import { parseOrganizationId, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";

export const dynamic="force-dynamic";export const revalidate=0;
type Row={id:string;document_number:string;document_type:string;accounting_date:string;description:string;debit_total:string;credit_total:string;created_by:string;reversal_of_document_id:string|null};
export default async function JournalRegisterPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{search?:string;from?:string;to?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}
 const query=await searchParams,search=query.search?.trim()||null,from=query.from||null,to=query.to||null;
 const validDate=(value:string|null)=>value===null||/^\d{4}-\d{2}-\d{2}$/.test(value);
 if(search&&search.length>100||!validDate(from)||!validDate(to)||(from&&to&&from>to))return <main className="content"><h1>Journal register</h1><p role="alert">Enter a valid date range and search within 100 characters.</p></main>;
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 let rows:Row[]=[];let forbidden=false;let canWrite=false;
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);if(!actor.capabilities.includes("ledger.read"))throw CommandError.forbidden();canWrite=actor.capabilities.includes("journal.write");const result=await runtime.client.rpc("read_journal_register",{p_organization_id:organizationId,p_search:search,p_from:from,p_to:to,p_limit:101});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();throw new Error("Journal register could not be loaded.");}if(!Array.isArray(result.data)||result.data.length>101)throw new Error("Invalid journal register response.");rows=result.data.map((value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Invalid journal row.");const row=value as Record<string,unknown>;parseUuid(row.id);if(row.organization_id!==organizationId||typeof row.document_number!=="string"||typeof row.document_type!=="string"||typeof row.accounting_date!=="string"||typeof row.description!=="string"||typeof row.debit_total!=="string"||typeof row.credit_total!=="string"||typeof row.created_by!=="string"||(row.reversal_of_document_id!==null&&typeof row.reversal_of_document_id!=="string"))throw new Error("Invalid journal row.");return row as unknown as Row;});}
 catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")forbidden=true;else throw error;}
 if(forbidden)return <main className="content"><h1>Access denied</h1><p>You need ledger.read to view posted journals.</p></main>;
 const shown=rows.slice(0,100);
 return <main className="content"><p className="eyebrow">Accounting</p><h1>Journal register</h1><p>Posted journal history is immutable. Corrections remain linked to their dated reversal.</p>{canWrite&&<p><Link className="primary" href={`/o/${organizationId}/accounting/journals/new`}>Create manual journal</Link></p>}<form className="panel toolbar" method="get"><label>Search number or memo<input name="search" type="search" maxLength={100} defaultValue={search??""}/></label><label>From<input name="from" type="date" defaultValue={from??""}/></label><label>To<input name="to" type="date" defaultValue={to??""}/></label><button type="submit">Filter</button></form><section className="panel"><h2>Posted journals</h2>{shown.length===0?<p>No posted journals match these filters.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Number</th><th>Type</th><th>Memo</th><th>Debit (BDT)</th><th>Credit (BDT)</th><th>Created by</th><th>History</th></tr></thead><tbody>{shown.map(row=><tr key={row.id}><td>{row.accounting_date}</td><td><Link href={`/o/${organizationId}/accounting/journals/${row.id}`}>{row.document_number}</Link></td><td>{row.document_type.replaceAll("_"," ")}</td><td>{row.description}</td><td>{row.debit_total}</td><td>{row.credit_total}</td><td>{row.created_by}</td><td>{row.reversal_of_document_id?<Link href={`/o/${organizationId}/accounting/journals/${row.reversal_of_document_id}`}>Original journal</Link>:"Original"}</td></tr>)}</tbody></table></div>}{rows.length===101&&<p>Showing the first 100 entries. Refine the filters to narrow the register.</p>}</section></main>;
}
