import { parseOrganizationId, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";

export const dynamic="force-dynamic";export const revalidate=0;
type Account={id:string;code:string;name:string};type Center={id:string;code:string;name:string};type Entry={line_id:string;journal_id:string;source_document_id:string;document_number:string;source_type:string;account_id:string;account_code:string;account_name:string;accounting_date:string;line_no:number;description:string;cost_center_id:string|null;debit:string;credit:string;movement:string;running_balance:string;opening_balance:string};
type Snapshot={company?:{name?:string;timezone?:string};generated_at?:string;ledger_cutoff_at?:string;provisional?:boolean};
export default async function GeneralLedgerPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{account?:string;from?:string;to?:string;source?:string;cost_center?:string;after_date?:string;after_journal?:string;after_line?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}
 const q=await searchParams;const validDate=(v:string|undefined)=>{if(!v)return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const parsed=new Date(`${v}T00:00:00.000Z`);return Number.isFinite(parsed.valueOf())&&parsed.toISOString().slice(0,10)===v;};const today=new Date().toISOString().slice(0,10);const from=q.from||"0001-01-01",to=q.to||today;
 let validCursor=true;try{if(q.after_date)parseUuid(q.after_journal??"");if(q.after_line&&(!/^\d+$/.test(q.after_line)||Number(q.after_line)<1))validCursor=false;}catch{validCursor=false;}
 if(!validDate(from)||!validDate(to)||from>to||(q.source?.length??0)>100||Boolean(q.after_date)!==Boolean(q.after_journal)||Boolean(q.after_date)!==Boolean(q.after_line)||!validDate(q.after_date)||!validCursor)return <main className="content"><h1>General ledger</h1><p role="alert">Choose valid dates and a source filter up to 100 characters.</p></main>;
 let accountId:string|null=null,centerId:string|null=null;try{if(q.account)accountId=parseUuid(q.account,"account");if(q.cost_center)centerId=parseUuid(q.cost_center,"cost_center");}catch{return <main className="content"><h1>General ledger</h1><p role="alert">Choose a valid account and cost center.</p></main>;}
 let accounts:Account[]=[],centers:Center[]=[],rows:Entry[]=[],forbidden=false,openingBalance="0.00",snapshot:Snapshot={};
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);if(!actor.capabilities.includes("ledger.read"))throw CommandError.forbidden();const [a,c]=await Promise.all([runtime.client.rpc("list_report_accounts",{p_organization_id:organizationId}),runtime.client.rpc("list_ledger_cost_centers",{p_organization_id:organizationId})]);if(a.error||c.error)throw a.error?.code==="42501"||c.error?.code==="42501"?CommandError.forbidden():new Error("Ledger filters could not be loaded.");if(!Array.isArray(a.data)||!Array.isArray(c.data))throw new Error("Invalid ledger filter lists.");accounts=a.data.map((v:unknown)=>{const x=v as Record<string,unknown>;return{id:parseUuid(x.id),code:String(x.code),name:String(x.name)};});centers=c.data.map((v:unknown)=>{const x=v as Record<string,unknown>;return{id:parseUuid(x.id),code:String(x.code),name:String(x.name)};});
  if(accountId){const result=await runtime.client.rpc("read_report_snapshot",{p_organization_id:organizationId,p_report_type:"general_ledger",p_filters:{account:accountId,from,to,...(q.source?{source:q.source}:{}),...(centerId?{cost_center:centerId}:{}),...(q.after_date?{after_date:q.after_date,after_journal:q.after_journal,after_line:q.after_line}:{}),limit:500}});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();if(result.error.code==="22023"||result.error.code==="P0002")throw CommandError.validation({query:"Choose a valid date range and page cursor."});throw new Error("General ledger could not be loaded.");}if(!result.data||typeof result.data!=="object"||Array.isArray(result.data))throw new Error("Invalid report snapshot.");const envelope=result.data as Record<string,unknown>;snapshot={company:envelope.company as Snapshot["company"],generated_at:String(envelope.generated_at??""),ledger_cutoff_at:String(envelope.ledger_cutoff_at??""),provisional:envelope.provisional===true};if(!envelope.data||typeof envelope.data!=="object"||Array.isArray(envelope.data))throw new Error("Invalid ledger snapshot data.");const reportData=envelope.data as Record<string,unknown>;openingBalance=String(reportData.opening_balance??"0.00");if(!Array.isArray(reportData.rows)||reportData.rows.length>501)throw new Error("Invalid ledger response.");rows=reportData.rows.map((v:unknown)=>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("Invalid ledger row.");const x=v as Record<string,unknown>;return{...x,line_id:parseUuid(x.line_id),journal_id:parseUuid(x.journal_id),source_document_id:parseUuid(x.source_document_id),account_id:parseUuid(x.account_id)} as unknown as Entry;});}
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")forbidden=true;else if(!(error instanceof CommandError))throw error;}
 if(forbidden)return <main className="content"><h1>Access denied</h1><p>You need ledger.read to view the general ledger.</p></main>;
 const shown=rows.slice(0,500),last=shown.at(-1);const next=rows.length===501&&last?new URLSearchParams({account:accountId!,from,to,...(q.source?{source:q.source}:{}),...(centerId?{cost_center:centerId}:{}),after_date:last.accounting_date,after_journal:last.journal_id,after_line:String(last.line_no)}):null;
 return <main className="content"><p className="eyebrow">Accounting · {snapshot.company?.name??"Current company"}</p><h1>General ledger</h1><p>Balances include posted entries only. Reversals appear on their accounting dates. Timezone: {snapshot.company?.timezone??"—"} · Ledger cutoff: {snapshot.ledger_cutoff_at??"Select an account"} · Generated: {snapshot.generated_at??"—"} · {snapshot.provisional?"Provisional":"Posted ledger"}</p><form className="panel toolbar" method="get"><label>Account<select name="account" required defaultValue={accountId??""}><option value="">Choose an account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>From<input name="from" type="date" defaultValue={q.from??""}/></label><label>To<input name="to" type="date" defaultValue={q.to??today}/></label><label>Source or memo<input name="source" type="search" maxLength={100} defaultValue={q.source??""}/></label><label>Cost center<select name="cost_center" defaultValue={centerId??""}><option value="">All cost centers</option>{centers.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><button type="submit">Show ledger</button></form>
 {accountId&&<section className="panel"><h2>{accounts.find(a=>a.id===accountId)?.code} · {accounts.find(a=>a.id===accountId)?.name}</h2><p>Opening balance at {from}: BDT {openingBalance}</p>{shown.length===0?<p>No posted activity in this range.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Source</th><th>Account line</th><th>Debit</th><th>Credit</th><th>Movement</th><th>Running balance</th></tr></thead><tbody>{shown.map(row=><tr key={row.line_id}><td>{row.accounting_date}</td><td><Link href={`/o/${organizationId}/accounting/journals/${row.source_document_id}`}>{row.document_number} · {row.source_type.replaceAll("_"," ")}</Link></td><td>{row.description}</td><td>{row.debit}</td><td>{row.credit}</td><td>{row.movement}</td><td>{row.running_balance}</td></tr>)}</tbody></table></div>}{next&&<p><Link className="secondary" href={`/o/${organizationId}/accounting/general-ledger?${next}`}>Next 500 entries</Link></p>}</section>}</main>;
}
