import { parseOrganizationId, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { decodeLedgerCursor, encodeLedgerCursor, readGeneralLedger, readLedgerAccounts } from "../../../../../server/reports/ledger.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";
export const dynamic="force-dynamic";export const revalidate=0;
export default async function GeneralLedgerPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{account?:string;from?:string;to?:string;cost_center?:string;source?:string;cutoff?:string;cursor?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId)}catch{redirect("/companies?error=not_found")}const query=await searchParams;const today=new Date().toISOString().slice(0,10),from=query.from??today,to=query.to??today;const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies),accounts=await readLedgerAccounts(runtime.client,actor),selected=accounts.find(a=>a.id===query.account);const ledger=selected?await readGeneralLedger(runtime.client,actor,{accountId:selected.id,from,to,costCenterId:query.cost_center,source:query.source,cutoff:query.cutoff,cursor:decodeLedgerCursor(query.cursor)}):null;const last=ledger?.items.at(-1);const next=ledger?.hasMore&&last?encodeLedgerCursor({accounting_date:String(last.accounting_date),posted_at:String(last.posted_at),journal_entry_id:parseUuid(last.journal_entry_id),line_no:Number(last.line_no)}):null;const nextQuery=new URLSearchParams({account:selected?.id??"",from,to,...(query.cost_center?{cost_center:query.cost_center}:{}),...(query.source?{source:query.source}:{}),...(ledger?{cutoff:ledger.cutoffAt}:{}),...(next?{cursor:next}:{})});
  return <main className="content"><p className="eyebrow">Accounting</p><h1>General ledger</h1><p>Posted activity sorted by accounting date, posting time, journal and line. Each page uses the same posting cutoff.</p><form className="panel toolbar" action={`/o/${organizationId}/accounting/general-ledger`} method="get"><label>Account<select name="account" required defaultValue={query.account??""><option value="">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>From date<input type="date" name="from" required defaultValue={from}/></label><label>Through date<input type="date" name="to" required defaultValue={to}/></label><label>Cost center ID<input name="cost_center" defaultValue={query.cost_center??""}/></label><label>Source number/type/memo<input name="source" maxLength={100} defaultValue={query.source??""}/></label><button type="submit">Apply filters</button></form>
  {query.account&&!selected?<p role="alert">Choose an account with posted ledger activity in this company.</p>:ledger&&selected?<section className="panel"><h2>{selected.code} · {selected.name}</h2><p>Opening balance before {from}: BDT {ledger.openingBalance} · Snapshot cutoff: {ledger.cutoffAt}</p>{ledger.items.length===0?<p>No posted journal lines match this date range and filters.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Journal / source</th><th>Memo / line</th><th>Debit (BDT)</th><th>Credit (BDT)</th><th>Running balance (Dr +)</th></tr></thead><tbody>{ledger.items.map((line,i)=><tr key={String(line.journal_line_id??i)}><td>{String(line.accounting_date)}</td><td><Link href={`/o/${organizationId}/accounting/journals/${String(line.journal_entry_id)}`}>{String(line.document_number)}</Link><small>{String(line.source_type).replaceAll("_"," ")}</small>{actor.capabilities.includes("documents.read")&&<small><Link href={`/o/${organizationId}/accounting/documents/${String(line.source_document_id)}`}>Source</Link></small>}</td><td>{String(line.memo||"—")}<small>{String(line.line_description||"")}</small></td><td>{String(line.debit)}</td><td>{String(line.credit)}</td><td>{String(line.running_balance)}</td></tr>)}</tbody><tfoot><tr><th colSpan={3}>Filtered period totals</th><th>{ledger.periodDebit}</th><th>{ledger.periodCredit}</th><th>Closing {ledger.closingBalance}</th></tr></tfoot></table></div>}{next&&<p><Link className="secondary" href={`/o/${organizationId}/accounting/general-ledger?${nextQuery.toString()}`}>Next 100 entries</Link></p>}</section>:<section className="panel"><h2>Select an account</h2><p>Only accounts with posted activity are listed. Choose an account and date range to drill into its source journals.</p></section>}
  </main>
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need ledger.read to view account activity.</p></main>;if(error instanceof CommandError&&error.code==="VALIDATION_ERROR")return <main className="content"><h1>Invalid filters</h1><p>Check account, date range, cost center and page cursor, then try again.</p></main>;throw error;}
}
