import { moneyUnits } from "@ams/accounting";
import { parseOrganizationId } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { bangladeshDate } from "../../../../../lib/date.ts";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";

export const dynamic="force-dynamic";export const revalidate=0;
type CashRow={cash_account_id:string;account_id:string;account_code:string;account_name:string;opening:string;closing:string};
type Activity={date:string;flow_class:string;cash_account:string;account_id:string;account_code:string;document_id:string;document_number:string|null;document_type:string;description:string;amount:string;exception_reason:string|null};
type Data={from:string;to:string;opening_cash:string;operating:string;investing:string;financing:string;internal_transfer_inflows:string;internal_transfer_outflows:string;internal_transfer_net:string;unclassified:string;unclassified_count:number;cash_equivalent_account_count:number;closing_cash:string;calculated_closing:string;reconciliation_difference:string;provisional:boolean;cash_accounts:CashRow[];activity:Activity[];exceptions:Activity[];cutoff_at:string;timezone:string};
type Snapshot={company:{name:string};generated_at:string;ledger_cutoff_at:string;provisional:boolean;data:Data};
const dateOk=(value:string|null|undefined)=>!!value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(new Date(`${value}T00:00:00Z`).getTime())&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value;
const money=(value:string)=>{if(!/^-?(0|[1-9]\d{0,13})(\.\d{1,2})?$/.test(value))throw new Error("Invalid cash-flow money value.");return value;};
const labels:Record<string,string>={operating:"Operating",investing:"Investing",financing:"Financing",internal_transfer:"Internal transfer",unclassified:"Unclassified"};
export default async function CashFlowPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{from?:string;to?:string}>}){
 let organizationId:ReturnType<typeof parseOrganizationId>;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}
 const query=await searchParams,today=bangladeshDate(),from=query.from??`${today.slice(0,4)}-01-01`,to=query.to??today;
 if(!dateOk(from)||!dateOk(to)||from>to)return <main className="content"><h1>Cash flow</h1><p role="alert">Enter a valid report date range.</p></main>;
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");let capabilities:readonly string[];
 try{capabilities=(await resolveActorContext(organizationId,runtime.dependencies)).capabilities;if(!capabilities.includes("reports.read"))throw CommandError.forbidden();}
 catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need reports.read to view cash flow.</p></main>;throw error;}
 let snapshot:Snapshot;try{const result=await runtime.client.rpc("read_cash_flow_snapshot",{p_organization_id:organizationId,p_from:from,p_to:to});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();if(result.error.code==="22023")throw CommandError.validation({period:"Choose a valid cash-flow range."});throw new Error("Cash-flow report could not be generated.");}if(!result.data||typeof result.data!=="object"||Array.isArray(result.data))throw new Error("Invalid cash-flow snapshot.");snapshot=result.data as Snapshot;if(!snapshot.data||!Array.isArray(snapshot.data.activity)||!Array.isArray(snapshot.data.cash_accounts)||!Array.isArray(snapshot.data.exceptions))throw new Error("Invalid cash-flow report data.");}
 catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need reports.read to view cash flow.</p></main>;if(error instanceof CommandError&&error.code==="VALIDATION_FAILED")return <main className="content"><h1>Cash flow</h1><p role="alert">Choose valid start and end dates.</p></main>;throw error;}
 const data=snapshot.data,provisional=snapshot.provisional||data.provisional,exportQuery=new URLSearchParams({from,to,format:"json"}),difference=moneyUnits(money(data.reconciliation_difference)),canDrill=capabilities.includes("ledger.read");
 function document(row:Activity){return canDrill?<Link href={`/o/${organizationId}/accounting/general-ledger?${new URLSearchParams({account:row.account_id,from:row.date,to:row.date})}`}>{row.document_number??row.document_type}</Link>:<span>{row.document_number??row.document_type}</span>;}
 return <main className="content"><p className="eyebrow">Reports · {snapshot.company.name}</p><h1>Cash-flow management report</h1><p>Cash equivalents are explicitly configured cash accounts. Non-cash entries and opening journals are excluded from current-period flows. Internal principal transfers between cash-equivalent accounts are shown separately; transfer fees are operating outflows. Classification uses the posted cash line and ledger snapshot. This is a management report, not an IAS 7 statutory statement. Timezone: {data.timezone} · Ledger cutoff: {snapshot.ledger_cutoff_at} · Generated: {snapshot.generated_at}</p>
  <form method="get" className="panel toolbar"><label>From<input type="date" name="from" required defaultValue={from}/></label><label>To<input type="date" name="to" required defaultValue={to}/></label><button type="submit">Run report</button>{capabilities.includes("reports.export")&&<a className="secondary" href={`/api/v1/organizations/${organizationId}/reports/cash_flow?${exportQuery}`}>Download JSON snapshot</a>}</form>
  <section className="panel"><h2>Reconciliation · {from} to {to}</h2><dl className="toolbar"><div><dt>Opening cash equivalents</dt><dd>BDT {money(data.opening_cash)}</dd></div><div><dt>Operating</dt><dd>BDT {money(data.operating)}</dd></div><div><dt>Investing</dt><dd>BDT {money(data.investing)}</dd></div><div><dt>Financing</dt><dd>BDT {money(data.financing)}</dd></div><div><dt>Internal transfer in / out</dt><dd>BDT {money(data.internal_transfer_inflows)} / {money(data.internal_transfer_outflows)}</dd></div><div><dt>Internal transfer net</dt><dd>BDT {money(data.internal_transfer_net)}</dd></div><div><dt>Unclassified net movement</dt><dd>BDT {money(data.unclassified)}</dd></div><div><dt>Calculated closing cash</dt><dd>BDT {money(data.calculated_closing)}</dd></div><div><dt>Ledger closing cash</dt><dd>BDT {money(data.closing_cash)}</dd></div><div><dt>Difference</dt><dd>BDT {money(data.reconciliation_difference)}</dd></div></dl><p role={provisional||difference!==0n?"alert":"status"}>{data.cash_equivalent_account_count===0?"Provisional · configure at least one cash-equivalent account.":provisional?`Provisional · ${data.unclassified_count} cash-line movement(s) need classification. Export remains available.`:difference!==0n?"Cash reconciliation mismatch; investigate before close review.":"Classified cash movements reconcile to the ledger. This report is not finalized."}</p></section>
  <section className="panel"><h2>Cash-equivalent accounts</h2>{data.cash_accounts.length===0?<p>No cash-equivalent accounts are configured.</p>:<div className="table-scroll"><table><thead><tr><th>Account</th><th>Opening (BDT)</th><th>Closing (BDT)</th></tr></thead><tbody>{data.cash_accounts.map(row=><tr key={row.cash_account_id}><td>{canDrill?<Link href={`/o/${organizationId}/accounting/general-ledger?${new URLSearchParams({account:row.account_id,from,to})}`}>{row.account_code} · {row.account_name}</Link>:`${row.account_code} · ${row.account_name}`}</td><td>{money(row.opening)}</td><td>{money(row.closing)}</td></tr>)}</tbody></table></div>}</section>
  {provisional&&<section className="panel"><h2>Classification exceptions</h2><p>Classify cash movements when preparing a draft. Posted journals remain immutable; a correction must use the documented accounting path.</p>{data.exceptions.length===0?<p>No unclassified exceptions.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Document</th><th>Cash account</th><th>Amount (BDT)</th><th>Reason</th></tr></thead><tbody>{data.exceptions.map((row,index)=><tr key={`${row.document_id}-${index}`}><td>{row.date}</td><td>{document(row)}</td><td>{row.account_code} · {row.cash_account}</td><td>{money(row.amount)}</td><td>{row.exception_reason}</td></tr>)}</tbody></table></div>}</section>}
  <section className="panel"><h2>Classified activity</h2>{data.activity.length===0?<p>No cash-equivalent activity in this period.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Class</th><th>Cash account</th><th>Document</th><th>Description</th><th>Movement (BDT)</th><th>Review note</th></tr></thead><tbody>{data.activity.map((row,index)=><tr key={`${row.document_id}-${index}`}><td>{row.date}</td><td>{labels[row.flow_class]??row.flow_class}</td><td>{row.account_code} · {row.cash_account}</td><td>{document(row)}</td><td>{row.description}</td><td>{money(row.amount)}</td><td>{row.exception_reason??"—"}</td></tr>)}</tbody></table></div>}</section>
 </main>;
}
