import { randomUUID } from "node:crypto";
import { expect, test } from "@playwright/test";
import { browserApi, localStack, openCompany } from "./support/local-auth.ts";

test("US-011 ordinary JWT directory RLS, private-schema denial and live revocation", async ({ browser }) => {
  const stack = localStack();
  const owner = await stack.user("us011-browser-owner", "Security Owner");
  const billing = await stack.user("us011-browser-billing", "Security Billing");
  const makeCompany = async (name: string) => {
    const result = await owner.client.rpc("create_company_atomic", { p_name: name, p_legal_name: name, p_country_code: "BD", p_base_currency: "BDT", p_timezone: "Asia/Dhaka", p_fiscal_year_start_month: 1, p_books_start_date: "2026-01-01", p_idempotency_key: randomUUID() });
    expect(result.error).toBeNull(); const id = result.data[0].organization_id as string;
    expect(id).toMatch(/^[a-f0-9-]{36}$/i); return id;
  };
  const org = await makeCompany("Security Company"), foreignOrg = await makeCompany("Security Other Company");
  const member = randomUUID(), invoice = randomUUID(), bill = randomUUID(), foreignInvoice = randomUUID();
  stack.sql(`insert into finance.organization_members(id,organization_id,user_id,display_name_snapshot) values('${member}','${org}','${billing.id}','Security Billing');
    insert into finance.member_roles(organization_id,member_id,role_id) select '${org}','${member}',id from finance.roles where organization_id='${org}' and template_key='billing';
    insert into finance.business_documents(id,organization_id,document_type,issue_date,accounting_date,total_amount,created_by_member_id) select '${invoice}','${org}','invoice','2026-01-01','2026-01-01',12.34,id from finance.organization_members where organization_id='${org}' and user_id='${owner.id}';
    insert into finance.business_documents(id,organization_id,document_type,issue_date,accounting_date,created_by_member_id) select '${bill}','${org}','bill','2026-01-01','2026-01-01',id from finance.organization_members where organization_id='${org}' and user_id='${owner.id}';
    insert into finance.business_documents(id,organization_id,document_type,issue_date,accounting_date,created_by_member_id) select '${foreignInvoice}','${foreignOrg}','invoice','2026-01-01','2026-01-01',id from finance.organization_members where organization_id='${foreignOrg}' and user_id='${owner.id}';`);
  const direct = await billing.client.rpc("read_document_directory", { p_organization_id: org });
  expect(direct.error).toBeNull(); expect(direct.data.map((r: { id: string }) => r.id)).toEqual([invoice]);
  const foreign = await billing.client.rpc("read_document_directory", { p_organization_id: foreignOrg });
  expect(foreign.error).toBeNull(); expect(foreign.data).toEqual([]);
  expect((await billing.client.schema("finance").from("business_documents").select("id")).error).not.toBeNull();
  expect((await billing.client.schema("finance_private").rpc("require_capability", { p_organization_id: org, p_capability: "users.manage" })).error).not.toBeNull();
  const metadata = await billing.client.auth.updateUser({ data: { role: "Owner", capabilities: ["*"] } }); expect(metadata.error).toBeNull();
  expect((await billing.client.rpc("list_roles_for_management", { p_organization_id: org })).error).not.toBeNull();
  const context = await browser.newContext(); const page = await context.newPage();
  await openCompany(page, billing, "Security Company");
  const response = await browserApi(page, `/api/v1/organizations/${org}/documents`);
  expect(response.status).toBe(200); expect(response.body.data).toHaveLength(1);
  expect(response.body.data[0].totalAmount).toBe("12.34");
  expect((await browserApi(page, `/api/v1/organizations/${foreignOrg}/documents`)).status).toBe(404);
  const jwt = (await billing.client.auth.getSession()).data.session!.access_token;
  const removed = await owner.client.rpc("deactivate_member", { p_organization_id: org, p_member_id: member, p_request_id: "req_us011_remove" }); expect(removed.error).toBeNull();
  expect((await billing.client.auth.getUser(jwt)).error).toBeNull();
  expect((await billing.client.rpc("read_document_directory", { p_organization_id: org })).data).toEqual([]);
  expect((await browserApi(page, `/api/v1/organizations/${org}/documents`)).status).toBe(404);
  await context.close();
});
