"use client";
import { useMemo,useState } from "react";
import type { AccountCatalog,AccountRow,MappingKey } from "../../../../../server/accounts/contracts.ts";
import styles from "./screen.module.css";

const labels:Record<string,string>={cash:"Cash",bank:"Bank",ar:"Accounts receivable",vendor_advance:"Supplier advances",input_tax:"Input tax",ap:"Accounts payable",output_tax:"Output tax",customer_advance:"Customer advances",retained_earnings:"Retained earnings",opening_suspense:"Opening suspense",rounding_difference:"Rounding difference"};
const required:Record<MappingKey,{type:string;control:string|null}>={cash:{type:"asset",control:null},bank:{type:"asset",control:null},ar:{type:"asset",control:"ar"},vendor_advance:{type:"asset",control:"vendor_advance"},input_tax:{type:"asset",control:null},ap:{type:"liability",control:"ap"},output_tax:{type:"liability",control:null},customer_advance:{type:"liability",control:"customer_advance"},retained_earnings:{type:"equity",control:null},opening_suspense:{type:"equity",control:null},rounding_difference:{type:"expense",control:null}};
type Props=AccountCatalog&{organizationId:string;nonce:string;canManage:boolean};
export function AccountManager({organizationId,nonce,accounts,mappings,canManage}:Props){
  const [view,setView]=useState<"tree"|"table">("tree");const [editing,setEditing]=useState<AccountRow|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  const [mapChoice,setMapChoice]=useState<Record<string,string>>(()=>Object.fromEntries(mappings.map(m=>[m.key,m.accountId])));
  const depth=useMemo(()=>{const byId=new Map(accounts.map(a=>[a.id,a]));return (a:AccountRow)=>{let d=0,p=a.parentId,seen=new Set<string>();while(p&&byId.has(p)&&!seen.has(p)){seen.add(p);d++;p=byId.get(p)?.parentId??null;}return d;}},[accounts]);
  async function submitAccount(form:FormData){setBusy(true);setError("");setMessage("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/accounts`,{method:"POST",headers:{"Content-Type":"application/json","X-Request-Id":`chart-${crypto.randomUUID()}`},body:JSON.stringify({account_id:editing?.id??null,expected_version:editing?.rowVersion??null,code:String(form.get("code")??""),name:String(form.get("name")??""),parent_id:String(form.get("parent_id")??"")||null,account_type:String(form.get("account_type")??"asset"),normal_side:String(form.get("normal_side")??"debit"),report_group:String(form.get("report_group")??""),control_kind:String(form.get("control_kind")??"")||null,is_postable:form.get("is_postable")==="on",is_active:form.get("is_active")==="on"})});const json=await response.json();if(!response.ok)throw new Error(json?.error?.fields?.account??json?.error?.fields?.code??json?.error?.message??"Could not save account.");setMessage("Account saved. Refresh to confirm the latest company chart.");setEditing(null);window.location.reload();}catch(e){setError(e instanceof Error?e.message:"Could not save account.");}finally{setBusy(false);}}
  async function submitMapping(key:MappingKey,version:number){setBusy(true);setError("");setMessage("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/account-mappings`,{method:"POST",headers:{"Content-Type":"application/json","X-Request-Id":`mapping-${crypto.randomUUID()}`},body:JSON.stringify({mapping_key:key,account_id:mapChoice[key],expected_version:version})});const json=await response.json();if(!response.ok)throw new Error(json?.error?.fields?.account??json?.error?.message??"Could not save mapping.");setMessage(`${labels[key]} mapping saved. Refresh to confirm.`);window.location.reload();}catch(e){setError(e instanceof Error?e.message:"Could not save mapping.");}finally{setBusy(false);}}
  const selected=editing;
  return <main className={styles.main} data-company-context={nonce}><p className="eyebrow">Accounting configuration</p><h1>Chart of accounts</h1>
    <p className="muted">Maintain company accounts and required posting mappings. Opening suspense is a visible control account; this screen never fills missing mappings automatically.</p>
    {error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.notice}>{message}</p>}
    {canManage&&<section className={`panel ${styles.panel}`}><div className={styles.heading}><div><h2>{selected?"Edit account":"Add account"}</h2><p>Classification becomes permanent when the account is first used in a posted journal.</p></div>{selected&&<button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel edit</button>}</div>
      <form action={submitAccount} className={styles.form} key={selected?.id??"new"}>
        <label>Code<input name="code" required maxLength={32} defaultValue={selected?.code??""}/></label><label>Name<input name="name" required maxLength={160} defaultValue={selected?.name??""}/></label>
        <label>Account type<select name="account_type" defaultValue={selected?.accountType??"asset"}>{["asset","liability","equity","income","expense"].map(x=><option key={x}>{x}</option>)}</select></label>
        <label>Normal side<select name="normal_side" defaultValue={selected?.normalSide??"debit"}><option value="debit">Debit</option><option value="credit">Credit</option></select></label>
        <label>Report group<input name="report_group" required maxLength={80} defaultValue={selected?.reportGroup??""}/></label>
        <label>Control kind<select name="control_kind" defaultValue={selected?.controlKind??""}><option value="">None</option>{["ar","ap","customer_advance","vendor_advance"].map(x=><option key={x} value={x}>{x}</option>)}</select></label>
        <label>Parent group<select name="parent_id" defaultValue={selected?.parentId??""}><option value="">Top level</option>{accounts.filter(a=>!a.isPostable&&a.accountType===(selected?.accountType??"asset")&&a.id!==selected?.id&&a.isActive).map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label>
        <label className={styles.check}><input name="is_postable" type="checkbox" defaultChecked={selected?.isPostable??true}/>Postable account</label>
        <label className={styles.check}><input name="is_active" type="checkbox" defaultChecked={selected?.isActive??true}/>Active</label>
        <button type="submit" disabled={busy}>{busy?"Saving…":selected?"Save account":"Create account"}</button>
      </form></section>}
    <section className={`panel ${styles.panel}`}><div className={styles.heading}><div><h2>Accounts</h2><p>{accounts.length} accounts · groups cannot receive postings</p></div><div className={styles.toggle}><button type="button" aria-pressed={view==="tree"} onClick={()=>setView("tree")}>Tree</button><button type="button" aria-pressed={view==="table"} onClick={()=>setView("table")}>Table</button></div></div>
      {accounts.length===0?<p>No accounts are configured for this company.</p>:<div className={styles.tableWrap}><table><thead><tr><th>Code</th><th>Name</th><th>Type / side</th><th>Report group</th><th>Control</th><th>State</th>{canManage&&<th>Action</th>}</tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.code}</td><td>{view==="tree"&&<span aria-hidden="true">{"　".repeat(Math.min(depth(a),8))}{a.parentId?"↳ ":""}</span>}{a.name}{a.isSystem&&<small className={styles.system}>System</small>}</td><td>{a.accountType} / {a.normalSide}</td><td>{a.reportGroup}</td><td>{a.controlKind??"—"}</td><td>{a.isActive?"Active":"Archived"}{!a.isPostable?" · Group":""}</td>{canManage&&<td><button type="button" className="secondary" onClick={()=>setEditing(a)}>Edit</button></td>}</tr>)}</tbody></table></div>}</section>
    <section className={`panel ${styles.panel}`}><h2>Required mappings</h2><p>Targets must be active, postable and match the documented control classification.</p><div className={styles.mappings}>{mappings.map(m=>{const rule=required[m.key];const options=accounts.filter(a=>a.isActive&&a.isPostable&&a.accountType===rule.type&&a.controlKind===rule.control);return <form key={m.key} onSubmit={e=>{e.preventDefault();void submitMapping(m.key,m.rowVersion);}}><label htmlFor={`map-${m.key}`}>{labels[m.key]}</label><select id={`map-${m.key}`} value={mapChoice[m.key]??m.accountId} onChange={e=>setMapChoice({...mapChoice,[m.key]:e.target.value})} disabled={!canManage||busy}>{options.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select>{canManage&&<button type="submit" disabled={busy||!options.length}>Save mapping</button>}</form>;})}</div>{mappings.length===0&&<p role="alert">Mapping records are missing. Posting must remain blocked until the controlled configuration is repaired.</p>}</section>
  </main>;
}
