"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { bangladeshDate } from "../../../../../lib/date.ts";
import type { SourceType } from "../../../../../server/documents/contracts.ts";
import styles from "./documents.module.css";

type Option={id:string;code?:string;name?:string;display_name?:string;kind?:string;label?:string;rate_percent?:string};
export type DraftOptions={accounts:Option[];parties:Option[];cash_accounts:Option[];rounding_accounts:Option[];tax_codes:Option[]};
type Line={id:string|null;original_line_id:string|null;description:string;quantity:string;unit_price:string;discount_amount:string;account_id:string;tax_code_id:string|null;tax_mode:"exclusive"|"inclusive"};
type Journal={account_id:string;debit:string;credit:string;description:string};
type Movement={cash_account_id:string;direction:"in"|"out";amount:string;method:string;reference:string;cash_flow_class:string};
type Plan={target_open_item_id:string;amount:string};
const labels:Record<SourceType,string>={invoice:"Sales invoice",customer_credit:"Customer credit",bill:"Supplier bill",vendor_credit:"Supplier credit",paid_expense:"Paid expense",receipt:"Customer receipt",vendor_payment:"Supplier payment",customer_refund:"Customer refund",vendor_refund:"Supplier refund",customer_advance:"Customer advance",vendor_advance:"Supplier advance",transfer:"Cash transfer",manual_journal:"Manual journal",controlled_adjustment:"Controlled adjustment",opening_balance:"Opening balance"};
const tradeTypes:SourceType[]=["invoice","customer_credit","bill","vendor_credit","paid_expense"];
const movementTypes:SourceType[]=["receipt","vendor_payment","customer_refund","vendor_refund","customer_advance","vendor_advance","paid_expense"];
const journalTypes:SourceType[]=["manual_journal","controlled_adjustment","opening_balance"];
const blankLine=(accountId=""):Line=>({id:null,original_line_id:null,description:"",quantity:"1",unit_price:"0.00",discount_amount:"0.00",account_id:accountId,tax_code_id:null,tax_mode:"exclusive"});
export function DraftEditor({organizationId,nonce,documentType,options,initial,expectedVersion}:{organizationId:string;nonce:string;documentType:SourceType;options:DraftOptions;initial?:Record<string,unknown>;expectedVersion?:number}){
 const router=useRouter();const idem=useRef<string>(crypto.randomUUID());const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [preview,setPreview]=useState("");
 const d=initial??{};const initialLines=Array.isArray(d.lines)?d.lines as Record<string,unknown>[]:[];
 const [lines,setLines]=useState<Line[]>(initialLines.length?initialLines.map((l)=>({id:String(l.id),original_line_id:l.original_line_id?String(l.original_line_id):null,description:String(l.description),quantity:String(l.quantity),unit_price:String(l.unit_price),discount_amount:String(l.discount_amount),account_id:String(l.account_id),tax_code_id:l.tax_code_id?String(l.tax_code_id):null,tax_mode:l.tax_mode==="inclusive"?"inclusive":"exclusive"})): [blankLine(options.accounts[0]?.id)]);
 const [journals,setJournals]=useState<Journal[]>(Array.isArray(d.journal_rows)?(d.journal_rows as Record<string,unknown>[]).map((r)=>({account_id:String(r.account_id),debit:String(r.debit),credit:String(r.credit),description:String(r.description)})): [{account_id:options.accounts[0]?.id??"",debit:"0.00",credit:"0.00",description:""}]);
 const [movement,setMovement]=useState<Movement>(()=>{const m=(d.movement&&typeof d.movement==="object"?d.movement:{}) as Record<string,unknown>;return{cash_account_id:String(m.cash_account_id??options.cash_accounts[0]?.id??""),direction:String(m.direction??(["receipt","customer_advance","vendor_refund"].includes(documentType)?"in":"out")) as "in"|"out",amount:String(m.amount??"0.00"),method:String(m.method??"bank_transfer"),reference:String(m.reference??""),cash_flow_class:String(m.cash_flow_class??"operating")};});
 const [allocationPlan,setAllocationPlan]=useState<Plan[]>(Array.isArray(d.allocation_plan)?(d.allocation_plan as Record<string,unknown>[]).map((p)=>({target_open_item_id:String(p.target_open_item_id),amount:String(p.amount)})):[]);
 const [trade,setTrade]=useState<Record<string,unknown>>(()=>d.trade&&typeof d.trade==="object"?d.trade as Record<string,unknown>:{recognition_mode:"earned_or_incurred",performance_confirmed:false});
 const [transfer,setTransfer]=useState<Record<string,string>>(()=>{const t=(d.transfer&&typeof d.transfer==="object"?d.transfer:{}) as Record<string,unknown>;return{from_cash_account_id:String(t.from_cash_account_id??options.cash_accounts[0]?.id??""),to_cash_account_id:String(t.to_cash_account_id??options.cash_accounts[1]?.id??""),amount:String(t.amount??"0.00"),fee_amount:String(t.fee_amount??"0.00"),fee_account_id:String(t.fee_account_id??options.accounts[0]?.id??"")};});
 const field=(name:string,fallback="")=>String(d[name]??fallback);
 async function submit(form:FormData){setBusy(true);setError("");const roundingAdjustment=String(form.get("rounding_adjustment")??"0.00");const payload={document_type:documentType,party_id:String(form.get("party_id")??"")||null,issue_date:String(form.get("issue_date")??""),accounting_date:String(form.get("accounting_date")??""),due_date:String(form.get("due_date")??"")||null,external_reference:String(form.get("external_reference")??"")||null,description:String(form.get("description")??""),currency:"BDT",rounding_adjustment:roundingAdjustment,rounding_reason:roundingAdjustment==="0.00"?null:String(form.get("rounding_reason")??""),rounding_account_id:roundingAdjustment==="0.00"?null:String(form.get("rounding_account_id")??"")||null,trade:tradeTypes.includes(documentType)?{...trade,original_document_id:String(form.get("original_document_id")??"")||null,supplier_invoice_date:String(form.get("supplier_invoice_date")??"")||null,supplier_invoice_key:String(form.get("supplier_invoice_key")??"")||null}:null,movement:movementTypes.includes(documentType)?movement:null,transfer:documentType==="transfer"?transfer:null,lines:tradeTypes.includes(documentType)?lines:[],journal_rows:journalTypes.includes(documentType)?journals:[],allocation_plan:allocationPlan.filter((p)=>p.target_open_item_id.trim()&&p.amount!=="0.00")};
  try{const url=`/api/v1/organizations/${organizationId}/documents${initial?`/${String(d.id)}`:""}`;const response=await fetch(url,{method:initial?"PATCH":"POST",headers:{"Content-Type":"application/json","X-Request-Id":`document-${crypto.randomUUID()}`,"Idempotency-Key":idem.current},body:JSON.stringify(initial?{expected_version:expectedVersion,draft:payload}:payload)});const json=await response.json();if(!response.ok)throw new Error(json?.error?.fields?.document??json?.error?.fields?.expected_version??json?.error?.message??"Could not save draft.");idem.current=crypto.randomUUID();router.push(`/o/${organizationId}/accounting/documents/${json.data.documentId}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save draft.");}finally{setBusy(false);}}
 async function previewPosting(){if(!initial)return;setError("");setPreview("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/documents/${String(d.id)}/preview-posting`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_version:expectedVersion})});const json=await response.json();if(!response.ok)throw new Error(json?.error?.message??"Could not preview draft.");setPreview(JSON.stringify(json.data.preview,null,2));}catch(e){setError(e instanceof Error?e.message:"Could not preview draft.");}}
 const needsParty=documentType!=="paid_expense"&&["invoice","customer_credit","bill","vendor_credit","receipt","vendor_payment","customer_refund","vendor_refund","customer_advance","vendor_advance"].includes(documentType);
 return <main className={styles.main} data-company-context={nonce}><p className="eyebrow">Draft source</p><h1>{initial?"Edit draft · ":"New "}{labels[documentType]}</h1><p className={styles.hint}>Saving creates or updates a draft only. It does not create a journal or move money.</p>{error&&<p role="alert" className={styles.error}>{error}</p>}
 <form action={submit} className={styles.form}>
  {needsParty&&<label>Customer or supplier<select name="party_id" required defaultValue={field("party_id")}>{options.parties.map((p)=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label>}
  <label>Issue date<input name="issue_date" type="date" required defaultValue={field("issue_date",bangladeshDate())}/></label><label>Accounting date<input name="accounting_date" type="date" required defaultValue={field("accounting_date",bangladeshDate())}/></label>
  <label>Due date<input name="due_date" type="date" defaultValue={field("due_date")}/></label><label>External reference<input name="external_reference" maxLength={160} defaultValue={field("external_reference")}/></label><label>Description<input name="description" maxLength={2000} defaultValue={field("description")}/></label>
  {tradeTypes.includes(documentType)&&<>
   {documentType==="customer_credit"||documentType==="vendor_credit"?<label>Original posted document ID<input name="original_document_id" required defaultValue={String(trade.original_document_id??"")}/></label>:null}
   {documentType==="invoice"&&<><label>Revenue recognition<select value={String(trade.recognition_mode??"earned_or_incurred")} onChange={(e)=>setTrade({...trade,recognition_mode:e.target.value})}><option value="earned_or_incurred">Earned or incurred</option><option value="deferred_revenue">Deferred revenue</option></select></label><label className={styles.check}><input type="checkbox" checked={Boolean(trade.performance_confirmed)} onChange={(e)=>setTrade({...trade,performance_confirmed:e.target.checked})}/>Service performance confirmed</label></>}
   {(documentType==="bill"||documentType==="vendor_credit")&&<><label>Supplier invoice date<input name="supplier_invoice_date" type="date" defaultValue={String(trade.supplier_invoice_date??"")}/></label><label>Supplier invoice reference<input name="supplier_invoice_key" maxLength={160} defaultValue={String(trade.supplier_invoice_key??"")}/></label></>}
   <section className={styles.wide}><h2>Lines</h2>{lines.map((line,i)=><div className={styles.line} key={line.id??i}>
     {line.id&&<input type="hidden" value={line.id} onChange={()=>{}}/>}<label>Description<input value={line.description} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></label><label>Quantity<input inputMode="decimal" value={line.quantity} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,quantity:e.target.value}:x))}/></label><label>Unit price<input inputMode="decimal" value={line.unit_price} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,unit_price:e.target.value}:x))}/></label>
     <label>Account<select value={line.account_id} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,account_id:e.target.value}:x))}>{options.accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>Tax code<select value={line.tax_code_id??""} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,tax_code_id:e.target.value||null}:x))}><option value="">No tax</option>{options.tax_codes.map((t)=><option key={t.id} value={t.id}>{t.code} · {t.label} ({t.rate_percent}%)</option>)}</select></label><label>Tax mode<select value={line.tax_mode} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,tax_mode:e.target.value as "inclusive"|"exclusive"}:x))}><option value="exclusive">Exclusive</option><option value="inclusive">Inclusive</option></select></label>
     {documentType.includes("credit")&&<label>Original line ID<input required value={line.original_line_id??""} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,original_line_id:e.target.value||null}:x))}/></label>}{lines.length>1&&<button type="button" className="secondary" onClick={()=>setLines(lines.filter((_,j)=>j!==i))}>Remove line</button>}
   </div>)}<button type="button" className="secondary" onClick={()=>setLines([...lines,blankLine(options.accounts[0]?.id)])}>Add line</button></section>
  </>}
  {movementTypes.includes(documentType)&&<section className={styles.wide}><h2>Cash movement</h2><div className={styles.line}><label>Cash/bank account<select value={movement.cash_account_id} onChange={(e)=>setMovement({...movement,cash_account_id:e.target.value})}>{options.cash_accounts.map((a)=><option key={a.id} value={a.id}>{a.name} · {a.kind}</option>)}</select></label><label>Amount (BDT)<input inputMode="decimal" value={movement.amount} onChange={(e)=>setMovement({...movement,amount:e.target.value})}/></label><label>Method<select value={movement.method} onChange={(e)=>setMovement({...movement,method:e.target.value})}>{["cash","bank_transfer","mobile_wallet","card","other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Reference<input value={movement.reference} onChange={(e)=>setMovement({...movement,reference:e.target.value})}/></label></div></section>}
  {(["receipt","vendor_payment"] as SourceType[]).includes(documentType)&&<section className={styles.wide}><h2>Settlement plan</h2><p>Targets must be same-company open items. Their available balance is checked again when the source posts.</p>{allocationPlan.map((plan,i)=><div className={styles.line} key={i}><label>Open item ID<input value={plan.target_open_item_id} onChange={(e)=>setAllocationPlan(allocationPlan.map((p,j)=>j===i?{...p,target_open_item_id:e.target.value}:p))}/></label><label>Amount (BDT)<input inputMode="decimal" value={plan.amount} onChange={(e)=>setAllocationPlan(allocationPlan.map((p,j)=>j===i?{...p,amount:e.target.value}:p))}/></label><button type="button" className="secondary" onClick={()=>setAllocationPlan(allocationPlan.filter((_,j)=>j!==i))}>Remove target</button></div>)}<button type="button" className="secondary" onClick={()=>setAllocationPlan([...allocationPlan,{target_open_item_id:"",amount:"0.00"}])}>Add settlement target</button></section>}
  {documentType==="transfer"&&<section className={styles.wide}><h2>Transfer</h2><div className={styles.line}>{(["from_cash_account_id","to_cash_account_id"] as const).map((key)=><label key={key}>{key==="from_cash_account_id"?"From":"To"}<select value={transfer[key]} onChange={(e)=>setTransfer({...transfer,[key]:e.target.value})}>{options.cash_accounts.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>)}<label>Amount<input value={transfer.amount} onChange={(e)=>setTransfer({...transfer,amount:e.target.value})}/></label><label>Fee<input value={transfer.fee_amount} onChange={(e)=>setTransfer({...transfer,fee_amount:e.target.value})}/></label><label>Fee expense account<select value={transfer.fee_account_id} onChange={(e)=>setTransfer({...transfer,fee_account_id:e.target.value})}>{options.accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label></div></section>}
  {journalTypes.includes(documentType)&&<section className={styles.wide}><h2>Journal rows</h2>{journals.map((row,i)=><div className={styles.line} key={i}><label>Account<select value={row.account_id} onChange={(e)=>setJournals(journals.map((x,j)=>j===i?{...x,account_id:e.target.value}:x))}>{options.accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>Debit<input value={row.debit} onChange={(e)=>setJournals(journals.map((x,j)=>j===i?{...x,debit:e.target.value,credit:"0.00"}:x))}/></label><label>Credit<input value={row.credit} onChange={(e)=>setJournals(journals.map((x,j)=>j===i?{...x,credit:e.target.value,debit:"0.00"}:x))}/></label><label>Description<input value={row.description} onChange={(e)=>setJournals(journals.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></label>{journals.length>1&&<button type="button" className="secondary" onClick={()=>setJournals(journals.filter((_,j)=>j!==i))}>Remove row</button>}</div>)}<button type="button" className="secondary" onClick={()=>setJournals([...journals,{account_id:options.accounts[0]?.id??"",debit:"0.00",credit:"0.00",description:""}])}>Add row</button></section>}
  <label>Explicit rounding (BDT)<input name="rounding_adjustment" defaultValue={field("rounding_adjustment","0.00")}/></label><label>Rounding reason<input name="rounding_reason" maxLength={500} defaultValue={field("rounding_reason")}/></label><label>Rounding account<select name="rounding_account_id" defaultValue={field("rounding_account_id")}><option value="">No rounding</option>{options.rounding_accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label>
  {initial&&<button type="button" className="secondary" disabled={busy} onClick={()=>void previewPosting()}>Preview posting</button>}{preview&&<pre className={styles.wide} aria-label="Posting preview">{preview}</pre>}<button type="submit" disabled={busy}>{busy?"Saving…":"Save draft"}</button>
 </form>
 </main>;
}
