"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { SourceType } from "../../../../../server/documents/contracts.ts";
import styles from "./documents.module.css";

type Option={id:string;code?:string;name?:string;display_name?:string;kind?:string;label?:string;rate_percent?:string};
type ItemOption={id:string;sku:string|null;name:string;unit:string;default_unit_price:string;sales_account_id:string|null;purchase_account_id:string|null;tax_code_id:string|null};
export type DraftOptions={accounts:Option[];parties:Option[];cash_accounts:Option[];rounding_accounts:Option[];tax_codes:Option[];items:ItemOption[];cost_centers:Option[]};
type Line={id:string|null;item_id:string|null;item_snapshot:Record<string,unknown>|null;original_line_id:string|null;description:string;quantity:string;unit_price:string;discount_amount:string;account_id:string;cost_center_id:string|null;cost_center_snapshot:Record<string,unknown>|null;tax_code_id:string|null;tax_mode:"exclusive"|"inclusive"};
type Journal={account_id:string;cost_center_id:string|null;debit:string;credit:string;description:string};
type Movement={cash_account_id:string;direction:"in"|"out";amount:string;method:string;reference:string;cash_flow_class:string};
type Plan={target_open_item_id:string;amount:string};
type ReceiptTarget={openItemId:string;documentId:string;documentNumber:string|null;issueDate:string;dueDate:string|null;totalAmount:string;residualAmount:string};
const labels:Record<SourceType,string>={invoice:"Sales invoice",customer_credit:"Customer credit",bill:"Supplier bill",vendor_credit:"Supplier credit",paid_expense:"Paid expense",receipt:"Customer receipt",vendor_payment:"Supplier payment",customer_refund:"Customer refund",vendor_refund:"Supplier refund",customer_advance:"Customer advance",vendor_advance:"Supplier advance",transfer:"Cash transfer",manual_journal:"Manual journal",controlled_adjustment:"Controlled adjustment",opening_balance:"Opening balance"};
const tradeTypes:SourceType[]=["invoice","customer_credit","bill","vendor_credit","paid_expense"];
const movementTypes:SourceType[]=["receipt","vendor_payment","customer_refund","vendor_refund","customer_advance","vendor_advance","paid_expense"];
const journalTypes:SourceType[]=["manual_journal","controlled_adjustment","opening_balance"];
const blankLine=(accountId=""):Line=>({id:null,item_id:null,item_snapshot:null,original_line_id:null,description:"",quantity:"1",unit_price:"0.00",discount_amount:"0.00",account_id:accountId,cost_center_id:null,cost_center_snapshot:null,tax_code_id:null,tax_mode:"exclusive"});
export function DraftEditor({organizationId,nonce,documentType,options,initial,expectedVersion,duplicate=false,createNew=false,receiptInvoices=[]}:{organizationId:string;nonce:string;documentType:SourceType;options:DraftOptions;initial?:Record<string,unknown>;expectedVersion?:number;duplicate?:boolean;createNew?:boolean;receiptInvoices?:ReceiptTarget[]}){
 const router=useRouter();const idem=useRef<string>(crypto.randomUUID());const submitIdem=useRef<string>(crypto.randomUUID());const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [preview,setPreview]=useState("");
 const d=initial??{};const initialLines=Array.isArray(d.lines)?d.lines as Record<string,unknown>[]:[];
 const [lines,setLines]=useState<Line[]>(initialLines.length?initialLines.map((l)=>({id:l.id?String(l.id):null,item_id:l.item_id?String(l.item_id):null,item_snapshot:l.item_snapshot&&typeof l.item_snapshot==="object"?l.item_snapshot as Record<string,unknown>:null,original_line_id:l.original_line_id?String(l.original_line_id):null,description:String(l.description),quantity:String(l.quantity),unit_price:String(l.unit_price),discount_amount:String(l.discount_amount),account_id:String(l.account_id),cost_center_id:l.cost_center_id?String(l.cost_center_id):null,cost_center_snapshot:l.cost_center_snapshot&&typeof l.cost_center_snapshot==="object"?l.cost_center_snapshot as Record<string,unknown>:null,tax_code_id:l.tax_code_id?String(l.tax_code_id):null,tax_mode:l.tax_mode==="inclusive"?"inclusive":"exclusive"})): [blankLine(options.accounts[0]?.id)]);
 const [journals,setJournals]=useState<Journal[]>(Array.isArray(d.journal_rows)?(d.journal_rows as Record<string,unknown>[]).map((r)=>({account_id:String(r.account_id),cost_center_id:r.cost_center_id?String(r.cost_center_id):null,debit:String(r.debit),credit:String(r.credit),description:String(r.description)})): [{account_id:options.accounts[0]?.id??"",cost_center_id:null,debit:"0.00",credit:"0.00",description:""}]);
 const [movement,setMovement]=useState<Movement>(()=>{const m=(d.movement&&typeof d.movement==="object"?d.movement:{}) as Record<string,unknown>;return{cash_account_id:String(m.cash_account_id??options.cash_accounts[0]?.id??""),direction:String(m.direction??(["receipt","customer_advance","vendor_refund"].includes(documentType)?"in":"out")) as "in"|"out",amount:String(m.amount??"0.00"),method:String(m.method??"bank_transfer"),reference:String(m.reference??""),cash_flow_class:String(m.cash_flow_class??"operating")};});
 const [allocationPlan,setAllocationPlan]=useState<Plan[]>(Array.isArray(d.allocation_plan)?(d.allocation_plan as Record<string,unknown>[]).map((p)=>({target_open_item_id:String(p.target_open_item_id),amount:String(p.amount)})):[]);
 const [trade,setTrade]=useState<Record<string,unknown>>(()=>d.trade&&typeof d.trade==="object"?d.trade as Record<string,unknown>:{recognition_mode:"earned_or_incurred",performance_confirmed:false});
 const [transfer,setTransfer]=useState<Record<string,string>>(()=>{const t=(d.transfer&&typeof d.transfer==="object"?d.transfer:{}) as Record<string,unknown>;return{from_cash_account_id:String(t.from_cash_account_id??options.cash_accounts[0]?.id??""),to_cash_account_id:String(t.to_cash_account_id??options.cash_accounts[1]?.id??""),amount:String(t.amount??"0.00"),fee_amount:String(t.fee_amount??"0.00"),fee_account_id:String(t.fee_account_id??options.accounts[0]?.id??"")};});
 const field=(name:string,fallback="")=>String(d[name]??fallback);
 const [receiptParty,setReceiptParty]=useState(field("party_id"));const [receiptDate,setReceiptDate]=useState(field("accounting_date",new Date().toISOString().slice(0,10)));
 const [receiptTargets,setReceiptTargets]=useState<ReceiptTarget[]>(receiptInvoices);const [receiptLoading,setReceiptLoading]=useState(false);
 async function refreshReceiptTargets(partyId:string,date:string){if(!partyId||!date){setReceiptTargets([]);return;}setReceiptLoading(true);setError("");try{const q=new URLSearchParams({party_id:partyId,accounting_date:date});const response=await fetch(`/api/v1/organizations/${organizationId}/receipt-allocation-options?${q}`);const json=await response.json();if(!response.ok)throw new Error(json?.error?.message??"Eligible invoices could not be loaded.");setReceiptTargets(Array.isArray(json.data)?json.data as ReceiptTarget[]:[]);}catch(e){setReceiptTargets([]);setError(e instanceof Error?e.message:"Eligible invoices could not be loaded.");}finally{setReceiptLoading(false);}}
 async function submit(form:FormData){setBusy(true);setError("");const roundingAdjustment=String(form.get("rounding_adjustment")??"0.00");const payload={document_type:documentType,party_id:String(form.get("party_id")??"")||null,issue_date:String(form.get("issue_date")??""),accounting_date:String(form.get("accounting_date")??""),due_date:String(form.get("due_date")??"")||null,external_reference:String(form.get("external_reference")??"")||null,description:String(form.get("description")??""),currency:"BDT",rounding_adjustment:roundingAdjustment,rounding_reason:roundingAdjustment==="0.00"?null:String(form.get("rounding_reason")??""),rounding_account_id:roundingAdjustment==="0.00"?null:String(form.get("rounding_account_id")??"")||null,trade:tradeTypes.includes(documentType)?{...trade,original_document_id:String(form.get("original_document_id")??"")||null,supplier_invoice_date:String(form.get("supplier_invoice_date")??"")||null,supplier_invoice_key:String(form.get("supplier_invoice_key")??"")||null}:null,movement:movementTypes.includes(documentType)?movement:null,transfer:documentType==="transfer"?transfer:null,lines:tradeTypes.includes(documentType)?lines.map((line)=>{const payloadLine:Record<string,unknown>={...line};delete payloadLine.item_snapshot;delete payloadLine.cost_center_snapshot;return payloadLine;}):[],journal_rows:journalTypes.includes(documentType)?journals:[],allocation_plan:allocationPlan.filter((p)=>p.target_open_item_id.trim()&&!/^0+(?:\.0+)?$/.test(p.amount.trim()))};
  try{const editing=!!initial&&!createNew;const url=`/api/v1/organizations/${organizationId}/documents${editing?`/${String(d.id)}`:""}`;const response=await fetch(url,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json","X-Request-Id":`document-${crypto.randomUUID()}`,"Idempotency-Key":idem.current},body:JSON.stringify(editing?{expected_version:expectedVersion,draft:payload}:payload)});const json=await response.json();if(!response.ok)throw new Error(json?.error?.fields?.document??json?.error?.fields?.expected_version??json?.error?.message??"Could not save draft.");idem.current=crypto.randomUUID();router.push(`/o/${organizationId}/accounting/documents/${json.data.documentId}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save draft.");}finally{setBusy(false);}}
 async function previewPosting(){if(!initial||createNew)return;setError("");setPreview("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/documents/${String(d.id)}/preview-posting`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_version:expectedVersion})});const json=await response.json();if(!response.ok)throw new Error(json?.error?.message??"Could not preview draft.");setPreview(JSON.stringify(json.data.preview,null,2));}catch(e){setError(e instanceof Error?e.message:"Could not preview draft.");}}
 async function submitForApproval(){if(!initial)return;setBusy(true);setError("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/documents/${String(d.id)}/submit`,{method:"POST",headers:{"Content-Type":"application/json","X-Request-Id":`document-submit-${crypto.randomUUID()}`,"Idempotency-Key":submitIdem.current},body:JSON.stringify({expected_version:expectedVersion})});const json=await response.json();if(!response.ok)throw new Error(json?.error?.fields?.approval??json?.error?.message??"Could not submit document for review.");submitIdem.current=crypto.randomUUID();router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not submit document for review.");}finally{setBusy(false);}}
 const needsParty=documentType!=="paid_expense"&&["invoice","customer_credit","bill","vendor_credit","receipt","vendor_payment","customer_refund","vendor_refund","customer_advance","vendor_advance"].includes(documentType);
 return <main className={styles.main} data-company-context={nonce}><p className="eyebrow">Draft source</p><h1>{duplicate?"Duplicate as new draft · ":initial&&!createNew?"Edit draft · ":"New "}{labels[documentType]}</h1><p className={styles.hint}>Saving creates or updates a draft only. It does not create a journal or move money.</p>{error&&<p role="alert" className={styles.error}>{error}</p>}
 <form action={submit} className={styles.form}>
  {needsParty&&<label>{documentType==="receipt"?"Customer":"Customer or supplier"}<select name="party_id" required value={documentType==="receipt"?receiptParty:undefined} defaultValue={documentType==="receipt"?undefined:field("party_id")} onChange={documentType==="receipt"?e=>{const party=e.target.value;setReceiptParty(party);setAllocationPlan([]);void refreshReceiptTargets(party,receiptDate);}:undefined}><option value="">Choose a customer</option>{options.parties.map((p)=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label>}
  <label>Issue date<input name="issue_date" type="date" required defaultValue={field("issue_date",new Date().toISOString().slice(0,10))}/></label><label>Accounting date<input name="accounting_date" type="date" required value={documentType==="receipt"?receiptDate:undefined} defaultValue={documentType==="receipt"?undefined:field("accounting_date",new Date().toISOString().slice(0,10))} onChange={documentType==="receipt"?e=>{const date=e.target.value;setReceiptDate(date);setAllocationPlan([]);void refreshReceiptTargets(receiptParty,date);}:undefined}/></label>
  <label>Due date<input name="due_date" type="date" defaultValue={field("due_date")}/></label><label>External reference<input name="external_reference" maxLength={160} defaultValue={field("external_reference")}/></label><label>Description<input name="description" maxLength={2000} defaultValue={field("description")}/></label>
  {tradeTypes.includes(documentType)&&<>
   {documentType==="customer_credit"||documentType==="vendor_credit"?<label>Original posted document ID<input name="original_document_id" required defaultValue={String(trade.original_document_id??"")}/></label>:null}
   {documentType==="invoice"&&<><label>Revenue recognition<select value={String(trade.recognition_mode??"earned_or_incurred")} onChange={(e)=>setTrade({...trade,recognition_mode:e.target.value})}><option value="earned_or_incurred">Earned or incurred</option><option value="deferred_revenue">Deferred revenue</option></select></label><label className={styles.check}><input type="checkbox" checked={Boolean(trade.performance_confirmed)} onChange={(e)=>setTrade({...trade,performance_confirmed:e.target.checked})}/>Service performance confirmed</label><label>Payment terms<input maxLength={500} value={String(trade.terms??"")} onChange={e=>setTrade({...trade,terms:e.target.value})}/></label><label className={styles.wide}>Invoice notes<textarea maxLength={4000} rows={4} value={String(trade.notes??"")} onChange={e=>setTrade({...trade,notes:e.target.value})}/></label></>}
   {(documentType==="bill"||documentType==="vendor_credit")&&<><label>Supplier invoice date<input name="supplier_invoice_date" type="date" defaultValue={String(trade.supplier_invoice_date??"")}/></label><label>Supplier invoice reference<input name="supplier_invoice_key" maxLength={160} defaultValue={String(trade.supplier_invoice_key??"")}/></label></>}
   <section className={styles.wide}><h2>Lines</h2>{lines.map((line,i)=><div className={styles.line} key={line.id??i}>
     {documentType!=="customer_credit"&&documentType!=="vendor_credit"&&<label>Service/non-stock item<select value={line.item_id??""} onChange={e=>{const item=options.items.find(x=>x.id===e.target.value);const accountId=item?(documentType==="invoice"?item.sales_account_id:item.purchase_account_id):null;setLines(lines.map((x,j)=>j===i?{...x,item_id:item?.id??null,item_snapshot:item?{name:item.name,sku:item.sku,unit:item.unit}:null,description:item?.name??x.description,unit_price:documentType==="invoice"?(item?.default_unit_price??x.unit_price):x.unit_price,account_id:accountId&&options.accounts.some(a=>a.id===accountId)?accountId:x.account_id,tax_code_id:item?.tax_code_id??x.tax_code_id}:x));}}><option value="">No catalogue item</option>{line.item_id&&!options.items.some(x=>x.id===line.item_id)&&<option value={line.item_id}>{String(line.item_snapshot?.name??"Archived item")}</option>}{options.items.map(item=><option key={item.id} value={item.id}>{item.sku?`${item.sku} · `:""}{item.name} ({item.unit})</option>)}</select></label>}
     {line.id&&<input type="hidden" value={line.id} onChange={()=>{}}/>}<label>Description<input value={line.description} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></label><label>Quantity<input inputMode="decimal" value={line.quantity} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,quantity:e.target.value}:x))}/></label><label>Unit price<input inputMode="decimal" value={line.unit_price} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,unit_price:e.target.value}:x))}/></label>
     {typeof line.item_snapshot?.unit === "string"&&<p>Unit snapshot: {line.item_snapshot.unit}</p>}<label>Account<select value={line.account_id} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,account_id:e.target.value}:x))}>{options.accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>Cost-center tag<select value={line.cost_center_id??""} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,cost_center_id:e.target.value||null,cost_center_snapshot:options.cost_centers.find(c=>c.id===e.target.value)?{id:e.target.value,code:options.cost_centers.find(c=>c.id===e.target.value)?.code,name:options.cost_centers.find(c=>c.id===e.target.value)?.name}:null}:x))}><option value="">No cost center</option>{line.cost_center_id&&!options.cost_centers.some(c=>c.id===line.cost_center_id)&&<option value={line.cost_center_id}>{String(line.cost_center_snapshot?.code??"")} · {String(line.cost_center_snapshot?.name??"Archived cost center")}</option>}{options.cost_centers.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><label>Tax code<select value={line.tax_code_id??""} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,tax_code_id:e.target.value||null}:x))}><option value="">No tax</option>{options.tax_codes.map((t)=><option key={t.id} value={t.id}>{t.code} · {t.label} ({t.rate_percent}%)</option>)}</select></label><label>Tax mode<select value={line.tax_mode} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,tax_mode:e.target.value as "inclusive"|"exclusive"}:x))}><option value="exclusive">Exclusive</option><option value="inclusive">Inclusive</option></select></label>
     {documentType.includes("credit")&&<label>Original line ID<input required value={line.original_line_id??""} onChange={(e)=>setLines(lines.map((x,j)=>j===i?{...x,original_line_id:e.target.value||null}:x))}/></label>}{lines.length>1&&<button type="button" className="secondary" onClick={()=>setLines(lines.filter((_,j)=>j!==i))}>Remove line</button>}
   </div>)}<button type="button" className="secondary" onClick={()=>setLines([...lines,blankLine(options.accounts[0]?.id)])}>Add line</button></section>
  </>}
  {movementTypes.includes(documentType)&&<section className={styles.wide}><h2>Cash movement</h2><div className={styles.line}><label>Cash/bank account<select value={movement.cash_account_id} onChange={(e)=>setMovement({...movement,cash_account_id:e.target.value})}>{options.cash_accounts.map((a)=><option key={a.id} value={a.id}>{a.name} · {a.kind}</option>)}</select></label><label>Amount (BDT)<input inputMode="decimal" value={movement.amount} onChange={(e)=>setMovement({...movement,amount:e.target.value})}/></label><label>Method<select value={movement.method} onChange={(e)=>setMovement({...movement,method:e.target.value})}>{["cash","bank_transfer","mobile_wallet","card","other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Reference<input value={movement.reference} onChange={(e)=>setMovement({...movement,reference:e.target.value})}/></label></div></section>}
  {documentType==="receipt"&&<section className={styles.wide}><h2>Invoice allocation</h2><p>Balances are calculated for this accounting date; the posting command checks all selected invoices and the receipt capacity again.</p>{receiptLoading&&<p role="status">Loading eligible invoices…</p>}{!receiptParty?<p>Choose a customer to see their open invoices.</p>:!receiptLoading&&receiptTargets.length===0?<p>No eligible open invoices for this customer and date. Any unallocated receipt remains visible as customer trade credit.</p>:<div className="table-scroll"><table><thead><tr><th>Select invoice</th><th>Issue date</th><th>Due date</th><th>Invoice total</th><th>Available (BDT)</th><th>Apply (BDT)</th></tr></thead><tbody>{receiptTargets.map(target=>{const plan=allocationPlan.find(p=>p.target_open_item_id===target.openItemId);return <tr key={target.openItemId}><td><label><input type="checkbox" checked={!!plan} onChange={e=>setAllocationPlan(e.target.checked?[...allocationPlan,{target_open_item_id:target.openItemId,amount:"0.00"}]:allocationPlan.filter(p=>p.target_open_item_id!==target.openItemId))}/>{target.documentNumber??target.documentId}</label></td><td>{target.issueDate}</td><td>{target.dueDate??"—"}</td><td>{target.totalAmount}</td><td>{target.residualAmount}</td><td>{plan&&<input aria-label={`Amount to apply to invoice ${target.documentNumber??target.documentId}`} inputMode="decimal" value={plan.amount} onChange={e=>setAllocationPlan(allocationPlan.map(p=>p.target_open_item_id===target.openItemId?{...p,amount:e.target.value}:p))}/>}</td></tr>;})}</tbody></table></div>}{documentType!=="receipt"&&null}</section>}
  {documentType==="vendor_payment"&&<section className={styles.wide}><h2>Settlement plan</h2><p>Targets must be same-company open items. Their available balance is checked again when the source posts.</p>{allocationPlan.map((plan,i)=><div className={styles.line} key={i}><label>Open item ID<input value={plan.target_open_item_id} onChange={(e)=>setAllocationPlan(allocationPlan.map((p,j)=>j===i?{...p,target_open_item_id:e.target.value}:p))}/></label><label>Amount (BDT)<input inputMode="decimal" value={plan.amount} onChange={(e)=>setAllocationPlan(allocationPlan.map((p,j)=>j===i?{...p,amount:e.target.value}:p))}/></label><button type="button" className="secondary" onClick={()=>setAllocationPlan(allocationPlan.filter((_,j)=>j!==i))}>Remove target</button></div>)}<button type="button" className="secondary" onClick={()=>setAllocationPlan([...allocationPlan,{target_open_item_id:"",amount:"0.00"}])}>Add settlement target</button></section>}
  {documentType==="transfer"&&<section className={styles.wide}><h2>Transfer</h2><div className={styles.line}>{(["from_cash_account_id","to_cash_account_id"] as const).map((key)=><label key={key}>{key==="from_cash_account_id"?"From":"To"}<select value={transfer[key]} onChange={(e)=>setTransfer({...transfer,[key]:e.target.value})}>{options.cash_accounts.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>)}<label>Amount<input value={transfer.amount} onChange={(e)=>setTransfer({...transfer,amount:e.target.value})}/></label><label>Fee<input value={transfer.fee_amount} onChange={(e)=>setTransfer({...transfer,fee_amount:e.target.value})}/></label><label>Fee expense account<select value={transfer.fee_account_id} onChange={(e)=>setTransfer({...transfer,fee_account_id:e.target.value})}>{options.accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label></div></section>}
  {journalTypes.includes(documentType)&&<section className={styles.wide}><h2>Journal rows</h2>{journals.map((row,i)=><div className={styles.line} key={i}><label>Account<select value={row.account_id} onChange={(e)=>setJournals(journals.map((x,j)=>j===i?{...x,account_id:e.target.value}:x))}>{options.accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>Cost-center tag<select value={row.cost_center_id??""} onChange={e=>setJournals(journals.map((x,j)=>j===i?{...x,cost_center_id:e.target.value||null}:x))}><option value="">No cost center</option>{options.cost_centers.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><label>Debit<input value={row.debit} onChange={(e)=>setJournals(journals.map((x,j)=>j===i?{...x,debit:e.target.value,credit:"0.00"}:x))}/></label><label>Credit<input value={row.credit} onChange={(e)=>setJournals(journals.map((x,j)=>j===i?{...x,credit:e.target.value,debit:"0.00"}:x))}/></label><label>Description<input value={row.description} onChange={(e)=>setJournals(journals.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></label>{journals.length>1&&<button type="button" className="secondary" onClick={()=>setJournals(journals.filter((_,j)=>j!==i))}>Remove row</button>}</div>)}<button type="button" className="secondary" onClick={()=>setJournals([...journals,{account_id:options.accounts[0]?.id??"",cost_center_id:null,debit:"0.00",credit:"0.00",description:""}])}>Add row</button></section>}
  <label>Explicit rounding (BDT)<input name="rounding_adjustment" defaultValue={field("rounding_adjustment","0.00")}/></label><label>Rounding reason<input name="rounding_reason" maxLength={500} defaultValue={field("rounding_reason")}/></label><label>Rounding account<select name="rounding_account_id" defaultValue={field("rounding_account_id")}><option value="">No rounding</option>{options.rounding_accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label>
  {initial&&!createNew&&<button type="button" className="secondary" disabled={busy} onClick={()=>void previewPosting()}>Preview posting</button>}{preview&&<pre className={styles.wide} aria-label="Posting preview">{preview}</pre>}<button type="submit" disabled={busy}>{busy?"Saving…":"Save draft"}</button>{initial&&!createNew&&<button type="button" disabled={busy} onClick={()=>void submitForApproval()}>{busy?"Submitting…":"Submit for approval"}</button>}
 </form>
 </main>;
}
