begin; create extension if not exists pgtap with schema extensions;
-- Synthetic deterministic tokens are only fixtures, never application tokens.
CREATE FUNCTION pg_temp.uid(n integer) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$ SELECT ('10100000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid $$;
CREATE FUNCTION pg_temp.rid(n integer) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$ SELECT ('10100000-1000-4000-8000-'||lpad(n::text,12,'0'))::uuid $$;
CREATE FUNCTION pg_temp.iid(n integer) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$ SELECT ('10100000-2000-4000-8000-'||lpad(n::text,12,'0'))::uuid $$;
CREATE FUNCTION pg_temp.token(n integer) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT lpad(n::text,43,'x') $$;
CREATE FUNCTION pg_temp.digest(n integer) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT encode(sha256(convert_to(pg_temp.token(n),'UTF8')),'hex') $$;
CREATE FUNCTION pg_temp.envelope() RETURNS jsonb LANGUAGE sql IMMUTABLE AS $$ SELECT jsonb_build_object('version',1,'iv',repeat('a',16),'tag',repeat('b',22),'ciphertext',repeat('c',58)) $$;
CREATE FUNCTION pg_temp.issue(n integer,recipient integer,role_number integer DEFAULT 3) RETURNS uuid LANGUAGE sql AS $$
 SELECT public.issue_company_invitation('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pg_temp.iid(n),'recipient'||recipient||'@example.invalid',pg_temp.rid(role_number),pg_temp.digest(n),pg_temp.envelope(),'req_invite_'||n)
$$;
CREATE FUNCTION pg_temp.inspect(n integer) RETURNS TABLE(organization_id uuid,organization_name text,role_name text,expires_at timestamptz) LANGUAGE sql AS $$ SELECT * FROM public.inspect_company_invitation(pg_temp.token(n)) $$;
CREATE FUNCTION pg_temp.respond(n integer,decision text DEFAULT 'accept') RETURNS TABLE(organization_id uuid,member_id uuid,invitation_status text) LANGUAGE sql AS $$ SELECT * FROM public.respond_company_invitation(pg_temp.token(n),decision,'req_respond_'||n) $$;

\ir ../helpers/us005_two_company_fixture.psql
update auth.users set email_confirmed_at=now(),last_sign_in_at=now() where id='11111111-1111-4111-8111-111111111111';
insert into auth.users(id,email,email_confirmed_at,last_sign_in_at) values (pg_temp.uid(1),'recipient1@example.invalid',now(),now()),(pg_temp.uid(2),'recipient2@example.invalid',now(),now()),(pg_temp.uid(3),'recipient3@example.invalid',now(),now()),(pg_temp.uid(4),'recipient4@example.invalid',NULL,now()),(pg_temp.uid(5),'recipient5@example.invalid',now(),now()),(pg_temp.uid(6),'recipient6@example.invalid',now(),now()),(pg_temp.uid(7),'recipient7@example.invalid',now(),now()),(pg_temp.uid(8),'recipient8@example.invalid',now(),now());
insert into finance.roles(id,organization_id,name,template_key,is_system) values (pg_temp.rid(1),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Invite Owner','owner',true),(pg_temp.rid(2),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Invite Admin','admin',true),(pg_temp.rid(3),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Invite Billing','billing',true);
insert into finance.member_roles(organization_id,member_id,role_id) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa',pg_temp.rid(1));
insert into finance.organization_members(id,organization_id,user_id,display_name_snapshot) values ('10100000-3000-4000-8000-000000000001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pg_temp.uid(1),'Invite Admin');
insert into finance.member_roles(organization_id,member_id,role_id) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','10100000-3000-4000-8000-000000000001',pg_temp.rid(2));

select plan(58);
select ok(not has_column_privilege('authenticated','finance.invitations','token_hash','SELECT'),'Token hashes are not exposed to ordinary readers');
select ok(has_column_privilege('authenticated','finance.invitations','email_normalized','SELECT'),'Safe metadata remains permission scoped');
reset role; set local role authenticated; set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
select lives_ok($$select pg_temp.issue(2,2,3)$$,'Owner issues explicit organization and role invitation');
select throws_ok($$select pg_temp.issue(9,2,3)$$,'23505',NULL,'Duplicate pending recipient cannot create another invitation');
select throws_ok($$select pg_temp.issue(10,1,3)$$,'23505',NULL,'An active colleague cannot be reinvited');
select throws_ok($$select public.issue_company_invitation('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',pg_temp.iid(11),'recipient3@example.invalid',pg_temp.rid(3),pg_temp.digest(11),pg_temp.envelope(),'req_invite_11')$$,'42501',NULL,'Membership without users.manage cannot issue cross-tenant invite');
select throws_ok($$select public.issue_company_invitation('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pg_temp.iid(12),'us005-dual@example.invalid',pg_temp.rid(3),pg_temp.digest(12),pg_temp.envelope(),'req_self')$$,'42501',NULL,'Self invitation cannot escalate privilege');
select throws_ok($$select public.issue_company_invitation('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pg_temp.iid(12),'x@example.invalid','bbbbbbbb-2222-4222-8222-bbbbbbbbbbbb',pg_temp.digest(12),pg_temp.envelope(),'req_foreign')$$,'22023',NULL,'A foreign-company role is rejected');
select throws_ok($$select public.issue_company_invitation('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pg_temp.iid(12),'x@example.invalid',pg_temp.rid(3),pg_temp.digest(12),'[]'::jsonb,'req_bad_delivery')$$,'22023',NULL,'Malformed delivery envelope rolls back atomically');
select throws_ok($$select public.resend_company_invitation('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pg_temp.iid(2),pg_temp.digest(20),pg_temp.envelope(),'req_resend_fast')$$,'P0429',NULL,'Immediate resend is throttled');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000001';
select throws_ok($$select pg_temp.issue(12,3,1)$$,'42501',NULL,'Admin cannot invite Owner');
select throws_ok($$select pg_temp.issue(12,3,3)$$,'42501',NULL,'Admin cannot grant financial Billing capability it lacks');
select lives_ok($$select pg_temp.issue(3,3,2)$$,'Admin can invite only grant-bounded administrative role');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000003';
select throws_ok($$select * from pg_temp.inspect(2)$$,'P0002',NULL,'Wrong recipient cannot see company or role');
select throws_ok($$select * from pg_temp.respond(2,'accept')$$,'P0002',NULL,'Wrong recipient cannot accept another email invitation');
select lives_ok($$select * from pg_temp.respond(3,'reject')$$,'Verified intended recipient can reject invitation');
select throws_ok($$select * from pg_temp.respond(3,'accept')$$,'P0002',NULL,'Rejected token is consumed and cannot accept');
reset role; set local role authenticated; set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
select lives_ok($$select pg_temp.issue(4,4,3)$$,'Owner can invite an address before it has verified an account');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000004';
select throws_ok($$select * from pg_temp.inspect(4)$$,'42501',NULL,'Unverified recipient sees no invitation information');
select throws_ok($$select * from pg_temp.respond(4,'accept')$$,'42501',NULL,'Unverified email cannot join');
reset role;
select is((select count(*)::int from finance.invitations where id=pg_temp.iid(12)),0,'Failed envelope and escalation leave no invitation row');
select is((select count(*)::int from finance.outbox_events where event_type='invitation.send'),3,'One durable event per successful invitation generation');
select ok((select token_hash=pg_temp.digest(2) and expires_at>now() and expires_at<=now()+interval '72 hours' from finance.invitations where id=pg_temp.iid(2)),'Token is hashed and has a bounded expiry');
select ok(not exists(select 1 from finance.outbox_events where payload::text like '%'||lpad('2',43,'x')||'%'),'Raw bearer token does not appear in outbox');
select is((select count(*)::int from finance.organization_members where user_id=pg_temp.uid(3)),0,'Rejection creates no membership');
select is((select count(*)::int from finance.audit_events where entity_id=pg_temp.iid(3) and action='invitations.rejected'),1,'Rejection preserves verified-identity audit without member creation');
update finance.invitations set last_issued_at=now()-interval '61 seconds' where id=pg_temp.iid(2);
reset role; set local role authenticated; set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
select lives_ok($$select public.resend_company_invitation('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pg_temp.iid(2),pg_temp.digest(20),pg_temp.envelope(),'req_rotated')$$,'Authorized resend rotates and queues a fresh token');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000002';
select throws_ok($$select * from pg_temp.inspect(2)$$,'P0002',NULL,'Old token immediately stops working after resend');
select throws_ok($$select * from public.inspect_company_invitation(pg_temp.digest(20))$$,'P0002',NULL,'Stored token hash is not a valid bearer token');
select lives_ok($$select * from pg_temp.inspect(20)$$,'Matching verified recipient can see organization and proposed role');
select lives_ok($$select * from pg_temp.respond(20,'accept')$$,'Fresh token creates exact scoped membership atomically');
select throws_ok($$select * from pg_temp.respond(20,'accept')$$,'P0002',NULL,'Consumed token cannot create duplicate membership');
reset role;
select is((select count(*)::int from finance.organization_members where organization_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' and user_id=pg_temp.uid(2)),1,'Acceptance produces exactly one membership');
select is((select count(*)::int from finance.member_roles mr join finance.organization_members m on m.id=mr.member_id where m.user_id=pg_temp.uid(2) and mr.role_id=pg_temp.rid(3)),1,'Accepted recipient gets exactly the selected role');
select is((select generation from finance.invitations where id=pg_temp.iid(2)),2,'Resend tracks a new generation');
select ok(not exists(select 1 from finance.outbox_events where payload->>'invitation_id'=pg_temp.iid(2)::text and payload?'delivery'),'Consumed invitation encrypted delivery payloads are purged');
reset role; set local role authenticated; set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
select lives_ok($$select public.deactivate_member('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(select member_id from public.list_members_for_management('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa') where display_name='recipient2'),'req_revoke_invitee')$$,'Revocation uses the supported live-authorized command');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000002';
select is((select count(*)::int from public.resolve_active_membership('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')),0,'S-07 old identity/JWT no longer resolves active membership');
select throws_ok($$select * from public.list_roles_for_management('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')$$,'42501',NULL,'Removed member is denied at next protected RPC');
reset role; set local role authenticated; set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
select lives_ok($$select pg_temp.issue(22,2,2)$$,'New explicit invitation can authorize a previously removed colleague');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000002';
select lives_ok($$select * from pg_temp.respond(22,'accept')$$,'Rejoining reuses historical member identity without old privileges');
reset role;
select is((select count(*)::int from finance.organization_members where organization_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' and user_id=pg_temp.uid(2)),1,'Reactivation does not create duplicate historical identity');
select is((select count(*)::int from finance.member_roles mr join finance.organization_members m on m.id=mr.member_id where m.user_id=pg_temp.uid(2) and mr.role_id=pg_temp.rid(3)),0,'Reactivation does not restore removed Billing role');
reset role; set local role authenticated; set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
select lives_ok($$select pg_temp.issue(5,5,3)$$,'Issue invitation for expiry test');
reset role; update finance.invitations set expires_at=now()-interval '1 second' where id=pg_temp.iid(5);
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000005';
select throws_ok($$select * from pg_temp.respond(5,'accept')$$,'P0002',NULL,'Expired invitation cannot grant membership');
reset role; set local role authenticated; set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
select lives_ok($$select pg_temp.issue(6,6,3)$$,'Issue invitation for revocation test');
select lives_ok($$select public.revoke_company_invitation('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pg_temp.iid(6),'req_cancel')$$,'Issuer can revoke pending invitation');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000006';
select throws_ok($$select * from pg_temp.respond(6,'accept')$$,'P0002',NULL,'Revoked invitation cannot grant membership');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000001';
select lives_ok($$select pg_temp.issue(7,7,2)$$,'Admin issues invitation before losing authority');
reset role; set local role authenticated; set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
select lives_ok($$select public.deactivate_member('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','10100000-3000-4000-8000-000000000001','req_revoke_issuer')$$,'Revocation removes issuer authority');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000007';
select throws_ok($$select * from pg_temp.respond(7,'accept')$$,'P0002',NULL,'Issuer removal invalidates pending invitation immediately');
reset role;
select is((select status from finance.invitations where id=pg_temp.iid(7)),'revoked'::text,'Pending invitations from removed issuer are explicitly revoked');
insert into finance.roles(id,organization_id,name) values (pg_temp.rid(4),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Snapshot role');
reset role; set local role authenticated; set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
select lives_ok($$select pg_temp.issue(8,8,4)$$,'Issue custom role invitation with immutable grant snapshot');
select lives_ok($$select public.update_custom_role('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pg_temp.rid(4),'Snapshot role',array['sales.read'],'req_change_snapshot')$$,'Role may be edited through authorized command');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000008';
select throws_ok($$select * from pg_temp.respond(8,'accept')$$,'P0002',NULL,'Changed role snapshot cannot silently expand invitation privilege');
reset role; set local role authenticated; set local request.jwt.claim.sub='10100000-0000-4000-8000-000000000002';
select throws_ok($$select token_hash from finance.invitations$$,'42501',NULL,'Even users.read does not expose invitation hashes');
select throws_ok($$select * from finance.outbox_events$$,'42501',NULL,'Encrypted delivery queue is not exposed to ordinary callers');
reset role; set local role anon;
select throws_ok($$select * from pg_temp.inspect(8)$$,'42501',NULL,'Anonymous users cannot invoke recipient RPC');
reset role; select * from finish(); rollback;
