import { parseOrganizationId, parseUuid, type Uuid } from "@ams/contracts";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { ActorContext } from "../auth/types.ts";
import { CommandError } from "../commands/errors.ts";

type RpcClient=Pick<SupabaseClient,"rpc">;
const record=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("Invalid ledger report response.");return v as Record<string,unknown>;};
export const validReportDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(`${v}T00:00:00Z`))&&new Date(`${v}T00:00:00Z`).toISOString().slice(0,10)===v;
export type LedgerCursor={accounting_date:string;posted_at:string;journal_entry_id:Uuid;line_no:number};
export function decodeLedgerCursor(raw?:string):LedgerCursor|null { if(!raw)return null;try{const v=record(JSON.parse(Buffer.from(raw,"base64url").toString("utf8")));if(typeof v.accounting_date!=="string"||!validReportDate(v.accounting_date)||typeof v.posted_at!=="string"||!Number.isSafeInteger(v.line_no))throw new Error();return{accounting_date:v.accounting_date,posted_at:v.posted_at,journal_entry_id:parseUuid(v.journal_entry_id),line_no:Number(v.line_no)};}catch{throw CommandError.validation({cursor:"Invalid ledger page cursor."});} }
export const encodeLedgerCursor=(cursor:LedgerCursor)=>Buffer.from(JSON.stringify(cursor)).toString("base64url");
export async function readLedgerAccounts(client:RpcClient,actor:ActorContext){if(!actor.capabilities.includes("ledger.read"))throw CommandError.forbidden();const r=await client.rpc("read_general_ledger_accounts",{p_organization_id:actor.organizationId});if(r.error){if(r.error.code==="42501")throw CommandError.forbidden();throw new CommandError({code:"INTERNAL_ERROR"});}if(!Array.isArray(r.data))throw new Error("Invalid ledger accounts response.");return r.data.map(v=>{const row=record(v);if(typeof row.code!=="string"||typeof row.name!=="string")throw new Error("Invalid ledger account.");return{id:parseUuid(row.id),code:row.code,name:row.name};});}
export async function readGeneralLedger(client:RpcClient,actor:ActorContext,input:{accountId:string;from:string;to:string;costCenterId?:string;source?:string;cutoff?:string;cursor?:LedgerCursor}){
 if(!actor.capabilities.includes("ledger.read"))throw CommandError.forbidden();const accountId=parseUuid(input.accountId,"account_id"),costCenterId=input.costCenterId?parseUuid(input.costCenterId,"cost_center_id"):null;
 if(!validReportDate(input.from)||!validReportDate(input.to)||input.from>input.to)throw CommandError.validation({date_range:"Choose a valid date range."});
 const c=input.cursor;const r=await client.rpc("read_general_ledger",{p_organization_id:parseOrganizationId(actor.organizationId),p_account_id:accountId,p_from:input.from,p_to:input.to,p_cost_center_id:costCenterId,p_source_query:input.source?.slice(0,100)||null,p_cutoff_at:input.cutoff||null,p_after_date:c?.accounting_date??null,p_after_posted_at:c?.posted_at??null,p_after_journal_id:c?.journal_entry_id??null,p_after_line_no:c?.line_no??null,p_limit:100});
 if(r.error){if(r.error.code==="42501")throw CommandError.forbidden();if(r.error.code==="P0002")throw CommandError.notFound();if(r.error.code==="22023")throw CommandError.validation({date_range:"The ledger filters are invalid."});throw new CommandError({code:"INTERNAL_ERROR"});}const data=record(r.data);if(!Array.isArray(data.items)||typeof data.opening_balance!=="string"||typeof data.period_debit!=="string"||typeof data.period_credit!=="string"||typeof data.closing_balance!=="string"||typeof data.cutoff_at!=="string"||typeof data.has_more!=="boolean")throw new Error("Invalid ledger response.");return{accountId,openingBalance:data.opening_balance,periodDebit:data.period_debit,periodCredit:data.period_credit,closingBalance:data.closing_balance,cutoffAt:data.cutoff_at,hasMore:data.has_more,items:data.items.map(v=>record(v))};
}
export async function readTrialBalance(client:RpcClient,actor:ActorContext,input:{asOf:string;from?:string;cutoff?:string}){if(!actor.capabilities.includes("reports.read"))throw CommandError.forbidden();if(!validReportDate(input.asOf)||(input.from&&!validReportDate(input.from))||(input.from&&input.from>input.asOf))throw CommandError.validation({date_range:"Choose valid trial-balance dates."});const r=await client.rpc("read_trial_balance",{p_organization_id:actor.organizationId,p_as_of:input.asOf,p_from:input.from||null,p_cutoff_at:input.cutoff||null});if(r.error){if(r.error.code==="42501")throw CommandError.forbidden();if(r.error.code==="22023")throw CommandError.validation({date_range:"Choose valid trial-balance dates."});throw new CommandError({code:"INTERNAL_ERROR"});}const data=record(r.data);if(!Array.isArray(data.accounts)||typeof data.difference!=="string"||typeof data.balanced!=="boolean"||typeof data.cutoff_at!=="string")throw new Error("Invalid trial-balance response.");return{...data,accounts:data.accounts.map(v=>record(v))};}
