import type { SupabaseClient } from "@supabase/supabase-js";
import { parseMoneyString, parseUuid } from "@ams/contracts";
import { capability } from "@ams/permissions";
import { CommandError, retryableTransactionError } from "../commands/errors.ts";
import type { OrganizationCommandDefinition } from "../commands/types.ts";
import { record } from "../documents/contracts.ts";

type RpcClient=Pick<SupabaseClient,"rpc">;
type ActionInput={kind:"apply"|"refund";advanceOpenItemId:string;targetOpenItemId:string|null;cashAccountId:string|null;amount:string;accountingDate:string;method:string|null;reference:string|null};
type VersionInput={expectedVersion:number};
type UnapplyInput={effectiveDate:string;reason:string};
function validateAction(raw:unknown):ActionInput{
 const r=record(raw);const allowed=["action_kind","advance_open_item_id","target_open_item_id","cash_account_id","amount","accounting_date","method","reference"];
 if(Object.keys(r).some(k=>!allowed.includes(k)))throw CommandError.validation({body:"Unexpected action field."});
 if(r.action_kind!=="apply"&&r.action_kind!=="refund")throw CommandError.validation({action_kind:"Choose apply or refund."});
 if(typeof r.accounting_date!=="string"||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(r.accounting_date))throw CommandError.validation({accounting_date:"Choose a valid accounting date."});
 const d=new Date(`${r.accounting_date}T00:00:00Z`);if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==r.accounting_date)throw CommandError.validation({accounting_date:"Choose a valid accounting date."});
 const kind=r.action_kind;const amount=parseMoneyString(r.amount,"amount");if(BigInt(amount.replace(".",""))<=0n)throw CommandError.validation({amount:"Enter an amount greater than zero."});
 const target=r.target_open_item_id===null?null:parseUuid(r.target_open_item_id,"target_open_item_id");const cash=r.cash_account_id===null?null:parseUuid(r.cash_account_id,"cash_account_id");
 if(kind==="apply"&&(target===null||cash!==null||r.method!==null||r.reference!==null))throw CommandError.validation({body:"An application requires a compatible invoice or bill."});
 if(kind==="refund"&&(target!==null||cash===null||typeof r.method!=="string"||!(["cash","bank_transfer","mobile_wallet","card","other"] as string[]).includes(r.method)))throw CommandError.validation({body:"A refund requires a cash account and method."});
 const reference=r.reference===null?null:r.reference;if(reference!==null&&(typeof reference!=="string"||reference.length>160))throw CommandError.validation({reference:"Use at most 160 characters."});if(kind==="refund"&&(typeof reference!=="string"||!reference.trim()))throw CommandError.validation({reference:"Enter the cash or bank refund reference."});
 return{kind,advanceOpenItemId:parseUuid(r.advance_open_item_id,"advance_open_item_id"),targetOpenItemId:target,cashAccountId:cash,amount,accountingDate:r.accounting_date,method:kind==="refund"?r.method as string:null,reference};
}
function validateVersion(raw:unknown):VersionInput{const r=record(raw);if(Object.keys(r).some(k=>k!=="expected_version")||!Number.isSafeInteger(r.expected_version)||Number(r.expected_version)<1)throw CommandError.validation({expected_version:"Refresh the advance action before continuing."});return{expectedVersion:Number(r.expected_version)};}
function validateUnapply(raw:unknown):UnapplyInput{const r=record(raw);if(Object.keys(r).some(k=>!['effective_date','reason'].includes(k)))throw CommandError.validation({body:"Unexpected unapply field."});if(typeof r.effective_date!=="string"||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(r.effective_date))throw CommandError.validation({effective_date:"Choose a valid accounting date."});const d=new Date(`${r.effective_date}T00:00:00Z`);if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==r.effective_date)throw CommandError.validation({effective_date:"Choose a valid accounting date."});if(typeof r.reason!=="string"||r.reason.trim().length<10||r.reason.trim().length>1000)throw CommandError.validation({reason:"Enter a reason between 10 and 1,000 characters."});return{effectiveDate:r.effective_date,reason:r.reason.trim()};}
function dbError(error:{code?:string}){const retry=retryableTransactionError(error);if(retry)return retry;if(error.code==="42501")return CommandError.forbidden();if(error.code==="28000")return CommandError.unauthenticated();if(error.code==="P0002")return CommandError.notFound();if(error.code==="23505")return CommandError.conflict("IDEMPOTENCY_CONFLICT");if(error.code==="40001")return CommandError.conflict("STALE_VERSION");if(error.code==="55P03")return CommandError.conflict("PERIOD_LOCKED");if(error.code==="23P01")return CommandError.conflict("ALLOCATION_EXCEEDED");if(error.code==="22023"||error.code==="23514"||error.code==="23503"||error.code==="22P02")return CommandError.validation({advance:"The action conflicts with an advance, date, cash or control-account rule."});return new Error("Advance action failed.");}
function parseReceipt(data:unknown){if(!Array.isArray(data)||data.length!==1)throw new Error("Invalid advance action receipt.");const r=record(data[0],"receipt");if(typeof r.document_id!=="string"||!Number.isSafeInteger(r.document_version)||typeof r.state!=="string"||typeof r.total_amount!=="string"||typeof r.material_digest!=="string")throw new Error("Malformed advance action receipt.");parseMoneyString(r.total_amount);return{documentId:parseUuid(r.document_id),documentVersion:Number(r.document_version),state:r.state,totalAmount:r.total_amount,materialDigest:r.material_digest};}
export function saveAdvanceActionCommand(client:RpcClient):OrganizationCommandDefinition<ActionInput,ReturnType<typeof parseReceipt>>{return{operation:"advance-actions.save",capability:capability("dues.allocate"),idempotency:"required",validate:validateAction,async execute(ctx,input){if(!ctx.idempotencyKey)throw CommandError.validation({idempotency_key:"An idempotency key is required."});const r=await client.rpc("save_advance_action_draft",{p_organization_id:ctx.actor.organizationId,p_request_id:ctx.requestId,p_idempotency_key:ctx.idempotencyKey,p_request_hash:ctx.requestHash,p_action_kind:input.kind,p_advance_open_item_id:input.advanceOpenItemId,p_target_open_item_id:input.targetOpenItemId,p_cash_account_id:input.cashAccountId,p_amount:input.amount,p_accounting_date:input.accountingDate,p_method:input.method,p_reference:input.reference});if(r.error)throw dbError(r.error);return parseReceipt(r.data);}};}
export function submitAdvanceActionCommand(client:RpcClient,documentId:string):OrganizationCommandDefinition<VersionInput,Record<string,unknown>>{return{operation:`advance-actions.submit:${documentId}`,capability:capability("dues.allocate"),idempotency:"required",validate:validateVersion,async execute(ctx,input){if(!ctx.idempotencyKey)throw CommandError.validation({idempotency_key:"An idempotency key is required."});const r=await client.rpc("submit_advance_action",{p_organization_id:ctx.actor.organizationId,p_document_id:parseUuid(documentId),p_expected_version:input.expectedVersion,p_request_id:ctx.requestId,p_idempotency_key:ctx.idempotencyKey,p_request_hash:ctx.requestHash});if(r.error)throw dbError(r.error);if(!Array.isArray(r.data)||r.data.length!==1)throw new Error("Invalid advance submission receipt.");return record(r.data[0],"receipt");}};}
export function postAdvanceActionCommand(client:RpcClient,documentId:string):OrganizationCommandDefinition<VersionInput,Record<string,unknown>>{return{operation:`advance-actions.post:${documentId}`,capability:capability("dues.allocate"),idempotency:"required",validate:validateVersion,async execute(ctx,input){if(!ctx.idempotencyKey)throw CommandError.validation({idempotency_key:"An idempotency key is required."});const r=await client.rpc("post_advance_action",{p_organization_id:ctx.actor.organizationId,p_document_id:parseUuid(documentId),p_expected_version:input.expectedVersion,p_request_id:ctx.requestId,p_idempotency_key:ctx.idempotencyKey,p_request_hash:ctx.requestHash});if(r.error)throw dbError(r.error);if(!Array.isArray(r.data)||r.data.length!==1)throw new Error("Invalid advance posting receipt.");return record(r.data[0],"receipt");}};}
export function unapplyAdvanceApplicationCommand(client:RpcClient,documentId:string):OrganizationCommandDefinition<UnapplyInput,Record<string,unknown>>{return{operation:`advance-applications.unapply:${documentId}`,capability:capability("dues.allocate"),idempotency:"required",validate:validateUnapply,async execute(ctx,input){if(!ctx.idempotencyKey)throw CommandError.validation({idempotency_key:"An idempotency key is required."});const r=await client.rpc("unapply_advance_application",{p_organization_id:ctx.actor.organizationId,p_document_id:parseUuid(documentId),p_request_id:ctx.requestId,p_idempotency_key:ctx.idempotencyKey,p_request_hash:ctx.requestHash,p_effective_date:input.effectiveDate,p_reason:input.reason});if(r.error)throw dbError(r.error);if(!Array.isArray(r.data)||r.data.length!==1)throw new Error("Invalid advance unapply receipt.");return record(r.data[0],"receipt");}};}
