import { moneyUnits } from "@ams/accounting";
import { parseOrganizationId } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { bangladeshDate } from "../../../../lib/date.ts";
import { resolveActorContext } from "../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../server/commands/errors.ts";
import { roleRuntime } from "../../../../server/roles/runtime.ts";

type Control="ar"|"ap";
type Item={open_item_id:string;journal_line_id:string;source_document_id:string;document_number:string;party_id:string;party_name:string;control_kind:string;side:"debit"|"credit";reference:string;issue_date:string;due_date:string|null;bucket:string;residual:string};
type AgingData={as_of:string;timezone:string;control_kind:string;buckets:Record<string,string>;trade_debt:string;unapplied_trade_credits:string;net_trade_control_items:string;trade_control_ledger:string;trade_control_difference:string;trade_credit_items:Item[];advances:{control_kind:string;normal_balance:string;opposite_side_credits:string;ledger_balance:string;difference:string;items:Item[]};items:Item[];net_bridge_difference:string;provisional:boolean};
type Snapshot={company:{name:string;timezone:string};generated_at:string;ledger_cutoff_at:string;data:AgingData};
const dateOk=(value:string|null|undefined)=>!!value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(new Date(`${value}T00:00:00Z`).getTime())&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value;
const money=(value:string)=>{if(!/^-?(0|[1-9]\d{0,13})(\.\d{1,2})?$/.test(value))throw new Error("Invalid aging money value.");return value;};
const bucketLabels:Record<string,string>={not_due:"Not yet due",days_1_30:"1–30 days overdue",days_31_60:"31–60 days overdue",days_61_90:"61–90 days overdue",days_91_plus:"91+ days overdue",no_due_date:"No due date"};
export async function AgingReport({params,searchParams,control}:{params:Promise<{organizationId:string}>;searchParams:Promise<{as_of?:string}>;control:Control}){
 let organizationId:ReturnType<typeof parseOrganizationId>;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}
 const query=await searchParams,asOf=query.as_of??bangladeshDate();if(!dateOk(asOf))return <main className="content"><h1>{control==="ar"?"Receivable":"Payable"} aging</h1><p role="alert">Enter a valid as-of date.</p></main>;
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");let capabilities:readonly string[];
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);capabilities=actor.capabilities;const readCapability=control==="ar"?"sales.read":"purchases.read";if(!capabilities.includes("dues.read")&&!capabilities.includes(readCapability))throw CommandError.forbidden();}
 catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You do not have access to this aging report.</p></main>;throw error;}
 let snapshot:Snapshot;try{const result=await runtime.client.rpc("read_aging_snapshot",{p_organization_id:organizationId,p_control:control,p_as_of:asOf});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();if(result.error.code==="22023")throw CommandError.validation({as_of:"Choose a valid as-of date."});throw new Error("Aging report could not be generated.");}if(!result.data||typeof result.data!=="object"||Array.isArray(result.data))throw new Error("Invalid aging report snapshot.");snapshot=result.data as Snapshot;if(!snapshot.data||!Array.isArray(snapshot.data.items)||!snapshot.data.advances)throw new Error("Invalid aging report data.");}
 catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You do not have access to this aging report.</p></main>;if(error instanceof CommandError&&error.code==="VALIDATION_FAILED")return <main className="content"><h1>Aging report</h1><p role="alert">Choose a valid as-of date.</p></main>;throw error;}
 const data=snapshot.data,receivable=control==="ar",title=receivable?"Receivable aging":"Payable aging",tradeDebtLabel=receivable?"Trade receivables":"Trade payables",creditLabel=receivable?"Unapplied customer credits":"Unapplied vendor credits",kind=receivable?"receivable_aging":"payable_aging",exportQuery=new URLSearchParams({as_of:asOf,format:"json"});
 const groups=new Map<string,Item[]>();for(const item of data.items){const key=`${item.control_kind}:${item.party_id}`;groups.set(key,[...(groups.get(key)??[]),item]);}
 const sourceCanRead=capabilities.includes(receivable?"sales.read":"purchases.read")||capabilities.includes("accounting.read");
 const canDraft=capabilities.includes(receivable?"sales.write":"purchases.write");
 function itemLink(item:Item){return sourceCanRead?<Link href={`/o/${organizationId}/accounting/documents/${item.source_document_id}`}>{item.document_number||item.reference}</Link>:<span>{item.document_number||item.reference}</span>;}
 function table(items:Item[],actions:boolean){if(items.length===0)return <p>No open items at this date.</p>;return <div className="table-scroll"><table><thead><tr><th>Document</th><th>Reference</th><th>Issue date</th><th>Due date</th><th>Aging category</th><th>Party</th><th>Remaining (BDT)</th>{actions&&<th>Action</th>}</tr></thead><tbody>{items.map(item=><tr key={item.open_item_id}><td>{itemLink(item)}</td><td>{item.reference}</td><td>{item.issue_date}</td><td>{item.due_date??"—"}</td><td>{bucketLabels[item.bucket]??(item.bucket==="unapplied_credit"?"Unapplied credit":"Advance")}</td><td>{item.party_name}</td><td>{money(item.residual)}</td>{actions&&<td>{canDraft&&item.control_kind===(receivable?"ar":"ap")&&item.side===(receivable?"debit":"credit")&&<Link href={`/o/${organizationId}/accounting/documents/new?type=${receivable?"receipt":"vendor_payment"}&party_id=${item.party_id}`}>{receivable?"Draft receipt":"Draft payment"}</Link>}</td>}</tr>)}</tbody></table></div>;}
 return <main className="content"><p className="eyebrow">Reports · {snapshot.company.name}</p><h1>{title}</h1><p>Historical residuals use each allocation and unapply effective date as known at this snapshot. AR and AP remain separate for contacts with both roles. Advances use their own control accounts. Date: {asOf} · Timezone: {snapshot.company.timezone} · Ledger cutoff: {snapshot.ledger_cutoff_at} · Generated: {snapshot.generated_at}</p>
  <form method="get" className="panel toolbar"><label>As of<input required type="date" name="as_of" defaultValue={asOf}/></label><button type="submit">Run report</button>{capabilities.includes("reports.export")&&<a className="secondary" href={`/api/v1/organizations/${organizationId}/reports/${kind}?${exportQuery}`}>Download JSON snapshot</a>}</form>
  <section className="panel"><h2>{tradeDebtLabel} aging buckets</h2><dl className="toolbar">{Object.entries(bucketLabels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>BDT {money(data.buckets[key]??"0.00")}</dd></div>)}<div><dt>Total gross debt</dt><dd>BDT {money(data.trade_debt)}</dd></div><div><dt>{creditLabel}</dt><dd>BDT {money(data.unapplied_trade_credits)}</dd></div><div><dt>Net trade control items</dt><dd>BDT {money(data.net_trade_control_items)}</dd></div></dl></section>
  <section className="panel"><h2>Trade control bridge</h2><p>Open-item net: BDT {money(data.net_trade_control_items)} · GL control balance: BDT {money(data.trade_control_ledger)} · Difference: BDT {money(data.trade_control_difference)}</p><p role={moneyUnits(money(data.trade_control_difference))===0n?"status":"alert"}>{moneyUnits(money(data.trade_control_difference))===0n?"Open items reconcile to the control account.":"Control mismatch; investigate the source ledger without netting unrelated balances."}</p></section>
  <section className="panel"><h2>Open trade items by party</h2>{groups.size===0?<p>No open trade items at this date.</p>:<div>{[...groups.entries()].filter(([,items])=>items[0]?.control_kind===(receivable?"ar":"ap")&&items.some(item=>item.side===(receivable?"debit":"credit"))).map(([key,items])=><details key={key} className="panel"><summary>{items[0]?.party_name} · {items.filter(item=>item.side===(receivable?"debit":"credit")).length} item(s)</summary>{table(items.filter(item=>item.side===(receivable?"debit":"credit")),true)}</details>)}</div>}</section>
  <section className="panel"><h2>{creditLabel}</h2><p>Trade credits remain separate from debt and are not offset against other parties.</p>{table(data.trade_credit_items,false)}</section>
  <section className="panel"><h2>{receivable?"Customer":"Vendor"} advances · separate control</h2><p>Normal-side balance: BDT {money(data.advances.normal_balance)} · Opposite-side credits: BDT {money(data.advances.opposite_side_credits)} · GL control balance: BDT {money(data.advances.ledger_balance)} · Difference: BDT {money(data.advances.difference)}</p><p role={moneyUnits(money(data.advances.difference))===0n?"status":"alert"}>{moneyUnits(money(data.advances.difference))===0n?"Advance open items reconcile to their separate control account.":"Advance control mismatch; investigate the source ledger."}</p>{table(data.advances.items,false)}</section>
  </main>;
}
