import { moneyUnits,formatMoney } from "@ams/accounting";
import { parseOrganizationId } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { bangladeshDate } from "../../../../../lib/date.ts";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";

export const dynamic="force-dynamic";export const revalidate=0;
type Section="asset"|"liability"|"equity"|"untransferred_earnings";
type Account={account_id:string;account_code:string;account_name:string;account_type:string;report_group:string;section:Section;amount:string};
type Statement={as_of:string;assets:string;liabilities:string;equity_accounts:string;untransferred_earnings:string;equity:string;liabilities_and_equity:string;difference:string;accounts:Account[]};
type Snapshot={company:{name:string;timezone:string};generated_at:string;ledger_cutoff_at:string;data:{current:Statement;comparison:Statement|null}};
const dateOk=(value:string|null|undefined)=>!!value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(new Date(`${value}T00:00:00Z`).getTime())&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value;
const money=(value:string)=>{if(!/^-?(0|[1-9]\d{0,13})(\.\d{1,2})?$/.test(value))throw new Error("Invalid Balance Sheet money value.");return value;};
const sectionTitle:Record<Section,string>={asset:"Assets",liability:"Liabilities",equity:"Equity accounts",untransferred_earnings:"Untransferred earnings"};
export default async function BalanceSheetPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{as_of?:string;comparison_as_of?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}
 const q=await searchParams,today=bangladeshDate(),asOf=q.as_of??today,comparisonAsOf=q.comparison_as_of??null;
 if(!dateOk(asOf)||!dateOk(comparisonAsOf)||(comparisonAsOf!==null&&comparisonAsOf===asOf))return <main className="content"><h1>Balance Sheet</h1><p role="alert">Enter valid, different as-of dates.</p></main>;
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");let capabilities:readonly string[];
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);capabilities=actor.capabilities;if(!capabilities.includes("reports.read"))throw CommandError.forbidden();}
 catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need reports.read to view Balance Sheet.</p></main>;throw error;}
 let snapshot:Snapshot;try{const result=await runtime.client.rpc("read_balance_sheet_snapshot",{p_organization_id:organizationId,p_as_of:asOf,p_comparison_as_of:comparisonAsOf});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();if(result.error.code==="22023")throw CommandError.validation({as_of:"Choose valid report dates."});throw new Error("Balance Sheet could not be generated.");}if(!result.data||typeof result.data!=="object"||Array.isArray(result.data))throw new Error("Invalid Balance Sheet snapshot.");snapshot=result.data as Snapshot;if(!snapshot.data?.current||!Array.isArray(snapshot.data.current.accounts))throw new Error("Invalid Balance Sheet report data.");}
 catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need reports.read to view Balance Sheet.</p></main>;if(error instanceof CommandError&&error.code==="VALIDATION_FAILED")return <main className="content"><h1>Balance Sheet</h1><p role="alert">Choose valid report dates.</p></main>;throw error;}
 const current=snapshot.data.current,comparison=snapshot.data.comparison,byId=(rows:Account[])=>new Map(rows.map(row=>[row.account_id,row]));
 const currentRows=byId(current.accounts),comparisonRows=byId(comparison?.accounts??[]),allRows=new Map([...currentRows,...comparisonRows]);
 const exportQuery=new URLSearchParams({as_of:asOf,...(comparisonAsOf?{comparison_as_of:comparisonAsOf}:{}),format:"json"});
 const difference=money(current.difference),isBalanced=moneyUnits(difference)===0n;
 const renderSection=(section:Section)=><section className="panel" key={section}><h2>{sectionTitle[section]}</h2>{![...allRows.values()].some(row=>row.section===section)?<p>No posted balance at this date.</p>:<div className="table-scroll"><table><thead><tr><th>Group</th><th>Account</th><th>As of {asOf} (BDT)</th>{comparison&&<th>As of {comparison.as_of} (BDT)</th>}</tr></thead><tbody>{[...allRows.values()].filter(row=>row.section===section).sort((a,b)=>a.account_code.localeCompare(b.account_code)).map(row=>{const now=currentRows.get(row.account_id),then=comparisonRows.get(row.account_id);return <tr key={row.account_id}><td>{row.report_group.replaceAll("_"," ")}</td><td><Link href={`/o/${organizationId}/accounting/general-ledger?${new URLSearchParams({account:row.account_id,from:"0001-01-01",to:asOf})}`}>{row.account_code} · {row.account_name}</Link></td><td>{money(now?.amount??"0.00")}</td>{comparison&&<td>{money(then?.amount??"0.00")}</td>}</tr>;})}</tbody></table></div>}</section>;
 return <main className="content"><p className="eyebrow">Reports · {snapshot.company.name}</p><h1>Balance Sheet</h1><p>Management view as of the selected date; not a statutory filing. Cumulative posted ledger includes opening, close and reversal journals by their accounting dates. Nominal income and expense balances are shown as untransferred earnings only while they remain in the ledger. Timezone: {snapshot.company.timezone} · Ledger cutoff: {snapshot.ledger_cutoff_at} · Generated: {snapshot.generated_at}</p>
  <form method="get" className="panel toolbar"><label>As of<input required type="date" name="as_of" defaultValue={asOf}/></label><label>Compare as of<input type="date" name="comparison_as_of" defaultValue={comparisonAsOf??""}/></label><button type="submit">Run report</button>{capabilities.includes("reports.export")&&<a className="secondary" href={`/api/v1/organizations/${organizationId}/reports/balance_sheet?${exportQuery}`}>Download JSON snapshot</a>}</form>
  <section className="panel"><h2>Statement totals</h2><dl className="toolbar"><div><dt>Assets</dt><dd>BDT {money(current.assets)}</dd></div><div><dt>Liabilities</dt><dd>BDT {money(current.liabilities)}</dd></div><div><dt>Equity accounts</dt><dd>BDT {money(current.equity_accounts)}</dd></div><div><dt>Untransferred earnings</dt><dd>BDT {money(current.untransferred_earnings)}</dd></div><div><dt>Equity including untransferred earnings</dt><dd>BDT {money(current.equity)}</dd></div><div><dt>Liabilities + equity</dt><dd>BDT {money(current.liabilities_and_equity)}</dd></div><div><dt>Difference</dt><dd>{formatMoney(moneyUnits(difference))}</dd></div></dl><p role={isBalanced?"status":"alert"}>{isBalanced?"Balanced · no balancing plug was added":"Out of balance · investigate the posted ledger; no balancing plug was added"}</p>{comparison&&<p>Comparison totals: assets BDT {money(comparison.assets)} · liabilities BDT {money(comparison.liabilities)} · equity BDT {money(comparison.equity)} · difference BDT {money(comparison.difference)}.</p>}</section>
  {renderSection("asset")}{renderSection("liability")}{renderSection("equity")}{renderSection("untransferred_earnings")}
 </main>;
}
