"use client";
import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
type Year={id:string;label:string;starts_on:string;ends_on:string;status:"open"|"closed";active_close:{run_id:string;document_id:string;created_at:string;snapshot:Record<string,unknown>}|null;history:{run_id:string;close_document_id:string;reopen_document_id:string|null;created_at:string;snapshot:Record<string,unknown>}[]};
type Preview={fiscal_year_id:string;label:string;starts_on:string;ends_on:string;year_status:string;period_count:number;locked_period_count:number;period_check_failures:number;retained_earnings_account_name:string|null;retained_earnings_mapping_ok:boolean;prior_open_year_count:number;active_close_runs:number;nominal_account_count:number;profit:string;retained_earnings_debit:string;retained_earnings_credit:string;can_close:boolean;generated_at:string;lines:{account_id:string;code:string;name:string;account_type:string;signed_balance:string;close_debit:string;close_credit:string}[]};
export function YearCloseScreen({organizationId,years,canClose,canReopen,initialPreview}:{organizationId:string;years:Year[];canClose:boolean;canReopen:boolean;initialPreview:Record<string,unknown>|null}){
 const router=useRouter(),key=useRef(crypto.randomUUID());const[selected,setSelected]=useState(years[0]?.id??"");const[preview,setPreview]=useState<Preview|null>(initialPreview as Preview|null);const[reason,setReason]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
 async function loadPreview(id:string){setSelected(id);setPreview(null);setError("");setNotice("");if(!id)return;setBusy(true);try{const response=await fetch(`/api/v1/organizations/${organizationId}/fiscal-years/${id}/close-preview`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message??"Could not calculate year-close preview.");setPreview(body.data as Preview);}catch(e){setError(e instanceof Error?e.message:"Could not calculate year-close preview.");}finally{setBusy(false);}}
 async function execute(action:"close"|"reopen"){if(!selected)return;setBusy(true);setError("");setNotice("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/fiscal-years/${selected}/${action}`,{method:"POST",headers:{"Content-Type":"application/json","X-Request-Id":`year-${action}-${crypto.randomUUID()}`,"Idempotency-Key":key.current},body:JSON.stringify({reason})});const body=await response.json();if(!response.ok)throw new Error(body?.error?.fields?.period??body?.error?.fields?.reason??body?.error?.message??`Fiscal year could not be ${action}d.`);key.current=crypto.randomUUID();setReason("");router.refresh();await loadPreview(selected);setNotice(action==="close"?"Fiscal year closed. The close journal and snapshot are recorded.":"Fiscal year reopened. The prior close was reversed and retained in history.");}catch(e){setError(e instanceof Error?e.message:`Fiscal year could not be ${action}d.`);}finally{setBusy(false);}}
 const year=years.find(item=>item.id===selected);
 return <main className="content"><p className="eyebrow">Accounting controls</p><h1>Fiscal year close</h1><p>Preview nominal account balances, review the mapped retained-earnings transfer and period checks, then close or reopen with a reason. Close and reopen require a recent authentication. Reopening posts a linked reversal and preserves the previous close snapshot.</p>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {years.length===0?<section className="panel"><h2>No fiscal years</h2><p>Set up an accounting calendar before a year can be closed.</p></section>:<>
  <section className="panel"><label>Fiscal year<select value={selected} onChange={event=>void loadPreview(event.target.value)}>{years.map(item=><option key={item.id} value={item.id}>{item.label} · {item.starts_on} to {item.ends_on} · {item.status}</option>)}</select></label><button type="button" className="secondary" disabled={busy||!selected} onClick={()=>void loadPreview(selected)}>Refresh preview</button></section>
  {preview&&year&&<><section className="panel"><h2>{preview.label} · close preview</h2><p>{preview.starts_on} – {preview.ends_on} · Status: {preview.year_status} · Calculated {preview.generated_at}</p><dl className="toolbar"><div><dt>Periods locked</dt><dd>{preview.locked_period_count} / {preview.period_count}</dd></div><div><dt>Pending period close checks</dt><dd>{preview.period_check_failures}</dd></div><div><dt>Retained earnings mapping</dt><dd>{preview.retained_earnings_mapping_ok?preview.retained_earnings_account_name:"Unavailable"}</dd></div><div><dt>Earlier open years</dt><dd>{preview.prior_open_year_count}</dd></div><div><dt>Active close runs</dt><dd>{preview.active_close_runs}</dd></div><div><dt>Annual profit / (loss)</dt><dd>BDT {preview.profit}</dd></div><div><dt>Retained earnings debit / credit</dt><dd>BDT {preview.retained_earnings_debit} / {preview.retained_earnings_credit}</dd></div></dl><p role={preview.can_close?"status":"alert"}>{preview.can_close?"All year-close prerequisites pass.":"Resolve the listed prerequisites before closing this year."}</p>
   {preview.lines.length===0?<p>No nominal balances are available to close.</p>:<div className="table-scroll"><table><thead><tr><th>Account</th><th>Current nominal balance (BDT)</th><th>Closing debit (BDT)</th><th>Closing credit (BDT)</th></tr></thead><tbody>{preview.lines.map(line=><tr key={line.account_id}><td>{line.code} · {line.name} ({line.account_type})</td><td>{line.signed_balance}</td><td>{line.close_debit}</td><td>{line.close_credit}</td></tr>)}</tbody></table></div>}
   {preview.can_close&&canClose&&<Action action="close" reason={reason} setReason={setReason} busy={busy} onSubmit={()=>void execute("close")}/>}
   {year.active_close&&canReopen&&<Action action="reopen" reason={reason} setReason={setReason} busy={busy} onSubmit={()=>void execute("reopen")}/>}
  </section>
  <section className="panel"><h2>Close run history</h2>{year.history.length===0?<p>No year-close runs yet.</p>:<ol>{year.history.map(run=><li key={run.run_id}><strong>{run.reopen_document_id?"Reopened":"Active close"}</strong> · {run.created_at} · Close document {run.close_document_id}{run.reopen_document_id&&<> · Reversal {run.reopen_document_id}</>}<details><summary>Immutable close snapshot</summary><pre>{JSON.stringify(run.snapshot,null,2)}</pre></details></li>)}</ol>}</section></>}
 </>}</main>;
}
function Action({action,reason,setReason,busy,onSubmit}:{action:"close"|"reopen";reason:string;setReason:(value:string)=>void;busy:boolean;onSubmit:()=>void}){return <form className="panel" onSubmit={event=>{event.preventDefault();onSubmit();}}><label>{action==="close"?"Close reason":"Reopen reason"}<textarea required minLength={10} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label><button type="submit" disabled={busy||reason.trim().length<10}>{busy?"Saving…":action==="close"?"Post year close":"Reopen and reverse close"}</button><p>Recent authentication and an authorized close capability are required.</p></form>;}
