import { moneyUnits } from "@ams/accounting";
import { parseOrganizationId,parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { bangladeshDate } from "../../../../../lib/date.ts";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";
import { PrintStatement } from "./print-button.tsx";
import { ReportExportButton } from "../report-export-button.tsx";

export const dynamic="force-dynamic";export const revalidate=0;
type Scope="customer"|"vendor";type Party={id:string;display_name:string;legal_name?:string|null;is_active?:boolean};
type Event={event_id:string;date:string;event_type:string;control_kind:string;document_type:string;source_document_id:string|null;document_number:string|null;reference:string|null;related_document_id:string|null;related_document:string|null;detail:string|null;balance_effect:string;running_balance:string};
type Data={scope:Scope;party:{id:string;name:string;email:string|null};from:string;to:string;opening:{trade:string;advances:string};movements:{trade:string;advances:string};closing:{trade:string;advances:string};control_bridge:{trade_ledger:string;trade_difference:string;advance_ledger:string;advance_difference:string};events:Event[];cutoff_at:string;timezone:string};
type Snapshot={company:{name:string};generated_at:string;ledger_cutoff_at:string;data:Data};
const dateOk=(value:string|null|undefined)=>!!value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(new Date(`${value}T00:00:00Z`).getTime())&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value;
const money=(value:string)=>{if(!/^-?(0|[1-9]\d{0,13})(\.\d{1,2})?$/.test(value))throw new Error("Invalid statement money value.");return value;};
const eventTitle:Record<string,string>={invoice:"Invoice",bill:"Supplier bill",receipt:"Customer receipt",vendor_payment:"Supplier payment",customer_credit:"Customer credit",vendor_credit:"Vendor credit",customer_refund:"Customer refund",vendor_refund:"Vendor refund",customer_advance:"Customer advance",vendor_advance:"Vendor advance",paid_expense:"Paid expense",allocation:"Allocation",allocation_reversal:"Allocation unapply"};
export default async function PartyStatementsPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{scope?:string;search?:string;after?:string;party_id?:string;from?:string;to?:string}>}){
 let organizationId:ReturnType<typeof parseOrganizationId>;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}
 const q=await searchParams,today=bangladeshDate();
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");let capabilities:readonly string[];
 try{capabilities=(await resolveActorContext(organizationId,runtime.dependencies)).capabilities;}catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");throw error;}
 const customerAccess=capabilities.includes("sales.read")||capabilities.includes("dues.read"),vendorAccess=capabilities.includes("purchases.read")||capabilities.includes("dues.read");if(!customerAccess&&!vendorAccess)return <main className="content"><h1>Access denied</h1><p>You do not have scoped party statement access.</p></main>;
 const scope:Scope=q.scope==="vendor"&&vendorAccess?"vendor":customerAccess?"customer":"vendor",search=(q.search??"").trim(),from=q.from??`${today.slice(0,7)}-01`,to=q.to??today;
 if(!dateOk(from)||!dateOk(to)||from>to)return <main className="content"><h1>Party statement</h1><p role="alert">Enter a valid date range.</p></main>;
 let partyId:string|null=null;try{partyId=q.party_id?parseUuid(q.party_id):null;}catch{return <main className="content"><h1>Party statement</h1><p role="alert">Choose a valid party.</p></main>;}
 let parties:Party[]=[];if(search.length>0){try{const result=await runtime.client.rpc("list_statement_parties",{p_organization_id:organizationId,p_scope:scope,p_search:search,p_after:q.after?parseUuid(q.after):null,p_limit:100});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();throw new Error("Party search failed.");}if(result.data&&typeof result.data==="object"&&!Array.isArray(result.data)&&Array.isArray((result.data as Record<string,unknown>).items))parties=(result.data as {items:Party[]}).items.map(row=>({...row,id:parseUuid(row.id)}));}catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You do not have access to this party selector.</p></main>;throw error;}}
 let snapshot:Snapshot|null=null;if(partyId){try{const result=await runtime.client.rpc("read_party_statement_snapshot",{p_organization_id:organizationId,p_scope:scope,p_party_id:partyId,p_from:from,p_to:to});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();if(result.error.code==="P0002")throw CommandError.validation({party_id:"Choose a party in this company with the selected role."});if(result.error.code==="22023")throw CommandError.validation({period:"Choose a valid date range."});throw new Error("Party statement could not be generated.");}if(!result.data||typeof result.data!=="object"||Array.isArray(result.data))throw new Error("Invalid party statement snapshot.");snapshot=result.data as Snapshot;if(!snapshot.data||!Array.isArray(snapshot.data.events))throw new Error("Invalid party statement data.");}catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You do not have access to this party statement.</p></main>;if(error instanceof CommandError&&error.code==="VALIDATION_FAILED")return <main className="content"><h1>Party statement</h1><p role="alert">Choose a party in this company and check the date range.</p></main>;throw error;}}
 const title=scope==="customer"?"Customer statement":"Vendor statement",type=scope==="customer"?"customer-statement":"vendor-statement",exportQuery=new URLSearchParams({party_id:partyId??"",from,to,format:"json"}),statement=snapshot?.data,sourceAccess=capabilities.includes(scope==="customer"?"sales.read":"purchases.read")||capabilities.includes("accounting.read");
 const bridgeOk=!!statement&&moneyUnits(money(statement.control_bridge.trade_difference))===0n&&moneyUnits(money(statement.control_bridge.advance_difference))===0n;
 function documentLink(id:string|null,label:string|null){if(!id||!label)return <span>{label??"—"}</span>;return sourceAccess?<Link href={`/o/${organizationId}/accounting/documents/${id}`}>{label}</Link>:<span>{label}</span>;}
 const canExport=capabilities.includes("reports.export")&&capabilities.includes("exports.read")&&(scope==="customer"?(capabilities.includes("dues.read")||capabilities.includes("sales.read")):(capabilities.includes("dues.read")||capabilities.includes("purchases.read")));
 return <main className="content"><p className="eyebrow">Reports · Party statements</p><h1>Customer and vendor statements</h1><form method="get" className="panel toolbar">
  <label>Side<select name="scope" defaultValue={scope}><option value="customer" disabled={!customerAccess}>Customer / AR</option><option value="vendor" disabled={!vendorAccess}>Vendor / AP</option></select></label>
  <label>Search party<input type="search" name="search" maxLength={100} defaultValue={search} placeholder="Enter a name to find parties"/></label>
  {search&&<label>Party<select name="party_id" defaultValue={partyId??""}><option value="">Choose a party</option>{statement&&!parties.some(party=>party.id===statement.party.id)&&<option value={statement.party.id}>{statement.party.name}</option>}{parties.map(party=><option key={party.id} value={party.id}>{party.display_name}{party.is_active===false?" · inactive":""}</option>)}</select></label>}
  <label>From<input required type="date" name="from" defaultValue={from}/></label><label>To<input required type="date" name="to" defaultValue={to}/></label><button type="submit">Open statement</button>
 </form>
 {search.length===0&&!partyId&&<p role="status">Search by customer or vendor name to load the party selector. Results are limited to 100 per search; use a more specific name if needed.</p>}
 {partyId&&!statement&&<p role="status">No statement is displayed. Select a matching party name and date range.</p>}
 {statement&&<>
  <section className="panel"><div className="toolbar"><div><p className="eyebrow">{title} · {statement.from} to {statement.to}</p><h2>{statement.party.name}</h2><p>{statement.party.email??"No email on file"} · {statement.scope==="customer"?"Accounts receivable":"Accounts payable"}</p><p>Company: {snapshot?.company.name} · Timezone: {statement.timezone} · Ledger cutoff: {statement.cutoff_at} · Generated: {snapshot?.generated_at}</p></div><div><PrintStatement/>{capabilities.includes("reports.export")&&<p><a className="secondary" href={`/api/v1/organizations/${organizationId}/reports/${type}?${exportQuery}`}>Download JSON statement</a></p>}{canExport&&partyId&&<p><ReportExportButton organizationId={organizationId} exportType={scope==="customer"?"customer_statement":"vendor_statement"} filters={{party_id:partyId,from,to}}/></p>}</div></div></section>
  <section className="panel"><h2>{scope==="customer"?"Trade receivable":"Trade payable"} balance</h2><dl className="toolbar"><div><dt>Opening</dt><dd>BDT {money(statement.opening.trade)}</dd></div><div><dt>Source movements</dt><dd>BDT {money(statement.movements.trade)}</dd></div><div><dt>Closing</dt><dd>BDT {money(statement.closing.trade)}</dd></div></dl><p role={moneyUnits(money(statement.opening.trade))+moneyUnits(money(statement.movements.trade))===moneyUnits(money(statement.closing.trade))?"status":"alert"}>{moneyUnits(money(statement.opening.trade))+moneyUnits(money(statement.movements.trade))===moneyUnits(money(statement.closing.trade))?"Opening plus movements equals closing.":"Statement does not reconcile; inspect dated source activity."}</p><p>Control ledger balance: BDT {money(statement.control_bridge.trade_ledger)} · Difference: BDT {money(statement.control_bridge.trade_difference)} · {bridgeOk?"Control reconciled":"Control mismatch"}</p></section>
  <section className="panel"><h2>{scope==="customer"?"Customer":"Vendor"} advance · separate control</h2><dl className="toolbar"><div><dt>Opening</dt><dd>BDT {money(statement.opening.advances)}</dd></div><div><dt>Source movements</dt><dd>BDT {money(statement.movements.advances)}</dd></div><div><dt>Closing</dt><dd>BDT {money(statement.closing.advances)}</dd></div></dl><p>Control ledger balance: BDT {money(statement.control_bridge.advance_ledger)} · Difference: BDT {money(statement.control_bridge.advance_difference)}</p></section>
  <section className="panel"><h2>Movements and allocation history</h2>{statement.events.length===0?<p>No source or allocation events in this date range.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Account stream</th><th>Type</th><th>Document / settlement</th><th>Reference</th><th>Related document</th><th>Details</th><th>Balance effect (BDT)</th><th>Running balance (BDT)</th></tr></thead><tbody>{statement.events.map(event=><tr key={event.event_id}><td>{event.date}</td><td>{event.control_kind=== (scope==="customer"?"ar":"ap")?(scope==="customer"?"AR trade":"AP trade"):scope==="customer"?"Customer advance":"Vendor advance"}</td><td>{eventTitle[event.document_type]??event.document_type}</td><td>{documentLink(event.source_document_id,event.document_number)}</td><td>{event.reference??"—"}</td><td>{documentLink(event.related_document_id,event.related_document)}</td><td>{event.detail??"—"}</td><td>{money(event.balance_effect)}</td><td>{money(event.running_balance)}</td></tr>)}</tbody></table></div>}</section>
 </>}
 </main>;
}
