import { parseOrganizationId, parseMoneyString, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../server/commands/errors.ts";
import { record } from "../../../../server/documents/contracts.ts";
import { roleRuntime } from "../../../../server/roles/runtime.ts";

export const dynamic="force-dynamic";export const revalidate=0;
export default async function AdvancesPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{scope?:string;search?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}
 const q=await searchParams;const scope=q.scope==="supplier"?"supplier":"customer";const search=q.search?.trim().slice(0,100)??"";
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);const capability=scope==="customer"?"sales.read":"purchases.read";if(!actor.capabilities.includes(capability))throw CommandError.forbidden();
  const result=await runtime.client.rpc("read_advance_register",{p_organization_id:organizationId,p_scope:scope,p_search:search||null,p_limit:50});if(result.error||!Array.isArray(result.data))throw new Error("Advance register could not be loaded.");
  const rows=result.data.map((value:unknown)=>{const row=record(value,"advance");if(typeof row.document_type!=="string"||typeof row.party_name!=="string"||typeof row.accounting_date!=="string"||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(row.accounting_date)||(row.document_number!==null&&typeof row.document_number!=="string")||(row.cash_account_name!==null&&typeof row.cash_account_name!=="string")||(row.method!==null&&typeof row.method!=="string")||(row.reference!==null&&typeof row.reference!=="string")||typeof row.original_amount!=="string"||typeof row.applied_amount!=="string"||typeof row.refunded_amount!=="string"||typeof row.remaining_amount!=="string")throw new Error("Invalid advance register row.");return{itemId:parseUuid(row.open_item_id),documentId:parseUuid(row.document_id),type:row.document_type,number:row.document_number,party:row.party_name,date:row.accounting_date,original:parseMoneyString(row.original_amount),applied:parseMoneyString(row.applied_amount),refunded:parseMoneyString(row.refunded_amount),remaining:parseMoneyString(row.remaining_amount),cashAccount:row.cash_account_name,method:row.method,reference:row.reference};});
  const writeCapability=scope==="customer"?actor.capabilities.includes("sales.write"):actor.capabilities.includes("purchases.write");
  return <main className="content"><p className="eyebrow">Finance</p><h1>Customer and supplier advances</h1><p>Advance control balances stay separate from trade invoices, bills, revenue and expense.</p>
   <nav className="toolbar" aria-label="Advance ledger"><Link className={scope==="customer"?"primary":"secondary"} aria-current={scope==="customer"?"page":undefined} href={`/o/${organizationId}/advances?scope=customer`}>Customer advances</Link><Link className={scope==="supplier"?"primary":"secondary"} aria-current={scope==="supplier"?"page":undefined} href={`/o/${organizationId}/advances?scope=supplier`}>Supplier advances</Link></nav>
   <div className="toolbar">{writeCapability&&<Link className="primary" href={`/o/${organizationId}/accounting/documents/new?type=${scope==="customer"?"customer_advance":"vendor_advance"}`}>Record {scope} advance</Link>}</div>
   <form className="panel toolbar" action={`/o/${organizationId}/advances`} method="get"><input type="hidden" name="scope" value={scope}/><label>Search advances<input type="search" name="search" maxLength={100} defaultValue={search}/></label><button type="submit">Search</button></form>
   <section className="panel"><h2>{scope==="customer"?"Customer":"Supplier"} advance balances</h2>{rows.length===0?<p>No {scope} advances found.</p>:<div className="table-scroll"><table><thead><tr><th>Source</th><th>Party</th><th>Date</th><th>Cash account</th><th>Original (BDT)</th><th>Applied (BDT)</th><th>Refunded (BDT)</th><th>Remaining (BDT)</th><th>State</th></tr></thead><tbody>{rows.map(row=><tr key={row.itemId}><td><Link href={`/o/${organizationId}/advances/${row.itemId}`}>{row.number??row.documentId}</Link></td><td>{row.party}</td><td>{row.date}</td><td>{row.cashAccount??"—"}{row.method?` · ${row.method}`:""}{row.reference?` · ${row.reference}`:""}</td><td>{row.original}</td><td>{row.applied}</td><td>{row.refunded}</td><td>{row.remaining}</td><td>{row.type.replaceAll("_"," ")}</td></tr>)}</tbody></table></div>}</section>
  </main>;
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You do not have permission to view this advance ledger.</p></main>;throw error;}
}
