"use client";
import { useMemo,useRef,useState,useSyncExternalStore } from "react";
import Link from "next/link";
import { parsePendingOpeningSave, recoverOpeningFields, type PendingOpeningSave } from "./opening-recovery.ts";
import { useRouter } from "next/navigation";

type Account={id:string;code:string;name:string;account_type:"asset"|"liability"|"equity"|"income"|"expense";normal_side:"debit"|"credit";control_kind:"ar"|"ap"|"customer_advance"|"vendor_advance"|null};
type Party={id:string;display_name:string;is_customer:boolean;is_vendor:boolean};
type Options={books_start_date:string;cutover_date:string;fiscal_year_start:string;accounts:Account[];parties:Party[];opening_suspense_account_id:string|null};
type Detail={id:string;account_id:string;party_id:string;reference:string;due_date:string;debit:string;credit:string};
const zero={debit:"0.00",credit:"0.00"};
function cents(value:string){if(!/^(0|[1-9]\d{0,13})(\.\d{1,2})?$/.test(value))return null;const [whole,fraction=""]=value.split(".");return BigInt(whole)*100n+BigInt((fraction+"00").slice(0,2));}
function amount(value:bigint){const sign=value<0n?"-":"";const abs=value<0n?-value:value;return `${sign}${abs/100n}.${String(abs%100n).padStart(2,"0")}`;}
function sum(rows:Detail[],field:"debit"|"credit",accountId:string){return rows.filter(r=>r.account_id===accountId).reduce((total,row)=>total+(cents(row[field])??0n),0n);}
type InitialOpening = { id: string; version: number; balances: Record<string,{debit:string;credit:string}>; details: Detail[]; evidence: string };
const recoveryEvent = "ams-opening-recovery";
function subscribeRecovery(callback: () => void) { window.addEventListener(recoveryEvent, callback); window.addEventListener("storage", callback); return () => { window.removeEventListener(recoveryEvent, callback); window.removeEventListener("storage", callback); }; }
export function OpeningBalanceWizard({organizationId,nonce,options,initial}:{organizationId:string;nonce:string;options:Options;initial?:InitialOpening}){
 const router=useRouter();const [balances,setBalances]=useState<Record<string,{debit:string;credit:string}>>(initial?.balances??{});const [details,setDetails]=useState<Detail[]>(initial?.details??[]);const [evidence,setEvidence]=useState(initial?.evidence??"");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const inFlight=useRef(false);
 const storageKey=`ams:opening-save:${organizationId}:${initial?.id??"new"}`;
 const fallback=useRef<string|null>(null);
 const saved=useSyncExternalStore(subscribeRecovery,()=>{try{return sessionStorage.getItem(storageKey)??fallback.current;}catch{return fallback.current;}},()=>null);
 const pending=parsePendingOpeningSave(saved);
 function persist(value:PendingOpeningSave|null){const raw=value?JSON.stringify(value):null;fallback.current=raw;try{if(raw)sessionStorage.setItem(storageKey,raw);else sessionStorage.removeItem(storageKey);}catch{/* Retry remains available in this tab if storage is disabled. */}window.dispatchEvent(new Event(recoveryEvent));}
 async function send(request:PendingOpeningSave){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError("");persist(request);let confirmed=false;try{
  const response=await fetch(`/api/v1/organizations/${organizationId}/opening-cutover/drafts`,{method:"POST",headers:{"Content-Type":"application/json","X-Request-Id":`opening-${crypto.randomUUID()}`,"Idempotency-Key":request.key},body:request.body});
  const result=await response.json();if(!response.ok){if(response.status>=400&&response.status<500){const recovered=recoverOpeningFields(request,options.accounts);setBalances(recovered.balances);setDetails(recovered.details);setEvidence(recovered.evidence);persist(null);}throw new Error(result?.error?.fields?.setup??result?.error?.fields?.draft??result?.error?.message??"Could not save opening draft.");}
  if(typeof result?.data?.documentId!=="string")throw new Error("The save response was incomplete. Retry the saved request.");
  confirmed=true;persist(null);router.push(`/o/${organizationId}/accounting/documents/${result.data.documentId}`);router.refresh();
 }catch(e){setError(e instanceof Error?e.message:"The save could not be confirmed. Retry the saved request.");}finally{if(!confirmed){inFlight.current=false;setBusy(false);}}}

 const controls=options.accounts.filter(a=>a.control_kind);const ordinary=options.accounts.filter(a=>!a.control_kind);
 const rows=useMemo(()=>options.accounts.map(account=>{if(account.control_kind)return{account_id:account.id,debit:amount(sum(details,"debit",account.id)),credit:amount(sum(details,"credit",account.id))};return{account_id:account.id,debit:amount(cents(balances[account.id]?.debit??"0.00")??0n),credit:amount(cents(balances[account.id]?.credit??"0.00")??0n)};}).filter(r=>r.debit!=="0.00"||r.credit!=="0.00"),[options.accounts,details,balances]);
 const totals=rows.reduce((t,row)=>({debit:t.debit+(cents(row.debit)??0n),credit:t.credit+(cents(row.credit)??0n)}),{debit:0n,credit:0n});
 const suspenseId=options.opening_suspense_account_id;const suspense=rows.find(row=>row.account_id===suspenseId);const nominal=rows.filter(row=>{const account=options.accounts.find(a=>a.id===row.account_id);return account?.account_type==="income"||account?.account_type==="expense";});
 function newDetail(accountId:string){setDetails(current=>[...current,{id:crypto.randomUUID(),account_id:accountId,party_id:"",reference:"",due_date:options.cutover_date,debit:"0.00",credit:"0.00"}]);}
 function updateDetail(id:string,patch:Partial<Detail>){setDetails(current=>current.map(row=>row.id===id?{...row,...patch}:row));}
 async function save(){if(inFlight.current)return;if(pending){await send(pending);return;}setError("");if(totals.debit!==totals.credit){setError("Trial balance debit and credit totals must agree before the cutover can be submitted.");return;}if(suspense){setError("Opening suspense must be zero before approval or posting.");return;}if(!suspenseId){setError("Company opening suspense account mapping is unavailable.");return;}if(!evidence.trim()){setError("Enter the source document or file reference for this trial balance.");return;}
  for(const row of details){if(!row.party_id||!row.reference.trim()||!row.due_date||((cents(row.debit)??0n)===0n)===( (cents(row.credit)??0n)===0n)){setError("Every AR, AP and advance detail needs a party, reference, due date, and exactly one positive amount.");return;}}
  const accountById=new Map(options.accounts.map(a=>[a.id,a]));const journalRows:Record<string,unknown>[]=[];
  for(const account of ordinary){const balance=balances[account.id]??zero;const debit=cents(balance.debit),credit=cents(balance.credit);if(debit===null||credit===null){setError(`Enter valid exact BDT amounts for ${account.code}.`);return;}if(debit>0n&&credit>0n){setError(`Use one side only for ${account.code}.`);return;}if(debit>0n||credit>0n)journalRows.push({account_id:account.id,party_id:null,cost_center_id:null,debit:amount(debit),credit:amount(credit),description:`Opening balance · ${account.name}`,cash_flow_class:null,open_item_reference:null,open_item_due_date:null});}
  for(const row of details){const debit=cents(row.debit),credit=cents(row.credit);if(debit===null||credit===null){setError("Enter valid exact BDT amounts for each control detail.");return;}if(debit>0n||credit>0n)journalRows.push({account_id:row.account_id,party_id:row.party_id,cost_center_id:null,debit:amount(debit),credit:amount(credit),description:`Opening ${accountById.get(row.account_id)?.control_kind} · ${row.reference.trim()}`,cash_flow_class:null,open_item_reference:row.reference.trim(),open_item_due_date:row.due_date});}
  if(journalRows.length<2){setError("Enter at least two nonzero trial balance rows.");return;}
  await send({key:crypto.randomUUID(),body:JSON.stringify({document_id:initial?.id??null,expected_version:initial?.version??null,draft:{document_type:"opening_balance",party_id:null,issue_date:options.cutover_date,accounting_date:options.cutover_date,due_date:null,external_reference:evidence.trim(),description:`Opening balances as at ${options.cutover_date}`,currency:"BDT",rounding_adjustment:"0.00",rounding_reason:null,rounding_account_id:null,trade:null,movement:null,transfer:null,lines:[],journal_rows:journalRows,allocation_plan:[]},evidence_reference:evidence.trim(),prior_trial_balance:rows,ytd_summary:nominal})});}

 return <main className="content" data-company-context={nonce}><p className="eyebrow">Accounting · Opening balances</p><h1>{initial?"Edit opening balance draft":"Opening balance and cutover"}</h1><p><Link href={`/o/${organizationId}/settings/setup`}>← Company setup</Link></p>{pending&&<section className="panel" role="status"><h2>Unconfirmed save</h2><p>A saved request is waiting for confirmation. Retry the same request to recover its result before making further changes.</p><button type="button" disabled={busy} onClick={()=>void send(pending)}>{busy?"Confirming save…":"Retry saved request"}</button></section>}<fieldset disabled={busy||!!pending} style={{border:0,padding:0,minWidth:0}}><p>Load the prior trial balance as summarized opening entries. No historic sales invoices are created. Books start on {options.books_start_date}; opening entries are dated {options.cutover_date}.</p><section className="panel"><h2>Cutover source</h2><p>Cutover date: <strong>{options.cutover_date}</strong> · Financial year starts: {options.fiscal_year_start}</p><label>Source trial balance reference<input value={evidence} maxLength={500} onChange={e=>setEvidence(e.target.value)} placeholder="Filename, report ID, or source reference" required/></label></section>
  <section className="panel"><h2>Prior trial balance · BDT</h2><p>Enter the source balances by account. Control accounts are calculated from the detailed items below.</p><div className="table-scroll"><table><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{ordinary.map(account=><tr key={account.id}><td>{account.code}</td><td>{account.name}{account.id===suspenseId&&<strong> · Opening suspense</strong>}</td><td>{account.account_type}</td><td><input aria-label={`${account.code} debit`} inputMode="decimal" value={balances[account.id]?.debit??"0.00"} onChange={e=>setBalances(current=>({...current,[account.id]:{...(current[account.id]??zero),debit:e.target.value,credit:e.target.value==="0.00"?(current[account.id]?.credit??"0.00"):"0.00"}}))}/></td><td><input aria-label={`${account.code} credit`} inputMode="decimal" value={balances[account.id]?.credit??"0.00"} onChange={e=>setBalances(current=>({...current,[account.id]:{...(current[account.id]??zero),credit:e.target.value,debit:e.target.value==="0.00"?(current[account.id]?.debit??"0.00"):"0.00"}}))}/></td></tr>)}</tbody><tfoot><tr><th colSpan={3}>Totals</th><th>{amount(totals.debit)}</th><th>{amount(totals.credit)}</th></tr></tfoot></table></div><p role={totals.debit===totals.credit&&!suspense?"status":"alert"}>{totals.debit===totals.credit?"Trial balance is balanced.":`Imbalance: BDT ${amount(totals.debit-totals.credit)} debit.`}{suspense?" Opening suspense must be cleared before submission.":""}</p></section>
  {controls.map(account=><section className="panel" key={account.id}><h2>{account.code} · {account.name} ({account.control_kind})</h2><p>Detail total: debit {amount(sum(details,"debit",account.id))} · credit {amount(sum(details,"credit",account.id))}. Detail rows become dated open items when the approved opening journal posts.</p>{details.filter(row=>row.account_id===account.id).map(row=><div className="toolbar" key={row.id}><label>Party<select required value={row.party_id} onChange={e=>updateDetail(row.id,{party_id:e.target.value})}><option value="">Choose party</option>{options.parties.filter(p=>account.control_kind==="ar"||account.control_kind==="customer_advance"?p.is_customer:p.is_vendor).map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label>Original reference<input required maxLength={160} value={row.reference} onChange={e=>updateDetail(row.id,{reference:e.target.value})}/></label><label>Due date<input required type="date" min={options.cutover_date} value={row.due_date} onChange={e=>updateDetail(row.id,{due_date:e.target.value})}/></label><label>Debit<input inputMode="decimal" value={row.debit} onChange={e=>updateDetail(row.id,{debit:e.target.value,credit:e.target.value==="0.00"?row.credit:"0.00"})}/></label><label>Credit<input inputMode="decimal" value={row.credit} onChange={e=>updateDetail(row.id,{credit:e.target.value,debit:e.target.value==="0.00"?row.debit:"0.00"})}/></label><button type="button" className="secondary" onClick={()=>setDetails(current=>current.filter(item=>item.id!==row.id))}>Remove</button></div>)}<button type="button" className="secondary" onClick={()=>newDetail(account.id)}>Add open item</button></section>)}
  <section className="panel"><h2>Pre-cutover year-to-date summary</h2><p>These exact nominal balances are stored as imported summary evidence. They contain no fabricated invoice or transaction detail. Annual profit and loss will consume each account summary once.</p><p>{nominal.length?nominal.map(row=>`${accountByName(options.accounts,row.account_id)}: debit ${row.debit}, credit ${row.credit}`).join(" · "):"No nominal account balances entered."}</p></section></fieldset>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy||!!pending||totals.debit!==totals.credit||!!suspense} onClick={()=>void save()}>{busy?"Saving cutover draft…":"Save opening draft"}</button><p>After saving, review the document and request approval. For a new company, return to Company setup to activate the books and post the approved opening in one transaction.</p></main>;
}
function accountByName(accounts:Account[],id:string){const account=accounts.find(a=>a.id===id);return account?`${account.code} ${account.name}`:id;}
