import {parseMoneyString,parseOrganizationId,parseUuid,type OrganizationId,type Uuid} from "@ams/contracts";
import type {SupabaseClient} from "@supabase/supabase-js";import {CommandError} from "../commands/errors.ts";import type {ActorContext} from "../auth/types.ts";import {record} from "./contracts.ts";
type RpcClient=Pick<SupabaseClient,"rpc">;export type CreditTab="all"|"drafts"|"awaiting_approval"|"posted";
export interface CreditableInvoice{ id:Uuid;documentNumber:string|null;customerId:Uuid;customerName:string;issueDate:string;accountingDate:string;totalAmount:string }
export interface CustomerCreditLineOption{originalLineId:Uuid;description:string;originalQuantity:string;remainingQuantity:string;unitPrice:string;discountAmount:string;accountId:Uuid;costCenterId:Uuid|null;taxCodeId:Uuid|null;taxMode:"inclusive"|"exclusive";taxLabel:string|null;taxRate:string;taxRecoverability:string;originalGross:string;remainingBasis:string}
export interface CustomerCreditOptions{invoiceId:Uuid;invoiceNumber:string|null;customerId:Uuid;customerName:string;issueDate:string;accountingDate:string;totalAmount:string;lines:CustomerCreditLineOption[]}
export async function readCreditableInvoices(client:RpcClient,actor:ActorContext,input:{accountingDate:string;search:string|null;after:string|null;limit:number}){
 if(!actor.capabilities.includes("sales.write"))throw CommandError.forbidden();if(!validDate(input.accountingDate)||!Number.isSafeInteger(input.limit)||input.limit<1||input.limit>100||input.search!==null&&input.search.length>100)throw CommandError.validation({query:"Use a valid date, search under 100 characters and page size 1-100."});
 const r=await client.rpc("read_customer_creditable_invoices",{p_organization_id:actor.organizationId,p_accounting_date:input.accountingDate,p_search:input.search,p_after:input.after?parseUuid(input.after,"after"):null,p_limit:input.limit+1});
 if(r.error){if(r.error.code==="42501")throw CommandError.forbidden();if(r.error.code==="22023")throw CommandError.validation({query:"Credit invoice filters are invalid."});throw new Error("Eligible customer invoices could not be loaded.");}
 if(!Array.isArray(r.data)||r.data.length>input.limit+1)throw new Error("Invalid customer credit invoice response.");const rows=r.data.map((v:unknown)=>{const row=record(v,"invoice");
   if((row.document_number!==null&&typeof row.document_number!=="string")||typeof row.customer_name!=="string"||!validDate(row.issue_date)||!validDate(row.accounting_date)||typeof row.total_amount!=="string")throw new Error("Invalid credit invoice row.");
   return{id:parseUuid(row.id),documentNumber:row.document_number,customerId:parseUuid(row.customer_id),customerName:row.customer_name,issueDate:row.issue_date,accountingDate:row.accounting_date,totalAmount:parseMoneyString(row.total_amount)} as CreditableInvoice;});
 const more=rows.length>input.limit;const items=more?rows.slice(0,input.limit):rows;return{items,nextCursor:more?items.at(-1)?.id??null:null};
}
export async function readCustomerCreditOptions(client:RpcClient,actor:ActorContext,invoiceId:string,accountingDate:string):Promise<CustomerCreditOptions>{
 if(!actor.capabilities.includes("sales.write"))throw CommandError.forbidden();const id=parseUuid(invoiceId,"original_document_id");if(!validDate(accountingDate))throw CommandError.validation({accounting_date:"Choose a valid accounting date."});
 const r=await client.rpc("read_customer_credit_options",{p_organization_id:actor.organizationId,p_invoice_id:id,p_accounting_date:accountingDate});
 if(r.error){if(r.error.code==="42501")throw CommandError.forbidden();if(r.error.code==="P0002")throw CommandError.notFound();if(r.error.code==="22023")throw CommandError.validation({original_document_id:"Choose a posted invoice on or before the credit date."});throw new Error("Eligible invoice lines could not be loaded.");}
 if(!Array.isArray(r.data)||r.data.length>500)throw new Error("Invalid eligible credit lines response.");let header:Omit<CustomerCreditOptions,"lines">|null=null;
 const lines=r.data.map((v:unknown):CustomerCreditLineOption=>{const row=record(v,"credit_line");if(row.invoice_id!==id||(row.invoice_number!==null&&typeof row.invoice_number!=="string")||typeof row.customer_name!=="string"||!validDate(row.issue_date)||!validDate(row.accounting_date)||typeof row.total_amount!=="string"||
   typeof row.line_description!=="string"||typeof row.original_quantity!=="string"||typeof row.remaining_quantity!=="string"||typeof row.unit_price!=="string"||typeof row.discount_amount!=="string"||
   (row.cost_center_id!==null&&typeof row.cost_center_id!=="string")||(row.tax_code_id!==null&&typeof row.tax_code_id!=="string")||!(["inclusive","exclusive"] as unknown[]).includes(row.tax_mode)||
   (row.tax_label!==null&&typeof row.tax_label!=="string")||typeof row.tax_rate!=="string"||typeof row.tax_recoverability!=="string"||typeof row.original_gross!=="string"||typeof row.remaining_basis!=="string")throw new Error("Invalid eligible credit line.");
   header={invoiceId:id,invoiceNumber:row.invoice_number,customerId:parseUuid(row.customer_id),customerName:row.customer_name,issueDate:row.issue_date,accountingDate:row.accounting_date,totalAmount:parseMoneyString(row.total_amount)};
   return{originalLineId:parseUuid(row.original_line_id),description:row.line_description,originalQuantity:row.original_quantity,remainingQuantity:row.remaining_quantity,unitPrice:row.unit_price,discountAmount:parseMoneyString(row.discount_amount),accountId:parseUuid(row.account_id),costCenterId:row.cost_center_id?parseUuid(row.cost_center_id):null,taxCodeId:row.tax_code_id?parseUuid(row.tax_code_id):null,taxMode:row.tax_mode as "inclusive"|"exclusive",taxLabel:row.tax_label,taxRate:row.tax_rate,taxRecoverability:row.tax_recoverability,originalGross:parseMoneyString(row.original_gross),remainingBasis:parseMoneyString(row.remaining_basis)};
 });
 if(!header)throw CommandError.notFound();return{...header,lines};
}
export async function readCustomerCreditRegister(client:RpcClient,actor:ActorContext,input:{status:CreditTab;search:string|null;after:string|null;limit:number}){
 if(!actor.capabilities.includes("sales.read"))throw CommandError.forbidden();if(!Number.isSafeInteger(input.limit)||input.limit<1||input.limit>100||input.search!==null&&input.search.length>100)throw CommandError.validation({query:"Use a search under 100 characters and page size 1-100."});
 const r=await client.rpc("read_customer_credit_register",{p_organization_id:actor.organizationId,p_status:input.status,p_search:input.search,p_after:input.after?parseUuid(input.after,"after"):null,p_limit:input.limit+1});
 if(r.error){if(r.error.code==="42501")throw CommandError.forbidden();if(r.error.code==="22023")throw CommandError.validation({query:"Credit filters are invalid."});throw new Error("Customer credit register could not be loaded.");}
 if(!Array.isArray(r.data)||r.data.length>input.limit+1)throw new Error("Invalid customer credit register response.");const rows=r.data.map((v:unknown)=>{const row=record(v,"credit");if(row.organization_id!==actor.organizationId||typeof row.state!=="string"||(row.document_number!==null&&typeof row.document_number!=="string")||typeof row.customer_name!=="string"||(row.original_document_number!==null&&typeof row.original_document_number!=="string")||!validDate(row.accounting_date)||typeof row.total_amount!=="string"||(row.residual_amount!==null&&typeof row.residual_amount!=="string"))throw new Error("Invalid customer credit row.");return{id:parseUuid(row.id),organizationId:parseOrganizationId(row.organization_id),state:row.state,documentNumber:row.document_number,customerName:row.customer_name,originalDocumentNumber:row.original_document_number,accountingDate:row.accounting_date,totalAmount:parseMoneyString(row.total_amount),residualAmount:row.residual_amount===null?null:parseMoneyString(row.residual_amount)};});
 const more=rows.length>input.limit;const items=more?rows.slice(0,input.limit):rows;return{items,nextCursor:more?items.at(-1)?.id??null:null};
}
export async function readCustomerCreditLifecycle(client:RpcClient,actor:ActorContext,documentId:string){if(!actor.capabilities.includes("sales.read"))throw CommandError.forbidden();const r=await client.rpc("read_customer_credit_lifecycle",{p_organization_id:actor.organizationId,p_document_id:parseUuid(documentId,"document_id")});if(r.error){if(r.error.code==="42501")throw CommandError.forbidden();if(r.error.code==="P0002")throw CommandError.notFound();throw new Error("Customer credit lifecycle could not be loaded.");}const row=record(r.data,"credit_lifecycle");if(row.organization_id!==actor.organizationId||typeof row.state!=="string"||(row.residual_amount!==null&&typeof row.residual_amount!=="string")||typeof row.applied_amount!=="string"||!Array.isArray(row.allocations)||!Array.isArray(row.approvals)||!Array.isArray(row.attachments)||!Array.isArray(row.activity)||!Array.isArray(row.corrections))throw new Error("Invalid customer credit lifecycle response.");if(row.residual_amount!==null)parseMoneyString(row.residual_amount);parseMoneyString(row.applied_amount);return row;}
function validDate(value:unknown):value is string{return typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value);}
