import { parseOrganizationId } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { readTransferRegister } from "../../../../../server/documents/transfers.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";
export const dynamic="force-dynamic";export const revalidate=0;
export default async function TransfersPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{search?:string}>}){let organizationId;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}const query=await searchParams;const search=typeof query.search==="string"?query.search.trim().slice(0,100):"";const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");let rows:Awaited<ReturnType<typeof readTransferRegister>>=[];let canWrite=false;let forbidden=false;
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);rows=await readTransferRegister(runtime.client,actor,search||null);canWrite=actor.capabilities.includes("banking.write");}catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="NOT_FOUND")redirect("/companies?error=not_found");if(error instanceof CommandError&&error.code==="FORBIDDEN")forbidden=true;else throw error;}
 if(forbidden)return <main className="content"><h1>Access denied</h1><p>You need banking.read to view transfers.</p></main>;
 return <main className="content"><p className="eyebrow">Banking</p><h1>Transfers</h1><p>Move funds between company accounts with explicit, separately coded fees. Internal principal is not income.</p>{canWrite&&<p><Link className="primary" href={`/o/${organizationId}/banking/transfers/new`}>New transfer</Link></p>}<form className="panel toolbar" method="get"><label>Search transfers<input type="search" name="search" maxLength={100} defaultValue={search} placeholder="Number, account or reference"/></label><button type="submit">Search</button>{search&&<Link href={`/o/${organizationId}/banking/transfers`}>Clear</Link>}</form><section className="panel"><h2>Transfer history</h2>{rows.length===0?<p>No transfers match these filters.</p>:<div className="table-scroll"><table><thead><tr><th>Number</th><th>Date</th><th>From</th><th>To</th><th>Principal (BDT)</th><th>Fee (BDT)</th><th>State</th><th>Reference</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><Link href={`/o/${organizationId}/banking/transfers/${row.id}`}>{row.documentNumber??"Draft"}</Link></td><td>{row.accountingDate}</td><td>{row.fromAccount}</td><td>{row.toAccount}</td><td>{row.amount}</td><td>{row.feeAmount}</td><td>{row.state.replaceAll("_"," ")}</td><td>{row.externalReference??"—"}</td></tr>)}</tbody></table></div>}</section></main>;
}
