import { parseMoneyString,parseOrganizationId,parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../server/commands/errors.ts";
import { record } from "../../../../server/documents/contracts.ts";
import { roleRuntime } from "../../../../server/roles/runtime.ts";

export const dynamic="force-dynamic";export const revalidate=0;
export default async function TransferRegisterPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{search?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}
 const search=(await searchParams).search?.trim().slice(0,100)??"";const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);if(!actor.capabilities.includes("banking.read"))throw CommandError.forbidden();
  const result=await runtime.client.rpc("read_transfer_register",{p_organization_id:organizationId,p_search:search||null,p_limit:50});if(result.error||!Array.isArray(result.data))throw new Error("Transfer register could not be loaded.");
  const rows=result.data.map((value:unknown)=>{const row=record(value,"transfer");if(typeof row.state!=="string"||typeof row.accounting_date!=="string"||typeof row.from_account!=="string"||typeof row.to_account!=="string"||typeof row.principal_amount!=="string"||typeof row.fee_amount!=="string"||typeof row.total_amount!=="string"||(row.document_number!==null&&typeof row.document_number!=="string")||(row.reference!==null&&typeof row.reference!=="string"))throw new Error("Invalid transfer register row.");return{id:parseUuid(row.document_id),number:row.document_number,state:row.state,date:row.accounting_date,reference:row.reference,from:row.from_account,to:row.to_account,principal:parseMoneyString(row.principal_amount),fee:parseMoneyString(row.fee_amount),total:parseMoneyString(row.total_amount)};});
  return <main className="content"><p className="eyebrow">Banking</p><h1>Transfers</h1><p>Move recorded balances between accounts. Internal cash-equivalent principal stays out of external cash flow; any fee remains separately classified.</p><div className="toolbar">{actor.capabilities.includes("banking.write")&&<Link className="primary" href={`/o/${organizationId}/banking/transfers/new`}>Record transfer</Link>}<Link className="secondary" href={`/o/${organizationId}/banking/accounts`}>Money accounts</Link></div><form className="panel toolbar" action={`/o/${organizationId}/banking/transfers`} method="get"><label>Search transfers<input type="search" name="search" maxLength={100} defaultValue={search}/></label><button type="submit">Search</button></form><section className="panel"><h2>Transfer history</h2>{rows.length===0?<p>No transfers match this search.</p>:<div className="table-scroll"><table><thead><tr><th>Transfer</th><th>Date</th><th>Reference</th><th>From</th><th>To</th><th>Principal (BDT)</th><th>Fee (BDT)</th><th>Total source (BDT)</th><th>State</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><Link href={`/o/${organizationId}/banking/transfers/${row.id}`}>{row.number??row.id}</Link></td><td>{row.date}</td><td>{row.reference??"—"}</td><td>{row.from}</td><td>{row.to}</td><td>{row.principal}</td><td>{row.fee}</td><td>{row.total}</td><td>{row.state.replaceAll("_"," ")}</td></tr>)}</tbody></table></div>}</section></main>;
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need banking.read to view transfers.</p></main>;throw error;}
}
