import { parseOrganizationId, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../../server/commands/errors.ts";
import { record } from "../../../../../../server/documents/contracts.ts";
import { readDraftOptions } from "../../../../../../server/documents/service.ts";
import { roleRuntime } from "../../../../../../server/roles/runtime.ts";
import { AdvanceActionForm } from "../action-form.tsx";
export const dynamic="force-dynamic";export const revalidate=0;
export default async function RefundAdvancePage({params}:{params:Promise<{organizationId:string;openItemId:string}>}){let organizationId,openItemId;try{const p=await params;organizationId=parseOrganizationId(p.organizationId);openItemId=parseUuid(p.openItemId);}catch{redirect("/companies?error=not_found");}const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");try{const actor=await resolveActorContext(organizationId,runtime.dependencies);const lifecycle=await runtime.client.rpc("read_advance_lifecycle",{p_organization_id:organizationId,p_open_item_id:openItemId});if(lifecycle.error){if(lifecycle.error.code==="P0002")throw CommandError.notFound();if(lifecycle.error.code==="42501")throw CommandError.forbidden();throw new Error("Advance is unavailable.");}const source=record(lifecycle.data,"advance");const customer=source.control_kind==="customer_advance";const capability=customer?"sales.write":"purchases.write";if(!actor.capabilities.includes(capability)||!actor.capabilities.includes("dues.allocate")||!actor.capabilities.includes("banking.write"))throw CommandError.forbidden();const today=new Date().toISOString().slice(0,10);const options=await readDraftOptions(runtime.client,actor,customer?"customer_advance":"vendor_advance",today);const cashAccounts=Array.isArray(options.cash_accounts)?options.cash_accounts.map((v:unknown)=>{const row=record(v,"cash_account");return{id:parseUuid(row.id),name:String(row.name),kind:String(row.kind)};}):[];return <main className="content"><p><Link href={`/o/${organizationId}/advances/${openItemId}`}>← Advance</Link></p><p className="eyebrow">Unused advance refund</p><h1>Refund {customer?"customer":"supplier"} advance</h1><p>Record an external cash refund against this advance. The amount is checked against the dated residual and never creates revenue or expense.</p><AdvanceActionForm organizationId={organizationId} openItemId={openItemId} kind="refund" accountingDate={today} cashAccounts={cashAccounts}/></main>;}catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="NOT_FOUND")redirect("/companies?error=not_found");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You do not have permission to refund this advance.</p></main>;throw error;}}
