import { parseMoneyString,parseOrganizationId,parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../../server/commands/errors.ts";
import { roleRuntime } from "../../../../../../server/roles/runtime.ts";
import { bangladeshDate } from "../../../../../../lib/date.ts";

export const dynamic="force-dynamic";export const revalidate=0;
export default async function CashAccountLedgerPage({params,searchParams}:{params:Promise<{organizationId:string;cashAccountId:string}>;searchParams:Promise<{from?:string;to?:string}>}){
 let organizationId,cashAccountId;try{const p=await params;organizationId=parseOrganizationId(p.organizationId);cashAccountId=parseUuid(p.cashAccountId);}catch{redirect("/companies?error=not_found");}
 const query=await searchParams;const to=query.to&&/^\d{4}-\d{2}-\d{2}$/.test(query.to)?query.to:bangladeshDate();const from=query.from&&/^\d{4}-\d{2}-\d{2}$/.test(query.from)?query.from:`${to.slice(0,4)}-01-01`;
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 let ledger:Record<string,unknown>;try{const actor=await resolveActorContext(organizationId,runtime.dependencies);if(!actor.capabilities.includes("banking.read"))throw CommandError.forbidden();const result=await runtime.client.rpc("read_cash_account_ledger",{p_organization_id:organizationId,p_cash_account_id:cashAccountId,p_from:from,p_to:to,p_limit:500});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();if(result.error.code==="P0002")throw CommandError.notFound();if(result.error.code==="22023")throw CommandError.validation({query:"Choose a valid date range."});throw new Error("Cashbook could not be loaded.");}if(!result.data||typeof result.data!=="object"||Array.isArray(result.data))throw new Error("Invalid cashbook response.");ledger=result.data as Record<string,unknown>;if(ledger.organization_id!==organizationId||ledger.cash_account_id!==cashAccountId||typeof ledger.name!=="string"||typeof ledger.kind!=="string"||!Array.isArray(ledger.transactions)||typeof ledger.opening_balance!=="string"||typeof ledger.closing_balance!=="string")throw new Error("Invalid cashbook data.");parseMoneyString(ledger.opening_balance);parseMoneyString(ledger.closing_balance);
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="NOT_FOUND")redirect(`/o/${organizationId}/banking/accounts?error=not_found`);if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need banking.read to view account balances.</p></main>;throw error;}
 return <main className="content"><p className="eyebrow">Banking · {String(ledger.kind).replaceAll("_"," ")}</p><h1>{String(ledger.name)}</h1><p>{String(ledger.account_code)} · {String(ledger.account_name)} · Book balances from posted entries</p><p><Link href={`/o/${organizationId}/banking/accounts`}>Back to cash and bank accounts</Link></p>
  <form className="panel toolbar" method="get"><label>From date<input type="date" name="from" defaultValue={from} required/></label><label>To date<input type="date" name="to" defaultValue={to} required/></label><button type="submit">Apply dates</button></form>
  <section className="panel"><h2>Cashbook summary</h2><dl><dt>Opening book balance</dt><dd>{String(ledger.opening_balance)} BDT</dd><dt>Closing book balance</dt><dd>{String(ledger.closing_balance)} BDT</dd><dt>Date range</dt><dd>{from} to {to}</dd></dl></section>
  <section className="panel"><h2>Ledger entries</h2>{ledger.transactions.length===0?<p>No posted transactions in this period.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Source</th><th>Reference</th><th>Description</th><th>Money in</th><th>Money out</th><th>Running book balance</th></tr></thead><tbody>{ledger.transactions.map((raw,index)=>{if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new Error("Invalid cashbook entry.");const row=raw as Record<string,unknown>;if(typeof row.accounting_date!=="string"||typeof row.debit!=="string"||typeof row.credit!=="string"||typeof row.running_balance!=="string")throw new Error("Invalid cashbook entry.");return <tr key={String(row.line_id??index)}><td>{row.accounting_date}</td><td>{typeof row.source_type==="string"?row.source_type.replaceAll("_"," "):"Journal"}{typeof row.source_document_id==="string"&&<><br/><Link href={`/o/${organizationId}/accounting/documents/${row.source_document_id}`}>Open source</Link></>}</td><td>{String(row.document_number??row.external_reference??"—")}</td><td>{String(row.description??"")}</td><td>{row.debit}</td><td>{row.credit}</td><td>{row.running_balance}</td></tr>;})}</tbody></table></div>}</section>
 </main>;
}
