import {parseOrganizationId} from "@ams/contracts";import Link from "next/link";import {redirect} from "next/navigation";
import {resolveActorContext} from "../../../../../server/auth/resolve-actor.ts";import {CommandError} from "../../../../../server/commands/errors.ts";
import {readSupplierBillRegister,type BillTab} from "../../../../../server/documents/supplier-bills.ts";import {roleRuntime} from "../../../../../server/roles/runtime.ts";
export const dynamic="force-dynamic";export const revalidate=0;const tabs:[BillTab,string][]=[["all","All"],["drafts","Drafts"],["awaiting_approval","Awaiting approval"],["posted","Posted"]];
export default async function SupplierBillRegisterPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{tab?:string;search?:string;after?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}const q=await searchParams;
 const tab=(tabs.some(([v])=>v===q.tab)?q.tab:"all") as BillTab;const search=typeof q.search==="string"?q.search.trim().slice(0,100):"";
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);const page=await readSupplierBillRegister(runtime.client,actor,{status:tab,search:search||null,after:q.after??null,limit:50});
  const href=(next:BillTab,after?:string)=>{const p=new URLSearchParams({tab:next});if(search)p.set("search",search);if(after)p.set("after",after);return`/o/${organizationId}/purchases/bills?${p}`;};
  return <main className="content"><p className="eyebrow">Purchases</p><h1>Supplier bills</h1><p>Bill posting increases accounts payable and expense or asset balances; recording payment remains a separate action.</p>
   <div className="toolbar">{actor.capabilities.includes("purchases.write")&&<Link className="primary" href={`/o/${organizationId}/purchases/bills/new`}>Create bill</Link>}<Link className="secondary" href={`/api/v1/organizations/${organizationId}/supplier-bills/export?tab=${tab}${search?`&search=${encodeURIComponent(search)}`:""}`}>Export filtered bills (CSV)</Link></div>
   <nav className="toolbar" aria-label="Supplier bill status">{tabs.map(([v,label])=><Link key={v} className={tab===v?"primary":"secondary"} aria-current={tab===v?"page":undefined} href={href(v)}>{label}</Link>)}</nav>
   <form className="panel toolbar" action={`/o/${organizationId}/purchases/bills`} method="get"><input type="hidden" name="tab" value={tab}/><label>Search bills<input type="search" name="search" maxLength={100} defaultValue={search} placeholder="Bill number, supplier or invoice reference"/></label><button type="submit">Search</button>{search&&<Link className="secondary" href={href(tab)}>Clear</Link>}</form>
   <section className="panel"><h2>{tabs.find(([v])=>v===tab)?.[1]} bills</h2>{page.items.length===0?<p>No supplier bills match these filters.</p>:<div className="table-scroll"><table><thead><tr><th>Number</th><th>Supplier</th><th>Invoice ref.</th><th>Invoice date</th><th>Accounting date</th><th>Due date</th><th>Total (BDT)</th><th>AP residual</th><th>Settlement</th><th>Duplicate ref.</th><th>Due</th><th>State</th><th>Actions</th></tr></thead><tbody>{page.items.map(b=><tr key={b.id}><td><Link href={`/o/${organizationId}/purchases/bills/${b.id}`}>{b.documentNumber??"Draft"}</Link></td><td>{b.vendorName}</td><td>{b.invoiceReference??"—"}</td><td>{b.invoiceDate??"—"}</td><td>{b.accountingDate}</td><td>{b.dueDate??"—"}</td><td>{b.totalAmount}</td><td>{b.residualAmount??"—"}</td><td>{b.settlementStatus.replaceAll("_"," ")}</td><td>{b.duplicateReference?<strong>Possible duplicate</strong>:"—"}</td><td>{b.overdue?"Overdue":"—"}</td><td>{b.state.replaceAll("_"," ")}</td><td><Link href={`/o/${organizationId}/purchases/bills/${b.id}${b.state==="draft"?"/edit":""}`}>{b.state==="draft"?"Edit":"Open"}</Link>{actor.capabilities.includes("purchases.write")&&<> · <Link href={`/o/${organizationId}/purchases/bills/new?copy=${b.id}`}>Duplicate as draft</Link></>}</td></tr>)}</tbody></table></div>}{page.nextCursor&&<p><Link className="secondary" href={href(tab,page.nextCursor)}>Next page</Link></p>}</section>
  </main>;
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="NOT_FOUND")redirect("/companies?error=not_found");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need purchases.read to view supplier bills.</p></main>;throw error;}
}
