"use client";
import {useId,useState} from "react";import type {AccountingPeriod} from "../../../../../server/periods/contracts.ts";import styles from "./screen.module.css";
export function PeriodScreen({organizationId,nonce,periods,canLock,canReopen}:{organizationId:string;nonce:string;periods:AccountingPeriod[];canLock:boolean;canReopen:boolean}){
const[busy,setBusy]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");
async function change(period:AccountingPeriod,action:"lock"|"reopen",reason:string){setBusy(period.id);setError("");setMessage("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/periods/${period.id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json","X-Request-Id":`period-${crypto.randomUUID()}`},body:JSON.stringify({expected_version:period.rowVersion,reason})});const json=await response.json();if(!response.ok)throw new Error(json?.error?.fields?.reason??json?.error?.fields?.period??json?.error?.message??"Could not change period status.");setMessage(`Period ${action==="lock"?"locked":"reopened"}. Refreshing period status.`);window.location.reload();}catch(e){setError(e instanceof Error?e.message:"Could not change period status.");}finally{setBusy("");}}
return <main className={styles.main} data-company-context={nonce}><p className="eyebrow">Accounting controls</p><h1>Fiscal periods</h1><p className="muted">Date-based operations must acquire the fiscal year and period locks in this order. Reopening leaves the previous lock event intact.</p>
{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.notice}>{message}</p>}
{periods.length===0?<section className="panel"><h2>No fiscal periods</h2><p>This company needs a fiscal calendar before normal accounting activity can be recorded.</p></section>:<section className={`panel ${styles.panel}`}><div className={styles.tableWrap}><table><thead><tr><th>Fiscal year</th><th>Period</th><th>Accounting dates</th><th>Status</th><th>Last event</th><th>Action</th></tr></thead><tbody>{periods.map(p=><tr key={p.id}><td>{p.yearLabel??"Opening"}</td><td>{p.label}</td><td>{p.startsOn} – {p.endsOn}</td><td><span className={p.status==="locked"?styles.locked:styles.open}>{p.status}</span></td><td>{p.lastAction?`${p.lastAction} · ${p.lastEventAt??""}`:"—"}{p.lastReason&&<small className={styles.reason}>{p.lastReason}</small>}</td><td>{p.status==="open"&&canLock?<ActionForm label="Lock period" busy={busy===p.id} disabled={Boolean(busy)} onSubmit={reason=>change(p,"lock",reason)}/>:p.status==="locked"&&canReopen?<ActionForm label="Reopen period" busy={busy===p.id} disabled={Boolean(busy)} onSubmit={reason=>change(p,"reopen",reason)}/>:"—"}</td></tr>)}</tbody></table></div><p className={styles.note}>This screen records lock/reopen events. The full close checklist, reconciliation snapshot, and year-close workflow belong to their dedicated stories.</p></section>}
</main>;
}
function ActionForm({label,busy,disabled,onSubmit}:{label:string;busy:boolean;disabled:boolean;onSubmit:(reason:string)=>void}){const id=useId();return <form className={styles.action} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);onSubmit(String(data.get("reason")??""));}}><label htmlFor={id}>Reason</label><textarea id={id} name="reason" required minLength={10} maxLength={1000} rows={2}/><button type="submit" className="secondary" disabled={disabled||busy}>{busy?"Saving…":label}</button></form>;}
