"use client";
import {useId,useState} from "react";import type {AccountingPeriod} from "../../../../../server/periods/contracts.ts";import styles from "./screen.module.css";
export function PeriodScreen({organizationId,nonce,periods,canLock,canReopen,canAudit}:{organizationId:string;nonce:string;periods:AccountingPeriod[];canLock:boolean;canReopen:boolean;canAudit:boolean}){
const[busy,setBusy]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");const[checklists,setChecklists]=useState<Record<string,CloseChecklist>>({});const[history,setHistory]=useState<Record<string,PeriodEvent[]>>({});
async function runChecks(period:AccountingPeriod){setBusy(period.id);setError("");setMessage("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/periods/${period.id}/checklist`,{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json?.error?.message??"Could not run period close checks.");setChecklists({...checklists,[period.id]:json.data as CloseChecklist});}catch(e){setError(e instanceof Error?e.message:"Could not run period close checks.");}finally{setBusy("");}}
async function loadHistory(period:AccountingPeriod){setBusy(period.id);setError("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/periods/${period.id}/events`,{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json?.error?.message??"Could not load period history.");setHistory({...history,[period.id]:Array.isArray(json.data)?json.data as PeriodEvent[]:[]});}catch(e){setError(e instanceof Error?e.message:"Could not load period history.");}finally{setBusy("");}}
async function change(period:AccountingPeriod,action:"lock"|"reopen",reason:string){setBusy(period.id);setError("");setMessage("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/periods/${period.id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json","X-Request-Id":`period-${crypto.randomUUID()}`},body:JSON.stringify({expected_version:period.rowVersion,reason})});const json=await response.json();if(!response.ok)throw new Error(json?.error?.fields?.reason??json?.error?.fields?.period??json?.error?.message??"Could not change period status.");setMessage(`Period ${action==="lock"?"locked":"reopened"}. Refreshing period status.`);window.location.reload();}catch(e){setError(e instanceof Error?e.message:"Could not change period status.");}finally{setBusy("");}}
return <main className={styles.main} data-company-context={nonce}><p className="eyebrow">Accounting controls</p><h1>Fiscal periods</h1><p className="muted">Date-based operations must acquire the fiscal year and period locks in this order. Reopening leaves the previous lock event intact.</p>
{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.notice}>{message}</p>}
{periods.length===0?<section className="panel"><h2>No fiscal periods</h2><p>This company needs a fiscal calendar before normal accounting activity can be recorded.</p></section>:<section className={`panel ${styles.panel}`}><div className={styles.tableWrap}><table><thead><tr><th>Fiscal year</th><th>Period</th><th>Accounting dates</th><th>Status</th><th>Last event</th><th>Action</th></tr></thead><tbody>{periods.map(p=><tr key={p.id}><td>{p.yearLabel??"Opening"}</td><td>{p.label}</td><td>{p.startsOn} – {p.endsOn}</td><td><span className={p.status==="locked"?styles.locked:styles.open}>{p.status}</span></td><td>{p.lastAction?`${p.lastAction} · ${p.lastEventAt??""}`:"—"}{p.lastReason&&<small className={styles.reason}>{p.lastReason}</small>}</td><td>{p.status==="open"&&canLock?<div className={styles.action}><button type="button" className="secondary" disabled={Boolean(busy)} onClick={()=>void runChecks(p)}>{busy===p.id?"Checking…":"Run close checks"}</button>{checklists[p.id]&&<p role={checklists[p.id].passed?"status":"alert"}>{checklists[p.id].passed?"All close checks passed.":`${checklists[p.id].blocking_count} blocking issue(s) remain.`}</p>}{checklists[p.id]?.passed&&<ActionForm label="Lock period" busy={busy===p.id} disabled={Boolean(busy)} onSubmit={reason=>change(p,"lock",reason)}/>}</div>:p.status==="locked"&&canReopen?<ActionForm label="Reopen period" busy={busy===p.id} disabled={Boolean(busy)} onSubmit={reason=>change(p,"reopen",reason)}/>:"—"}{canAudit&&<button type="button" className="secondary" disabled={Boolean(busy)} onClick={()=>void loadHistory(p)}>{busy===p.id?"Loading…":"View lock history"}</button>}</td></tr>)}</tbody></table></div>{Object.entries(checklists).map(([periodId,checklist])=><section key={periodId} className="panel"><h2>Close checklist · {periods.find(x=>x.id===periodId)?.label}</h2><div className="table-scroll"><table><thead><tr><th>Check</th><th>Result</th><th>Details</th></tr></thead><tbody>{checklist.checks.map(check=><tr key={check.code}><td>{check.code.replaceAll("_"," ")}</td><td>{check.count===0?"Clear":`${check.count} unresolved`}</td><td>{check.detail}</td></tr>)}</tbody></table></div><p>Checked {checklist.checked_at}. Locking recalculates all checks in the same database transaction.</p></section>)}{Object.entries(history).map(([periodId,events])=><section key={periodId} className="panel"><h2>Lock/reopen history · {periods.find(x=>x.id===periodId)?.label}</h2>{events.length===0?<p>No prior period events.</p>:<ol>{events.map((event,index)=><li key={`${event.action}-${event.created_at}-${index}`}><strong>{event.action}</strong> · {event.created_at}<p>{event.reason}</p><details><summary>Immutable close evidence</summary><pre>{JSON.stringify(event.snapshot,null,2)}</pre></details></li>)}</ol>}</section>)}</section>}
</main>;
}
type CloseChecklist={passed:boolean;blocking_count:number;checked_at:string;checks:{code:string;count:number;detail:string;blocking:boolean}[]};type PeriodEvent={action:"lock"|"reopen";reason:string;created_at:string;snapshot:Record<string,unknown>};
function ActionForm({label,busy,disabled,onSubmit}:{label:string;busy:boolean;disabled:boolean;onSubmit:(reason:string)=>void}){const id=useId();return <form className={styles.action} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);onSubmit(String(data.get("reason")??""));}}><label htmlFor={id}>Reason</label><textarea id={id} name="reason" required minLength={10} maxLength={1000} rows={2}/><button type="submit" className="secondary" disabled={disabled||busy}>{busy?"Saving…":label}</button></form>;}
