import { parseOrganizationId, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../../server/commands/errors.ts";
import { sourceTypes, type SourceType } from "../../../../../../server/documents/contracts.ts";
import { readDraftOptions, readFinancialDocument } from "../../../../../../server/documents/service.ts";
import { canPostDocument } from "../../../../../../server/documents/posting.ts";
import { readInvoiceLifecycle } from "../../../../../../server/documents/invoice-register.ts";
import { readSupplierRefundAllocationOptions, readSupplierRefundLifecycle, readVendorCreditBillLines, readVendorCreditLifecycle } from "../../../../../../server/documents/supplier-credits-refunds.ts";
import { roleRuntime } from "../../../../../../server/roles/runtime.ts";
import { DraftEditor, type DraftOptions } from "../draft-editor.tsx";
import { PostingAction } from "../posting-action.tsx";
import { WriteOffSubmitAction } from "../write-off-submit-action.tsx";
import styles from "../documents.module.css";

export const dynamic="force-dynamic";export const revalidate=0;
export async function DocumentDetailPage({params}:{params:Promise<{organizationId:string;documentId:string}>}){
 let organizationId;let documentId;try{const p=await params;organizationId=parseOrganizationId(p.organizationId);documentId=parseUuid(p.documentId);}catch{redirect("/companies?error=not_found");}
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);const document=await readFinancialDocument(runtime.client,actor,documentId);
  const type=String(document.document_type);const canEdit=String(document.state)==="draft"&&(sourceTypes as readonly string[]).includes(type);
  const invoiceLifecycle=type==="invoice"?await readInvoiceLifecycle(runtime.client,actor,documentId):null;
  const trade=document.trade&&typeof document.trade==="object"?document.trade as Record<string,unknown>:{};
  const partyId=typeof document.party_id==="string"?document.party_id:"";
  const originalId=typeof trade.original_document_id==="string"?trade.original_document_id:"";
  const vendorCreditLifecycle=type==="vendor_credit"?await readVendorCreditLifecycle(runtime.client,actor,documentId):null;
  const supplierRefundLifecycle=type==="vendor_refund"?await readSupplierRefundLifecycle(runtime.client,actor,documentId):null;
  let editor=null;if(canEdit){const raw=await readDraftOptions(runtime.client,actor,type,String(document.accounting_date));const options={accounts:Array.isArray(raw.accounts)?raw.accounts as DraftOptions["accounts"]:[],parties:Array.isArray(raw.parties)?raw.parties as DraftOptions["parties"]:[],cash_accounts:Array.isArray(raw.cash_accounts)?raw.cash_accounts as DraftOptions["cash_accounts"]:[],rounding_accounts:Array.isArray(raw.rounding_accounts)?raw.rounding_accounts as DraftOptions["rounding_accounts"]:[],tax_codes:Array.isArray(raw.tax_codes)?raw.tax_codes as DraftOptions["tax_codes"]:[],items:Array.isArray(raw.items)?raw.items as DraftOptions["items"]:[],cost_centers:Array.isArray(raw.cost_centers)?raw.cost_centers as DraftOptions["cost_centers"]:[]};
    const supplierBillLines=type==="vendor_credit"&&partyId&&originalId?await readVendorCreditBillLines(runtime.client,actor,partyId,originalId):[];
    const supplierCredits=type==="vendor_refund"&&partyId?await readSupplierRefundAllocationOptions(runtime.client,actor,partyId,String(document.accounting_date)):[];
    editor=<DraftEditor organizationId={organizationId} nonce={runtime.current.nonce} documentType={type as SourceType} options={options} initial={document} expectedVersion={Number(document.version)} supplierBillLines={supplierBillLines} supplierCredits={supplierCredits}/>;}
  const returnHref=type==="invoice"?`/o/${organizationId}/sales/invoices`:type==="vendor_credit"?`/o/${organizationId}/purchases/credits`:type==="vendor_refund"?`/o/${organizationId}/purchases/refunds`:`/o/${organizationId}/accounting/documents`;
  return <main className={styles.main}><p><Link href={returnHref}>← {type==="invoice"?"Invoices":type==="vendor_credit"?"Supplier credits":type==="vendor_refund"?"Supplier refunds":"Financial documents"}</Link></p>{editor??<><section className={`panel ${styles.panel}`}><p className="eyebrow">{document.document_type}</p><h1>{document.document_number??"Draft"}</h1><p>State: {String(document.state)} · Accounting date: {String(document.accounting_date)}</p><p>Total (BDT): {String(document.total_amount)}</p><p>{String(document.description??"")}</p>{type==="invoice"&&<InvoiceSnapshot organizationId={organizationId} document={document} lifecycle={invoiceLifecycle!} capabilities={actor.capabilities}/>}{vendorCreditLifecycle&&<SupplierLifecycle kind="credit" data={vendorCreditLifecycle} organizationId={organizationId} capabilities={actor.capabilities}/>}{supplierRefundLifecycle&&<SupplierLifecycle kind="refund" data={supplierRefundLifecycle} organizationId={organizationId} capabilities={actor.capabilities}/>}{Array.isArray(document.lines)&&document.lines.length>0&&<LineSnapshotTable rows={document.lines as Record<string,unknown>[]}/>}{String(type)==="write_off"&&<div><h2>Controlled write-off evidence</h2>{document.write_off&&typeof document.write_off==="object"&&<p>Target receivable item: {String((document.write_off as Record<string,unknown>).target_open_item_id)} · Reason: {String((document.write_off as Record<string,unknown>).reason)}</p>}{Array.isArray(document.journal_rows)&&<table><thead><tr><th>Account</th><th>Party</th><th>Reference</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{(document.journal_rows as Record<string,unknown>[]).map((row,i)=><tr key={i}><td>{String(row.account_id)}</td><td>{String(row.party_id??"—")}</td><td>{String(row.open_item_reference??"—")}</td><td>{String(row.debit)}</td><td>{String(row.credit)}</td></tr>)}</tbody></table>}{document.posted_journal&&typeof document.posted_journal==="object"&&<><h3>Posted ledger entry {String((document.posted_journal as Record<string,unknown>).id)}</h3><table><thead><tr><th>Account</th><th>Party</th><th>Open item</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{(Array.isArray((document.posted_journal as Record<string,unknown>).lines)?(document.posted_journal as Record<string,unknown>).lines as Record<string,unknown>[]:[]).map((line,i)=><tr key={i}><td>{String(line.account_id)}</td><td>{String(line.party_id??"—")}</td><td>{String(line.open_item_id??"—")}</td><td>{String(line.debit)}</td><td>{String(line.credit)}</td></tr>)}</tbody></table></>}<p>Tax is not automatically reversed for this bad-debt write-off. The linked debit and credit open items document the explicit settlement.</p></div>}</section>
    {String(type)==="write_off"&&String(document.state)==="draft"&&<WriteOffSubmitAction organizationId={organizationId} documentId={documentId} version={Number(document.version)}/>}
    {String(document.state)==="approved"&&canPostDocument(actor,String(document.document_type))&&<PostingAction organizationId={organizationId} documentId={documentId} version={Number(document.version)}/>}
   </>}</main>;
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="NOT_FOUND")redirect("/companies?error=not_found");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main><h1>Access denied</h1><p>You do not have permission to open this document.</p></main>;throw error;}
}
export default DocumentDetailPage;
function SupplierLifecycle({kind,data,organizationId,capabilities}:{kind:"credit"|"refund";data:Record<string,unknown>;organizationId:string;capabilities:readonly string[]}){
 const allocations=Array.isArray(data.allocations)?data.allocations as Record<string,unknown>[]:[];
  const approvals=Array.isArray(data.approvals)?data.approvals as Record<string,unknown>[]:[];
  const reversals=Array.isArray(data.reversals)?data.reversals as Record<string,unknown>[]:[];
 const sourceLines=Array.isArray(data.source_line_snapshots)?data.source_line_snapshots as Record<string,unknown>[]:[];
 const refund=kind==="refund";
 return <section className="panel" aria-label={refund?"Supplier refund history":"Supplier credit history"}>
  <h2>{refund?"Supplier refund settlement":"Supplier credit lifecycle"}</h2>
  {refund?<p>Cash received: BDT {String(data.total_amount)} · Settled against credits: BDT {String(data.settled_amount)}</p>:<><p>Original bill: {typeof data.original_document_id==="string"?<Link href={`/o/${organizationId}/accounting/documents/${data.original_document_id}`}>{String(data.original_document_number??data.original_document_id)}</Link>:"Unavailable"}</p><p>Credit total: BDT {String(data.total_amount)} · Applied: BDT {String(data.applied_amount)} · Remaining: BDT {String(data.residual_amount??"—")}</p></>}
  <h3>Allocations</h3>{allocations.length===0?<p>No allocations recorded.</p>:<ul>{allocations.map((row,i)=><li key={String(row.id??i)}>BDT {String(row.amount)} · {String(row.effective_date)} · {typeof row.counter_document_id==="string"?<Link href={`/o/${organizationId}/accounting/documents/${row.counter_document_id}`}>{String(row.counter_document_number??row.counter_document_type)}</Link>:typeof row.vendor_credit_id==="string"?<Link href={`/o/${organizationId}/accounting/documents/${row.vendor_credit_id}`}>{String(row.vendor_credit_number??row.vendor_credit_id)}</Link>:"Supplier credit"}{row.reversed_on?` · reversed ${String(row.reversed_on)}`:""}</li>)}</ul>}
  {!refund&&<><h3>Original bill line and tax snapshots</h3>{sourceLines.length===0?<p>No source line snapshots are available.</p>:<div className="table-scroll"><table><thead><tr><th>Original line</th><th>Recoverability</th><th>Tax snapshot</th><th>Original quantity</th><th>Credited quantity</th><th>Original gross (BDT)</th><th>Credited gross (BDT)</th></tr></thead><tbody>{sourceLines.map((row,i)=><tr key={String(row.credit_line_id??i)}><td>{String(row.description)} · {String(row.original_line_id)}</td><td>{String(row.tax_recoverability)}</td><td>{String(row.tax_label??"No tax")} · {String(row.tax_rate??"0")}%</td><td>{String(row.original_quantity)}</td><td>{String(row.credited_quantity)}</td><td>{String(row.original_gross)}</td><td>{String(row.credited_gross)}</td></tr>)}</tbody></table></div>}</>}
  {!refund&&capabilities.includes("approvals.read")&&<><h3>Approval history</h3>{approvals.length===0?<p>No approval request.</p>:approvals.map((row,i)=><p key={String(row.id??i)}>{String(row.state)} · version {String(row.version)} · {String(row.created_at)}{Array.isArray(row.decisions)?(row.decisions as Record<string,unknown>[]).map((decision,j)=><span key={j}> · {String(decision.decision)} ({String(decision.created_at)}){decision.reason?` · ${String(decision.reason)}`:""}</span>):null}</p>)}</>}
  {!refund&&<><h3>Reversals</h3>{reversals.length===0?<p>No reversal recorded.</p>:reversals.map((row,i)=><p key={String(row.id??i)}><Link href={`/o/${organizationId}/accounting/documents/${String(row.id)}`}>{String(row.document_number??row.id)}</Link> · {String(row.state)} · {String(row.accounting_date)} · {String(row.reason??"")}</p>)}</>}
 </section>;
}
function LineSnapshotTable({rows}:{rows:Record<string,unknown>[]}){return <div className="table-scroll"><table><thead><tr><th>Description</th><th>Item snapshot</th><th>SKU snapshot</th><th>Quantity</th><th>Unit</th><th>Unit rate</th><th>Tax snapshot</th><th>Net</th><th>Tax</th><th>Gross</th><th>Cost center</th></tr></thead><tbody>{rows.map((row,index)=>{const item=row.item_snapshot&&typeof row.item_snapshot==="object"?row.item_snapshot as Record<string,unknown>:{};const center=row.cost_center_snapshot&&typeof row.cost_center_snapshot==="object"?row.cost_center_snapshot as Record<string,unknown>:{};return <tr key={String(row.id??index)}><td>{String(row.description)}</td><td>{String(item.name??"—")}</td><td>{String(item.sku??"—")}</td><td>{String(row.quantity)}</td><td>{String(item.unit??"—")}</td><td>{String(row.unit_price)}</td><td>{String(row.tax_label_snapshot??"No tax")} · {String(row.tax_rate_snapshot??"0")}%</td><td>{String(row.net_amount)}</td><td>{String(row.tax_amount)}</td><td>{String(row.gross_amount)}</td><td>{center.id?`${String(center.code)} · ${String(center.name)}`:"—"}</td></tr>;})}</tbody></table></div>;}
function InvoiceSnapshot({organizationId,document,lifecycle,capabilities}:{organizationId:string;document:Record<string,unknown>;lifecycle:Record<string,unknown>;capabilities:readonly string[]}){
 const party=document.party_snapshot&&typeof document.party_snapshot==="object"?document.party_snapshot as Record<string,unknown>:{};
 const trade=document.trade&&typeof document.trade==="object"?document.trade as Record<string,unknown>:{};
 const rows=(key:string)=>Array.isArray(lifecycle[key])?lifecycle[key] as Record<string,unknown>[]:[];
 const allocations=rows("allocations"),deliveries=rows("delivery_attempts"),approvals=rows("approvals"),corrections=rows("corrections"),attachments=rows("attachments"),activity=rows("activity");
 const journal=document.posted_journal&&typeof document.posted_journal==="object"?document.posted_journal as Record<string,unknown>:null;
 const total=String(document.total_amount??"0.00");const balance=lifecycle.residual_amount===null?"—":String(lifecycle.residual_amount);
 return <><section aria-label="Invoice source, settlement and delivery status" className="panel"><h2>Invoice status</h2><p>Source: {String(lifecycle.state)} · Settlement: {String(lifecycle.settlement_status).replaceAll("_"," ")} · Delivery: {deliveries.length?String(deliveries.at(-1)?.status):"not sent"}</p><p>Total: BDT {total} · Residual: BDT {balance} {lifecycle.overdue===true&&<strong>· Overdue</strong>}</p><p>Recognition: {String(trade.recognition_mode??"earned_or_incurred").replaceAll("_"," ")} · Performance confirmed: {trade.performance_confirmed===true?"Yes":"No"}</p><h3>Issued customer snapshot</h3><p>{String(party.display_name??"Customer unavailable")} · {String(party.legal_name??"")}</p><p>{String(party.email??"")} · {String(party.phone??"")}</p><pre>{JSON.stringify({billing_address:party.billing_address??{},tax_identifiers:party.tax_identifiers??{}},null,2)}</pre>
  {String(lifecycle.state)==="posted"&&<div className="toolbar"><Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=receipt&party_id=${String(document.party_id)}`}>Record customer receipt</Link><Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=customer_credit&party_id=${String(document.party_id)}&original_document_id=${String(document.id)}`}>Issue customer credit</Link></div>}
 </section><section className="panel"><h2>Payments and credits</h2>{allocations.length===0?<p>No settlement allocations are linked.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Source</th><th>Allocated (BDT)</th><th>Allocation state</th></tr></thead><tbody>{allocations.map(a=><tr key={String(a.id)}><td>{String(a.effective_date)}</td><td>{String(a.counter_document_number??a.counter_document_type)}</td><td>{String(a.amount)}</td><td>{a.reversed_on?`Reversed ${String(a.reversed_on)}`:"Active"}</td></tr>)}</tbody></table></div>}</section>
 <section className="panel"><h2>Delivery attempts</h2>{deliveries.length?deliveries.map((item,i)=><p key={String(item.created_at??i)}>{String(item.channel)} · {String(item.status)} · {String(item.created_at)}{item.delivered_at?` · delivered ${String(item.delivered_at)}`:""}</p>):<p>No delivery attempt recorded. Email delivery never changes invoice posting state.</p>}</section>
 {capabilities.includes("approvals.read")&&<section className="panel"><h2>Approval history</h2>{approvals.length?approvals.map(request=><div key={String(request.id)}><p>{String(request.state)} · version {String(request.version)} · {String(request.created_at)}</p>{Array.isArray(request.decisions)&&(request.decisions as Record<string,unknown>[]).map((decision,i)=><p key={i}>{String(decision.decision)} · {String(decision.decided_by)} · {String(decision.created_at)}{decision.reason?` · ${String(decision.reason)}`:""}</p>)}</div>):<p>No approval request.</p>}</section>}
 <section className="panel"><h2>Corrections</h2>{corrections.length?corrections.map(row=><p key={String(row.id)}><Link href={`/o/${organizationId}/accounting/documents/${String(row.id)}`}>{String(row.document_number??row.document_type)}</Link> · {String(row.state)} · {String(row.accounting_date)} · {String(row.reason??"")}</p>):<p>No linked reversal or correction document.</p>}</section>
 {capabilities.includes("attachments.read")&&<section className="panel"><h2>Attachments</h2>{attachments.length?attachments.map(a=><p key={String(a.id)}>{String(a.filename)} · {String(a.content_type)} · {String(a.byte_size)} bytes · {String(a.scan_status)}</p>):<p>No attached evidence.</p>}</section>}
 {capabilities.includes("audit.read")&&<section className="panel"><h2>Activity</h2>{activity.length?activity.map((event,i)=><p key={i}>{String(event.action)} · {String(event.actor_kind)} · {String(event.created_at)}{event.reason?` · ${String(event.reason)}`:""}</p>):<p>No activity recorded.</p>}</section>}
 {capabilities.includes("ledger.read")&&<section className="panel"><h2>Accounting</h2>{journal?<><p>Posted journal {String(journal.id)} · {String(journal.accounting_date)}</p><table><thead><tr><th>Account ID</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{(Array.isArray(journal.lines)?journal.lines as Record<string,unknown>[]:[]).map((line,i)=><tr key={i}><td>{String(line.account_id)}</td><td>{String(line.debit)}</td><td>{String(line.credit)}</td></tr>)}</tbody></table></>:<p>No posted journal is linked.</p>}</section>}</>;
}
