import { parseOrganizationId, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../../server/commands/errors.ts";
import { sourceTypes, type SourceType } from "../../../../../../server/documents/contracts.ts";
import { readDraftOptions, readFinancialDocument } from "../../../../../../server/documents/service.ts";
import { canPostDocument } from "../../../../../../server/documents/posting.ts";
import { readInvoiceLifecycle } from "../../../../../../server/documents/invoice-register.ts";
import { readSupplierBillLifecycle } from "../../../../../../server/documents/supplier-bills.ts";
import { roleRuntime } from "../../../../../../server/roles/runtime.ts";
import { DraftEditor, type DraftOptions } from "../draft-editor.tsx";
import { PostingAction } from "../posting-action.tsx";
import { WriteOffSubmitAction } from "../write-off-submit-action.tsx";
import { BillAllocationUnapplyAction } from "../bill-allocation-unapply-action.tsx";
import styles from "../documents.module.css";

export const dynamic="force-dynamic";export const revalidate=0;
export async function DocumentDetailPage({params}:{params:Promise<{organizationId:string;documentId:string}>}){
 let organizationId;let documentId;try{const p=await params;organizationId=parseOrganizationId(p.organizationId);documentId=parseUuid(p.documentId);}catch{redirect("/companies?error=not_found");}
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);const document=await readFinancialDocument(runtime.client,actor,documentId);
  const type=String(document.document_type);const canEdit=String(document.state)==="draft"&&(sourceTypes as readonly string[]).includes(type);
  const invoiceLifecycle=type==="invoice"?await readInvoiceLifecycle(runtime.client,actor,documentId):null;
  const billLifecycle=type==="bill"?await readSupplierBillLifecycle(runtime.client,actor,documentId):null;
  let editor=null;if(canEdit){const raw=await readDraftOptions(runtime.client,actor,type,String(document.accounting_date));const options={accounts:Array.isArray(raw.accounts)?raw.accounts as DraftOptions["accounts"]:[],parties:Array.isArray(raw.parties)?raw.parties as DraftOptions["parties"]:[],cash_accounts:Array.isArray(raw.cash_accounts)?raw.cash_accounts as DraftOptions["cash_accounts"]:[],rounding_accounts:Array.isArray(raw.rounding_accounts)?raw.rounding_accounts as DraftOptions["rounding_accounts"]:[],tax_codes:Array.isArray(raw.tax_codes)?raw.tax_codes as DraftOptions["tax_codes"]:[],items:Array.isArray(raw.items)?raw.items as DraftOptions["items"]:[],cost_centers:Array.isArray(raw.cost_centers)?raw.cost_centers as DraftOptions["cost_centers"]:[]};
    editor=<DraftEditor organizationId={organizationId} nonce={runtime.current.nonce} documentType={type as SourceType} options={options} initial={document} expectedVersion={Number(document.version)}/>;}
  return <main className={styles.main}><p><Link href={type==="invoice"?`/o/${organizationId}/sales/invoices`:type==="bill"?`/o/${organizationId}/purchases/bills`:`/o/${organizationId}/accounting/documents`}>← {type==="invoice"?"Invoices":type==="bill"?"Supplier bills":"Financial documents"}</Link></p>{editor??<><section className={`panel ${styles.panel}`}><p className="eyebrow">{document.document_type}</p><h1>{document.document_number??"Draft"}</h1><p>State: {String(document.state)} · Accounting date: {String(document.accounting_date)}</p><p>Total (BDT): {String(document.total_amount)}</p><p>{String(document.description??"")}</p>{type==="invoice"&&<InvoiceSnapshot organizationId={organizationId} document={document} lifecycle={invoiceLifecycle!} capabilities={actor.capabilities}/>}{type==="bill"&&<SupplierBillSnapshot organizationId={organizationId} document={document} lifecycle={billLifecycle!} capabilities={actor.capabilities}/>}{Array.isArray(document.lines)&&document.lines.length>0&&<LineSnapshotTable rows={document.lines as Record<string,unknown>[]}/>}{String(type)==="write_off"&&<div><h2>Controlled write-off evidence</h2>{document.write_off&&typeof document.write_off==="object"&&<p>Target receivable item: {String((document.write_off as Record<string,unknown>).target_open_item_id)} · Reason: {String((document.write_off as Record<string,unknown>).reason)}</p>}{Array.isArray(document.journal_rows)&&<table><thead><tr><th>Account</th><th>Party</th><th>Reference</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{(document.journal_rows as Record<string,unknown>[]).map((row,i)=><tr key={i}><td>{String(row.account_id)}</td><td>{String(row.party_id??"—")}</td><td>{String(row.open_item_reference??"—")}</td><td>{String(row.debit)}</td><td>{String(row.credit)}</td></tr>)}</tbody></table>}{document.posted_journal&&typeof document.posted_journal==="object"&&<><h3>Posted ledger entry {String((document.posted_journal as Record<string,unknown>).id)}</h3><table><thead><tr><th>Account</th><th>Party</th><th>Open item</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{(Array.isArray((document.posted_journal as Record<string,unknown>).lines)?(document.posted_journal as Record<string,unknown>).lines as Record<string,unknown>[]:[]).map((line,i)=><tr key={i}><td>{String(line.account_id)}</td><td>{String(line.party_id??"—")}</td><td>{String(line.open_item_id??"—")}</td><td>{String(line.debit)}</td><td>{String(line.credit)}</td></tr>)}</tbody></table></>}<p>Tax is not automatically reversed for this bad-debt write-off. The linked debit and credit open items document the explicit settlement.</p></div>}</section>
    {String(type)==="write_off"&&String(document.state)==="draft"&&<WriteOffSubmitAction organizationId={organizationId} documentId={documentId} version={Number(document.version)}/>}
    {String(document.state)==="approved"&&canPostDocument(actor,String(document.document_type))&&<PostingAction organizationId={organizationId} documentId={documentId} version={Number(document.version)}/>}
   </>}</main>;
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="NOT_FOUND")redirect("/companies?error=not_found");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main><h1>Access denied</h1><p>You do not have permission to open this document.</p></main>;throw error;}
}
export default DocumentDetailPage;
function SupplierBillSnapshot({organizationId,document,lifecycle,capabilities}:{organizationId:string;document:Record<string,unknown>;lifecycle:Record<string,unknown>;capabilities:readonly string[]}){
 const party=document.party_snapshot&&typeof document.party_snapshot==="object"?document.party_snapshot as Record<string,unknown>:{};
 const trade=document.trade&&typeof document.trade==="object"?document.trade as Record<string,unknown>:{};
 const rows=(key:string)=>Array.isArray(lifecycle[key])?lifecycle[key] as Record<string,unknown>[]:[];
 const allocations=rows("allocations"),approvals=rows("approvals"),corrections=rows("corrections"),attachments=rows("attachments"),activity=rows("activity");
 const journal=document.posted_journal&&typeof document.posted_journal==="object"?document.posted_journal as Record<string,unknown>:null;
 return <><section className="panel"><h2>Supplier bill status</h2><p>Settlement: {String(lifecycle.settlement_status).replaceAll("_"," ")} · AP outstanding: BDT {String(lifecycle.residual_amount??"—")} · {lifecycle.overdue===true&&<strong>Overdue · </strong>}Due {String(document.due_date??"not set")}</p>
  <h3>Original supplier invoice</h3><p>Supplier: {String(party.display_name??"Supplier unavailable")} · {String(party.legal_name??"")}</p><p>Supplier reference: {String(trade.supplier_invoice_key??"—")} · Invoice date: {String(trade.supplier_invoice_date??"—")}</p><p>{String(party.email??"")} · {String(party.phone??"")}</p>
  {lifecycle.duplicate_reference===true&&<p role="status"><strong>Possible duplicate supplier invoice reference.</strong> Check the vendor’s other bills before continuing.</p>}
  {String(lifecycle.state)==="posted"&&capabilities.includes("purchases.write")&&<div className="toolbar">{String(lifecycle.residual_amount??"0.00")!=="0.00"&&<Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=vendor_payment&party_id=${String(document.party_id)}`}>Record supplier payment</Link>}<Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=vendor_credit&party_id=${String(document.party_id)}&original_document_id=${String(document.id)}`}>Record supplier credit</Link></div>}
 </section><section className="panel"><h2>Payments and credits</h2>{allocations.length===0?<p>No payment or credit allocations are linked.</p>:<div className="table-scroll"><table><thead><tr><th>Source</th><th>Allocated (BDT)</th><th>Effective date</th><th>State</th><th>Correction</th></tr></thead><tbody>{allocations.map(row=><tr key={String(row.id)}><td>{String(row.counter_document_number??row.counter_document_type)}</td><td>{String(row.amount)}</td><td>{String(row.effective_date)}</td><td>{row.reversed_on?`Unapplied ${String(row.reversed_on)}`:"Active"}</td><td>{capabilities.includes("dues.allocate")&&!row.reversed_on&&<BillAllocationUnapplyAction organizationId={organizationId} allocationId={String(row.id)}/>}</td></tr>)}</tbody></table></div>}</section>
 {capabilities.includes("approvals.read")&&<section className="panel"><h2>Approval history</h2>{approvals.length?approvals.map(row=><div key={String(row.id)}><p>{String(row.state)} · version {String(row.version)} · {String(row.created_at)}</p>{Array.isArray(row.decisions)&&(row.decisions as Record<string,unknown>[]).map((decision,i)=><p key={i}>{String(decision.decision)} · {String(decision.decided_by)} · {String(decision.created_at)}{decision.reason?` · ${String(decision.reason)}`:""}</p>)}</div>):<p>No approval request.</p>}</section>}
 <section className="panel"><h2>Corrections</h2>{corrections.length?corrections.map(row=><p key={String(row.id)}><Link href={`/o/${organizationId}/accounting/documents/${String(row.id)}`}>{String(row.document_number??row.document_type)}</Link> · {String(row.state)} · {String(row.accounting_date)} · {String(row.reason??"")}</p>):<p>No linked correction.</p>}</section>
 {capabilities.includes("attachments.read")&&<section className="panel"><h2>Evidence attachments</h2>{attachments.length?attachments.map(row=><p key={String(row.id)}>{String(row.filename)} · {String(row.content_type)} · {String(row.byte_size)} bytes · {String(row.scan_status)}</p>):<p>No evidence attachment linked. Upload is available when the private evidence module is implemented.</p>}</section>}
 {capabilities.includes("audit.read")&&<section className="panel"><h2>Activity</h2>{activity.length?activity.map((row,i)=><p key={i}>{String(row.action)} · {String(row.actor_kind)} · {String(row.created_at)}{row.reason?` · ${String(row.reason)}`:""}</p>):<p>No activity recorded.</p>}</section>}
 {capabilities.includes("ledger.read")&&<section className="panel"><h2>Accounting</h2>{journal?<><p>Posted journal {String(journal.id)} · {String(journal.accounting_date)}</p><table><thead><tr><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{(Array.isArray(journal.lines)?journal.lines as Record<string,unknown>[]:[]).map((line,i)=><tr key={i}><td>{String(line.account_id)}</td><td>{String(line.debit)}</td><td>{String(line.credit)}</td></tr>)}</tbody></table></>:<p>No posted journal is linked.</p>}</section>}
 </>;
}
function LineSnapshotTable({rows}:{rows:Record<string,unknown>[]}){return <div className="table-scroll"><table><thead><tr><th>Description</th><th>Item snapshot</th><th>SKU snapshot</th><th>Quantity</th><th>Unit</th><th>Unit rate</th><th>Tax snapshot</th><th>Recovery</th><th>Net</th><th>Tax</th><th>Gross</th><th>Cost center</th></tr></thead><tbody>{rows.map((row,index)=>{const item=row.item_snapshot&&typeof row.item_snapshot==="object"?row.item_snapshot as Record<string,unknown>:{};const center=row.cost_center_snapshot&&typeof row.cost_center_snapshot==="object"?row.cost_center_snapshot as Record<string,unknown>:{};return <tr key={String(row.id??index)}><td>{String(row.description)}</td><td>{String(item.name??"—")}</td><td>{String(item.sku??"—")}</td><td>{String(row.quantity)}</td><td>{String(item.unit??"—")}</td><td>{String(row.unit_price)}</td><td>{String(row.tax_label_snapshot??"No tax")} · {String(row.tax_rate_snapshot??"0")}%</td><td>{String(row.tax_recoverability_snapshot??"none")}</td><td>{String(row.net_amount)}</td><td>{String(row.tax_amount)}</td><td>{String(row.gross_amount)}</td><td>{center.id?`${String(center.code)} · ${String(center.name)}`:"—"}</td></tr>;})}</tbody></table></div>;}
function InvoiceSnapshot({organizationId,document,lifecycle,capabilities}:{organizationId:string;document:Record<string,unknown>;lifecycle:Record<string,unknown>;capabilities:readonly string[]}){
 const party=document.party_snapshot&&typeof document.party_snapshot==="object"?document.party_snapshot as Record<string,unknown>:{};
 const trade=document.trade&&typeof document.trade==="object"?document.trade as Record<string,unknown>:{};
 const rows=(key:string)=>Array.isArray(lifecycle[key])?lifecycle[key] as Record<string,unknown>[]:[];
 const allocations=rows("allocations"),deliveries=rows("delivery_attempts"),approvals=rows("approvals"),corrections=rows("corrections"),attachments=rows("attachments"),activity=rows("activity");
 const journal=document.posted_journal&&typeof document.posted_journal==="object"?document.posted_journal as Record<string,unknown>:null;
 const total=String(document.total_amount??"0.00");const balance=lifecycle.residual_amount===null?"—":String(lifecycle.residual_amount);
 return <><section aria-label="Invoice source, settlement and delivery status" className="panel"><h2>Invoice status</h2><p>Source: {String(lifecycle.state)} · Settlement: {String(lifecycle.settlement_status).replaceAll("_"," ")} · Delivery: {deliveries.length?String(deliveries.at(-1)?.status):"not sent"}</p><p>Total: BDT {total} · Residual: BDT {balance} {lifecycle.overdue===true&&<strong>· Overdue</strong>}</p><p>Recognition: {String(trade.recognition_mode??"earned_or_incurred").replaceAll("_"," ")} · Performance confirmed: {trade.performance_confirmed===true?"Yes":"No"}</p><h3>Issued customer snapshot</h3><p>{String(party.display_name??"Customer unavailable")} · {String(party.legal_name??"")}</p><p>{String(party.email??"")} · {String(party.phone??"")}</p><pre>{JSON.stringify({billing_address:party.billing_address??{},tax_identifiers:party.tax_identifiers??{}},null,2)}</pre>
  {String(lifecycle.state)==="posted"&&<div className="toolbar"><Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=receipt&party_id=${String(document.party_id)}`}>Record customer receipt</Link><Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=customer_credit&party_id=${String(document.party_id)}&original_document_id=${String(document.id)}`}>Issue customer credit</Link></div>}
 </section><section className="panel"><h2>Payments and credits</h2>{allocations.length===0?<p>No settlement allocations are linked.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Source</th><th>Allocated (BDT)</th><th>Allocation state</th></tr></thead><tbody>{allocations.map(a=><tr key={String(a.id)}><td>{String(a.effective_date)}</td><td>{String(a.counter_document_number??a.counter_document_type)}</td><td>{String(a.amount)}</td><td>{a.reversed_on?`Reversed ${String(a.reversed_on)}`:"Active"}</td></tr>)}</tbody></table></div>}</section>
 <section className="panel"><h2>Delivery attempts</h2>{deliveries.length?deliveries.map((item,i)=><p key={String(item.created_at??i)}>{String(item.channel)} · {String(item.status)} · {String(item.created_at)}{item.delivered_at?` · delivered ${String(item.delivered_at)}`:""}</p>):<p>No delivery attempt recorded. Email delivery never changes invoice posting state.</p>}</section>
 {capabilities.includes("approvals.read")&&<section className="panel"><h2>Approval history</h2>{approvals.length?approvals.map(request=><div key={String(request.id)}><p>{String(request.state)} · version {String(request.version)} · {String(request.created_at)}</p>{Array.isArray(request.decisions)&&(request.decisions as Record<string,unknown>[]).map((decision,i)=><p key={i}>{String(decision.decision)} · {String(decision.decided_by)} · {String(decision.created_at)}{decision.reason?` · ${String(decision.reason)}`:""}</p>)}</div>):<p>No approval request.</p>}</section>}
 <section className="panel"><h2>Corrections</h2>{corrections.length?corrections.map(row=><p key={String(row.id)}><Link href={`/o/${organizationId}/accounting/documents/${String(row.id)}`}>{String(row.document_number??row.document_type)}</Link> · {String(row.state)} · {String(row.accounting_date)} · {String(row.reason??"")}</p>):<p>No linked reversal or correction document.</p>}</section>
 {capabilities.includes("attachments.read")&&<section className="panel"><h2>Attachments</h2>{attachments.length?attachments.map(a=><p key={String(a.id)}>{String(a.filename)} · {String(a.content_type)} · {String(a.byte_size)} bytes · {String(a.scan_status)}</p>):<p>No attached evidence.</p>}</section>}
 {capabilities.includes("audit.read")&&<section className="panel"><h2>Activity</h2>{activity.length?activity.map((event,i)=><p key={i}>{String(event.action)} · {String(event.actor_kind)} · {String(event.created_at)}{event.reason?` · ${String(event.reason)}`:""}</p>):<p>No activity recorded.</p>}</section>}
 {capabilities.includes("ledger.read")&&<section className="panel"><h2>Accounting</h2>{journal?<><p>Posted journal {String(journal.id)} · {String(journal.accounting_date)}</p><table><thead><tr><th>Account ID</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{(Array.isArray(journal.lines)?journal.lines as Record<string,unknown>[]:[]).map((line,i)=><tr key={i}><td>{String(line.account_id)}</td><td>{String(line.debit)}</td><td>{String(line.credit)}</td></tr>)}</tbody></table></>:<p>No posted journal is linked.</p>}</section>}</>;
}
