import { parseOrganizationId, parseMoneyString, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { record } from "../../../../../server/documents/contracts.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";

export const dynamic="force-dynamic";export const revalidate=0;
export default async function AdvanceDetailPage({params}:{params:Promise<{organizationId:string;openItemId:string}>}){
 let organizationId,openItemId;try{const p=await params;organizationId=parseOrganizationId(p.organizationId);openItemId=parseUuid(p.openItemId);}catch{redirect("/companies?error=not_found");}
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);const result=await runtime.client.rpc("read_advance_lifecycle",{p_organization_id:organizationId,p_open_item_id:openItemId});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();if(result.error.code==="P0002")throw CommandError.notFound();throw new Error("Advance history could not be loaded.");}
  const data=record(result.data,"advance_lifecycle");if(typeof data.document_type!=="string"||typeof data.document_number!=="string"||typeof data.original_amount!=="string"||typeof data.applied_amount!=="string"||typeof data.refunded_amount!=="string"||typeof data.remaining_amount!=="string"||!Array.isArray(data.activity))throw new Error("Invalid advance lifecycle response.");
  const documentId=parseUuid(data.document_id);const original=parseMoneyString(data.original_amount);const applied=parseMoneyString(data.applied_amount);const refunded=parseMoneyString(data.refunded_amount);const remaining=parseMoneyString(data.remaining_amount);const activity=(data.activity as unknown[]).map(value=>{const row=record(value,"advance_activity");if(typeof row.amount!=="string"||typeof row.effective_date!=="string"||(row.other_document_id!==null&&typeof row.other_document_id!=="string")||(row.other_document_number!==null&&typeof row.other_document_number!=="string")||(row.other_document_type!==null&&typeof row.other_document_type!=="string")||(row.reversal_document_id!==null&&typeof row.reversal_document_id!=="string")||(row.reversal_document_number!==null&&typeof row.reversal_document_number!=="string"))throw new Error("Invalid advance activity row.");return{...row,amount:parseMoneyString(row.amount)};});
  const customer=data.document_type==="customer_advance";const writePermission=customer?"sales.post":"purchases.post";const canAct=actor.capabilities.includes(writePermission)&&actor.capabilities.includes("dues.allocate");return <main className="content"><p><Link href={`/o/${organizationId}/advances?scope=${customer?"customer":"supplier"}`}>← Advance register</Link></p><p className="eyebrow">{customer?"Customer":"Supplier"} advance</p><h1>{data.document_number}</h1><section className="panel"><p>Original advance: BDT {original}</p><p>Applied: BDT {applied}</p><p>Refunded: BDT {refunded}</p><p>Remaining: BDT {remaining}</p><p>Source document: <Link href={`/o/${organizationId}/accounting/documents/${documentId}`}>{data.document_number}</Link></p>{canAct&&remaining!=="0.00"&&<div className="toolbar"><Link className="secondary" href={`/o/${organizationId}/advances/${openItemId}/apply`}>Apply advance</Link>{actor.capabilities.includes("banking.write")&&<Link className="secondary" href={`/o/${organizationId}/advances/${openItemId}/refund`}>Refund unused balance</Link>}</div>}</section><section className="panel"><h2>Applications, refunds and reversals</h2>{activity.length===0?<p>No applications or refunds are recorded.</p>:<ul>{activity.map((row,i)=><li key={String(row.allocation_id??i)}>{String(row.action_kind??"Advance action")} · BDT {row.amount} · {String(row.effective_date)} · {typeof row.other_document_id==="string"?<Link href={`/o/${organizationId}/accounting/documents/${row.other_document_id}`}>{String(row.other_document_number??row.other_document_type)}</Link>:"Linked financial document"}{row.reversed_on?` · allocation reversed ${String(row.reversed_on)}`:""}{typeof row.reversal_document_id==="string"&&<> · <Link href={`/o/${organizationId}/accounting/documents/${row.reversal_document_id}`}>unapplied by {String(row.reversal_document_number??"reversal")}</Link></>}</li>)}</ul>}</section></main>;
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="NOT_FOUND")redirect("/companies?error=not_found");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You do not have permission to open this advance.</p></main>;throw error;}
}
