"use client";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useState } from "react";
type Row=Record<string,unknown>;
export function CashAccounts({organizationId,rows,options,canWrite}:{organizationId:string;rows:Row[];options:Row[];canWrite:boolean}){const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function create(form:FormData){setBusy(true);setError("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/cash-accounts`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:String(form.get("name")??""),kind:String(form.get("kind")??""),account_id:String(form.get("account_id")??""),institution:String(form.get("institution")??"")||null,masked_account_number:String(form.get("masked_account_number")??"")||null,is_cash_equivalent:form.get("is_cash_equivalent")==="on",allow_negative_balance:form.get("allow_negative_balance")==="on"})});const json=await response.json();if(!response.ok)throw new Error(json?.error?.fields?.body??json?.error?.message??"Could not save the cash account.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save the cash account.");}finally{setBusy(false);}}
 async function archive(id:string){setBusy(true);setError("");try{const response=await fetch(`/api/v1/organizations/${organizationId}/cash-accounts/${id}`,{method:"PATCH"});const json=await response.json();if(!response.ok)throw new Error(json?.error?.message??"Could not archive the account.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not archive the account.");}finally{setBusy(false);}}
 return <main className="content"><p className="eyebrow">Banking</p><h1>Cash and bank accounts</h1><p>Balances come from posted ledger entries. Opening balances are entered through an opening journal; this setup has no editable balance field. Wallet entries do not connect to provider APIs.</p><p>{canWrite&&<Link href={`/o/${organizationId}/banking/import`}>Import a bank statement</Link>} {rows.length>0&&<Link href={`/o/${organizationId}/banking/reconciliations`}>Reconcile a statement</Link>}</p>{error&&<p role="alert">{error}</p>}
 <section className="panel"><h2>Accounts</h2>{rows.length===0?<p>No cash, bank or wallet accounts configured.</p>:<div className="table-scroll"><table><thead><tr><th>Name</th><th>Kind</th><th>Ledger account</th><th>Book balance (BDT)</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={String(row.id)}><td><Link href={`/o/${organizationId}/banking/accounts/${String(row.id)}`}>{String(row.name)}</Link></td><td>{String(row.kind).replaceAll("_"," ")}</td><td>{String(row.account_code)} · {String(row.account_name)}</td><td>{String(row.book_balance)}</td><td>{row.is_active?"Active":"Archived"}</td><td>{canWrite&&row.is_active?<button type="button" className="secondary" disabled={busy} onClick={()=>void archive(String(row.id))}>Archive</button>:"—"}</td></tr>)}</tbody></table></div>}</section>
 {canWrite&&<section className="panel"><h2>Add cash, bank or wallet</h2><form action={create} className="toolbar"><label>Name<input name="name" maxLength={120} required/></label><label>Kind<select name="kind"><option value="cash">Physical cash</option><option value="bank">Bank</option><option value="mobile_wallet">Mobile wallet</option><option value="payment_clearing">Payment clearing</option></select></label><label>Ledger account<select name="account_id" required><option value="">Choose an asset account</option>{options.map(option=><option key={String(option.id)} value={String(option.id)}>{String(option.code)} · {String(option.name)}</option>)}</select></label><label>Institution (optional)<input name="institution" maxLength={120}/></label><label>Masked account number (optional)<input name="masked_account_number" maxLength={80} autoComplete="off"/></label><label><input type="checkbox" name="is_cash_equivalent"/> Include in cash equivalents</label><label><input type="checkbox" name="allow_negative_balance"/> Allow negative book balance</label><button type="submit" disabled={busy}>{busy?"Saving…":"Add account"}</button></form></section>}</main>;
}
