import { parseOrganizationId, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../../server/commands/errors.ts";
import { readJournalRegisterDetail } from "../../../../../../server/documents/journal-register.ts";
import { roleRuntime } from "../../../../../../server/roles/runtime.ts";
export const dynamic="force-dynamic"; export const revalidate=0;
export default async function JournalDetailPage({params}:{params:Promise<{organizationId:string;journalId:string}>}) {
  let organizationId,journalId; try { const p=await params; organizationId=parseOrganizationId(p.organizationId); journalId=parseUuid(p.journalId); } catch { redirect("/companies?error=not_found"); }
  const runtime=await roleRuntime(); if(!runtime.current||runtime.current.organizationId!==organizationId) redirect("/companies?error=context_mismatch");
  try { const actor=await resolveActorContext(organizationId,runtime.dependencies), data=await readJournalRegisterDetail(runtime.client,actor,journalId), lines=Array.isArray(data.lines)?data.lines as Record<string,unknown>[]:[];
    return <main className="content"><p><Link href={`/o/${organizationId}/accounting/journals`}>← Journal register</Link></p><p className="eyebrow">Posted journal · {String(data.source_type).replaceAll("_"," ")}</p><h1>{String(data.document_number)}</h1><section className="panel"><p>Accounting date: {String(data.accounting_date)} · Period: {String(data.period_label)}</p><p>{String(data.description??"")}</p><p>Creator: {String(data.creator)}</p>{actor.capabilities.includes("documents.read")&&<p>Source document: <Link href={`/o/${organizationId}/accounting/documents/${String(data.source_document_id)}`}>{String(data.document_number)}</Link></p>}<p>Debits BDT {String(data.debit_total)} · Credits BDT {String(data.credit_total)}</p>{data.reverses_journal_entry_id&&<p>This entry reverses <Link href={`/o/${organizationId}/accounting/journals/${String(data.reverses_journal_entry_id)}`}>{String(data.reverses_journal_entry_id)}</Link>.</p>}{data.reversal_journal_entry_id&&<p>Reversed on {String(data.reversal_date)} by <Link href={`/o/${organizationId}/accounting/journals/${String(data.reversal_journal_entry_id)}`}>{String(data.reversal_journal_entry_id)}</Link>.</p>}</section><section className="panel"><h2>Immutable ledger lines</h2><div className="table-scroll"><table><thead><tr><th>Line</th><th>Account</th><th>Description</th><th>Debit (BDT)</th><th>Credit (BDT)</th></tr></thead><tbody>{lines.map((line,i)=><tr key={i}><td>{String(line.line_no)}</td><td>{String(line.account_code)} · {String(line.account_name)}</td><td>{String(line.description||"—")}</td><td>{String(line.debit)}</td><td>{String(line.credit)}</td></tr>)}</tbody></table></div></section></main>;
  } catch(error) { if(error instanceof CommandError&&error.code==="UNAUTHENTICATED") redirect("/auth/sign-in?next=/companies"); if(error instanceof CommandError&&error.code==="NOT_FOUND") redirect(`/o/${organizationId}/accounting/journals?error=not_found`); if(error instanceof CommandError&&error.code==="FORBIDDEN") return <main className="content"><h1>Access denied</h1><p>You need ledger.read to view this journal.</p></main>; throw error; }
}
