import { parseOrganizationId,parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { bangladeshDate } from "../../../../../lib/date.ts";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";
import { ReportExportButton } from "../report-export-button.tsx";

export const dynamic="force-dynamic";export const revalidate=0;
type Year={id:string;label:string;starts_on:string;ends_on:string};type Center={id:string;code:string;name:string};
type AccountRow={account_id:string;account_code:string;account_name:string;account_type:"income"|"expense";report_group:string;current_amount:string;comparison_amount:string;current_ledger_debit:string;current_ledger_credit:string;current_summary_debit:string;current_summary_credit:string;current_evidence_document_id:string|null;current_evidence_reference:string|null;comparison_ledger_debit:string;comparison_ledger_credit:string;comparison_summary_debit:string;comparison_summary_credit:string;comparison_evidence_document_id:string|null;comparison_evidence_reference:string|null};
type Totals={revenue:string;direct_costs:string;gross_profit:string;operating_costs:string;other_income:string;other_expenses:string;net_profit:string;comparison_revenue:string;comparison_direct_costs:string;comparison_gross_profit:string;comparison_operating_costs:string;comparison_other_income:string;comparison_other_expenses:string;comparison_net_profit:string};
type Snapshot={snapshot_id:string;company:{name:string;timezone:string};generated_at:string;ledger_cutoff_at:string;provisional:boolean;data:{periods:{current:{from:string;to:string;ytd_summary_included:boolean};comparison:{from:string;to:string;ytd_summary_included:boolean}|null};accounts:AccountRow[];totals:Totals;warnings:string[];provisional:boolean}};
const dateOk=(value:string|null|undefined)=>!!value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(new Date(`${value}T00:00:00Z`).getTime())&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value;
const money=(value:string)=>{if(!/^-?(0|[1-9]\d{0,13})(\.\d{1,2})?$/.test(value))throw new Error("Invalid P&L money value.");return value;};
export default async function ProfitLossPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{from?:string;to?:string;cost_center?:string;comparison_from?:string;comparison_to?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}const query=await searchParams;const today=bangladeshDate();
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 let capabilities:readonly string[];let years:Year[]=[];let centers:Center[]=[];let companyStart="";
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);capabilities=actor.capabilities;if(!capabilities.includes("reports.read"))throw CommandError.forbidden();const options=await runtime.client.rpc("list_profit_loss_options",{p_organization_id:organizationId});if(options.error){if(options.error.code==="42501")throw CommandError.forbidden();throw new Error("P&L filters could not be loaded.");}if(!options.data||typeof options.data!=="object"||Array.isArray(options.data))throw new Error("Invalid P&L options.");const raw=options.data as Record<string,unknown>;if(raw.company&&typeof raw.company==="object"&&!Array.isArray(raw.company))companyStart=String((raw.company as Record<string,unknown>).books_start_date??"");if(Array.isArray(raw.fiscal_years))years=raw.fiscal_years.map(value=>{const row=value as Record<string,unknown>;return{id:parseUuid(row.id),label:String(row.label),starts_on:String(row.starts_on),ends_on:String(row.ends_on)};});if(Array.isArray(raw.cost_centers))centers=raw.cost_centers.map(value=>{const row=value as Record<string,unknown>;return{id:parseUuid(row.id),code:String(row.code),name:String(row.name)};});}
 catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need reports.read to view Profit and Loss.</p></main>;throw error;}
 const year=years.find(item=>item.starts_on<=today&&item.ends_on>=today)??years.at(0);const from=query.from??year?.starts_on??`${today.slice(0,4)}-01-01`;const to=query.to??today;const center=query.cost_center?parseUuid(query.cost_center):null;const comparisonFrom=query.comparison_from??null;const comparisonTo=query.comparison_to??null;
 const invalidComparison=(comparisonFrom===null)!==(comparisonTo===null)||(comparisonFrom!==null&&comparisonTo!==null&&(!dateOk(comparisonFrom)||!dateOk(comparisonTo)||comparisonFrom>comparisonTo||!(to<comparisonFrom||comparisonTo<from)));
 if(!dateOk(from)||!dateOk(to)||from>to||invalidComparison)return <main className="content"><h1>Profit and Loss</h1><p role="alert">Enter valid, non-overlapping report periods.</p></main>;
 let snapshot:Snapshot;try{const result=await runtime.client.rpc("read_profit_loss_snapshot",{p_organization_id:organizationId,p_from:from,p_to:to,p_cost_center_id:center,p_comparison_from:comparisonFrom,p_comparison_to:comparisonTo});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();if(result.error.code==="P0002")throw CommandError.validation({cost_center:"Choose an active cost center in this company."});if(result.error.code==="22023")throw CommandError.validation({period:"Choose a valid report range."});throw new Error("Profit and Loss could not be generated.");}if(!result.data||typeof result.data!=="object"||Array.isArray(result.data))throw new Error("Invalid P&L snapshot.");snapshot=result.data as Snapshot;if(!snapshot.data||!Array.isArray(snapshot.data.accounts)||!snapshot.data.totals)throw new Error("Invalid P&L report data.");}
 catch(error){if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need reports.read to view Profit and Loss.</p></main>;if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="VALIDATION_FAILED")return <main className="content"><h1>Profit and Loss</h1><p role="alert">Check the cost-center and report-period filters.</p></main>;throw error;}
 const data=snapshot.data,totals=data.totals,comparison=!!comparisonFrom;const directMapped=data.accounts.some(row=>row.account_type==="expense"&&row.report_group==="cost_of_sales");const canExport=capabilities.includes("reports.export")&&capabilities.includes("exports.read")&&capabilities.includes("reports.read");const exportQuery=new URLSearchParams({from,to,...(center?{cost_center:center}:{}),...(comparisonFrom&&comparisonTo?{comparison_from:comparisonFrom,comparison_to:comparisonTo}:{ }),format:"json"});
 const glFrom=companyStart&&from<companyStart?companyStart:from;
 function displayed(row:AccountRow,compare=false){const raw=money(compare?row.comparison_amount:row.current_amount);if(row.account_type==="expense"){const value=raw.startsWith("-")?raw.slice(1):`-${raw}`;return value;}return raw;}
 function summary(row:AccountRow,compare=false){const debit=money(compare?row.comparison_summary_debit:row.current_summary_debit),credit=money(compare?row.comparison_summary_credit:row.current_summary_credit);return debit!=="0.00"||credit!=="0.00";}
 return <main className="content"><p className="eyebrow">Reports · {snapshot.company.name}</p><h1>Profit and Loss</h1><p>Accrual performance from posted income and expense accounts. Opening journals and year-close mechanics are excluded. Timezone: {snapshot.company.timezone} · Ledger cutoff: {snapshot.ledger_cutoff_at} · Generated: {snapshot.generated_at}{snapshot.provisional?" · Provisional":""}</p>
  <form method="get" className="panel toolbar"><label>From<input required type="date" name="from" defaultValue={from}/></label><label>To<input required type="date" name="to" defaultValue={to}/></label><label>Cost center<select name="cost_center" defaultValue={center??""}><option value="">All cost centers</option>{centers.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Compare from<input type="date" name="comparison_from" defaultValue={comparisonFrom??""}/></label><label>Compare to<input type="date" name="comparison_to" defaultValue={comparisonTo??""}/></label><button type="submit">Run report</button>{capabilities.includes("reports.export")&&<a className="secondary" href={`/api/v1/organizations/${organizationId}/reports/profit_loss?${exportQuery}`}>Download JSON snapshot</a>}{canExport&&<ReportExportButton organizationId={organizationId} exportType="profit_and_loss" filters={{from,to,...(center?{cost_center:center}:{}),...(comparisonFrom&&comparisonTo?{comparison_from:comparisonFrom,comparison_to:comparisonTo}:{})}}/>}</form>
  {data.warnings.map((warning,index)=><p role="status" key={index}>{warning}</p>)}
  <section className="panel"><h2>Summary · {from} to {to}</h2><dl className="toolbar"><div><dt>Revenue</dt><dd>BDT {totals.revenue}</dd></div><div><dt>Direct costs</dt><dd>BDT {totals.direct_costs}</dd></div><div><dt>Gross profit {directMapped?"":"· no direct-cost accounts mapped"}</dt><dd>{directMapped?`BDT ${totals.gross_profit}`:"—"}</dd></div><div><dt>Operating costs</dt><dd>BDT {totals.operating_costs}</dd></div><div><dt>Other income</dt><dd>BDT {totals.other_income}</dd></div><div><dt>Other expenses</dt><dd>BDT {totals.other_expenses}</dd></div><div><dt>Net profit</dt><dd><strong>BDT {totals.net_profit}</strong></dd></div></dl></section>
  <section className="panel"><h2>Account detail</h2>{data.accounts.length===0?<p>No posted nominal activity is in this period.</p>:<div className="table-scroll"><table><thead><tr><th>Group</th><th>Account</th><th>Current period (BDT)</th>{comparison&&<th>Comparison (BDT)</th>}<th>Detail source</th></tr></thead><tbody>{data.accounts.map(row=>{const hasLedger=row.current_ledger_debit!=="0.00"||row.current_ledger_credit!=="0.00";return <tr key={row.account_id}><td>{row.report_group.replaceAll("_"," ")}</td><td>{hasLedger&&glFrom<=to?<Link href={`/o/${organizationId}/accounting/general-ledger?${new URLSearchParams({account:row.account_id,from:glFrom,to,...(center?{cost_center:center}:{})})}`}>{row.account_code} · {row.account_name}</Link>:<>{row.account_code} · {row.account_name}</>}</td><td>{displayed(row)}</td>{comparison&&<td>{displayed(row,true)}</td>}<td>{summary(row)?<span>Imported YTD summary · {row.current_evidence_reference??"source reference unavailable"} · no transaction-level detail</span>:"Posted ledger"}</td></tr>;})}</tbody></table></div>}{data.periods.current.ytd_summary_included&&<p>The approved pre-cutover YTD summary is included once for this year-to-date range. Its accounts link to post-cutover journal activity; original pre-cutover transactions were not imported.</p>}</section>
 </main>;
}
