import { parseOrganizationId } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { readTrialBalance } from "../../../../../server/reports/ledger.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";
export const dynamic="force-dynamic";export const revalidate=0;
export default async function TrialBalancePage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{as_of?:string;from?:string;cutoff?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId)}catch{redirect("/companies?error=not_found")}const query=await searchParams,asOf=query.as_of??new Date().toISOString().slice(0,10);const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies),report=query.as_of?await readTrialBalance(runtime.client,actor,{asOf,from:query.from,cutoff:query.cutoff}):null,data=report as Record<string,unknown>|null,accounts=Array.isArray(data?.accounts)?data.accounts as Record<string,unknown>[]:[];
  return <main className="content"><p className="eyebrow">Reports</p><h1>Trial balance</h1><p>Balances come from posted journals only. Reversals enter on their own accounting dates; no balancing plug is applied.</p><form className="panel toolbar" action={`/o/${organizationId}/reports/trial-balance`} method="get"><label>As of date<input type="date" name="as_of" required defaultValue={asOf}/></label><label>Movement from (optional)<input type="date" name="from" defaultValue={query.from??""}/></label><button type="submit">Run report</button></form>{data&&<section className="panel"><p>As of {String(data.as_of)} · Snapshot cutoff {String(data.cutoff_at)}</p><p>{String(data.opening_inclusion)} {String(data.closing_inclusion)}</p>{!data.balanced&&<p role="alert"><strong>Blocking imbalance:</strong> trial balance debits {String(data.total_debit)} differ from credits {String(data.total_credit)} by BDT {String(data.difference)}.</p>}<div className="table-scroll"><table><thead><tr><th>Account</th><th>Opening debit</th><th>Opening credit</th><th>Movement debit</th><th>Movement credit</th><th>Closing debit</th><th>Closing credit</th></tr></thead><tbody>{accounts.map((row,i)=><tr key={String(row.account_id??i)}><td>{actor.capabilities.includes("ledger.read")?<Link href={`/o/${organizationId}/accounting/general-ledger?account=${String(row.account_id)}&from=${encodeURIComponent(String(query.from??asOf))}&to=${encodeURIComponent(asOf)}&cutoff=${encodeURIComponent(String(data.cutoff_at))}`}>{String(row.code)} · {String(row.name)}</Link>:<>{String(row.code)} · {String(row.name)}</>}</td><td>{String(row.opening_debit)}</td><td>{String(row.opening_credit)}</td><td>{String(row.movement_debit)}</td><td>{String(row.movement_credit)}</td><td>{String(row.closing_debit)}</td><td>{String(row.closing_credit)}</td></tr>)}</tbody><tfoot><tr><th>Total</th><th colSpan={4}></th><th>{String(data.total_debit)}</th><th>{String(data.total_credit)}</th></tr></tfoot></table></div><p>Difference: BDT {String(data.difference)} · {data.balanced?"Balanced":"Requires investigation"}</p></section>}</main>
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You need reports.read to view the trial balance.</p></main>;if(error instanceof CommandError&&error.code==="VALIDATION_ERROR")return <main className="content"><h1>Invalid filters</h1><p>Choose a valid movement start date and as-of date.</p></main>;throw error;}
}
