import { formatMoney, moneyUnits } from "@ams/accounting";
import { parseOrganizationId, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";

export const dynamic="force-dynamic";export const revalidate=0;
type Row={account_id:string;account_code:string;account_name:string;account_type:string;opening_balance:string;movement_debit:string;movement_credit:string;closing_debit:string;closing_credit:string};
type Snapshot={company?:{name?:string;timezone?:string};generated_at?:string;ledger_cutoff_at?:string;status?:string;provisional?:boolean};
export default async function TrialBalancePage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{as_of?:string;from?:string}>}){
 let organizationId;try{organizationId=parseOrganizationId((await params).organizationId);}catch{redirect("/companies?error=not_found");}
 const q=await searchParams;const today=new Date().toISOString().slice(0,10),asOf=q.as_of||today,from=q.from||null;const dateOk=(v:string|null)=>{if(v===null)return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const parsed=new Date(`${v}T00:00:00.000Z`);return Number.isFinite(parsed.valueOf())&&parsed.toISOString().slice(0,10)===v;};
 if(!dateOk(asOf)||!dateOk(from)||(from&&from>asOf))return <main className="content"><h1>Trial balance</h1><p role="alert">Choose a valid as-of date and movement start date.</p></main>;
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");let rows:Row[]=[],snapshot:Snapshot={},forbidden=false,canExport=false;
 try{const actor=await resolveActorContext(organizationId,runtime.dependencies);if(!actor.capabilities.includes("reports.read"))throw CommandError.forbidden();canExport=actor.capabilities.includes("exports.read");const result=await runtime.client.rpc("read_report_snapshot",{p_organization_id:organizationId,p_report_type:"trial_balance",p_filters:{as_of:asOf,...(from?{from}:{})}});if(result.error){if(result.error.code==="42501")throw CommandError.forbidden();if(result.error.code==="22023")throw CommandError.validation({query:"Choose valid reporting dates."});throw new Error("Trial balance could not be loaded.");}if(!result.data||typeof result.data!=="object"||Array.isArray(result.data))throw new Error("Invalid report snapshot response.");const envelope=result.data as Record<string,unknown>;snapshot={company:envelope.company as Snapshot["company"],generated_at:String(envelope.generated_at??""),ledger_cutoff_at:String(envelope.ledger_cutoff_at??""),status:String(envelope.status??""),provisional:envelope.provisional===true};if(!Array.isArray(envelope.data))throw new Error("Invalid trial balance response.");rows=envelope.data.map((value:unknown)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Invalid balance row.");const row=value as Record<string,unknown>;return{...row,account_id:parseUuid(row.account_id)} as unknown as Row;});}
 catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="FORBIDDEN")forbidden=true;else if(!(error instanceof CommandError))throw error;}
 if(forbidden)return <main className="content"><h1>Access denied</h1><p>You need reports.read to view the trial balance.</p></main>;
 const debit=rows.reduce((sum,row)=>sum+moneyUnits(row.closing_debit),0n),credit=rows.reduce((sum,row)=>sum+moneyUnits(row.closing_credit),0n),difference=debit-credit;
 return <main className="content"><p className="eyebrow">Reports · As of {asOf}</p><h1>Trial balance</h1><p>Posted entries through {asOf}. Reversals are included on their effective accounting dates. Opening balances are entries dated before the optional movement start; closing entries remain included as posted.</p><p>Company: {snapshot.company?.name??"Current company"} · Timezone: {snapshot.company?.timezone??"—"}<br/>Ledger cutoff: {snapshot.ledger_cutoff_at??"—"} · Generated: {snapshot.generated_at??"—"} · {snapshot.provisional?"Provisional":"Posted ledger"}</p>{canExport&&<p><Link className="secondary" href={`/o/${organizationId}/exports`}>View export jobs</Link></p>}<form method="get" className="panel toolbar"><label>As of<input type="date" name="as_of" required defaultValue={asOf}/></label><label>Movement from<input type="date" name="from" max={asOf} defaultValue={from??""}/></label><button type="submit">Refresh</button></form><section className="panel"><div className="table-scroll"><table><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>Opening (BDT)</th><th>Movement debit</th><th>Movement credit</th><th>Closing debit</th><th>Closing credit</th></tr></thead><tbody>{rows.map(row=><tr key={row.account_id}><td>{row.account_code}</td><td><Link href={`/o/${organizationId}/accounting/general-ledger?${new URLSearchParams({account:row.account_id,...(from?{from}:{}) ,to:asOf})}`}>{row.account_name}</Link></td><td>{row.account_type}</td><td>{row.opening_balance}</td><td>{row.movement_debit}</td><td>{row.movement_credit}</td><td>{row.closing_debit}</td><td>{row.closing_credit}</td></tr>)}</tbody><tfoot><tr><th colSpan={6}>Difference (debit − credit)</th><th>{formatMoney(debit)}</th><th>{formatMoney(credit)}</th></tr></tfoot></table></div><p role={difference===0n?"status":"alert"}>Total difference: BDT {formatMoney(difference)}{difference===0n?" · Balanced":" · Blocking imbalance; no balancing plug was added"}</p></section></main>;
}
