import { parseOrganizationId, parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../../server/commands/errors.ts";
import { record } from "../../../../../../server/documents/contracts.ts";
import { roleRuntime } from "../../../../../../server/roles/runtime.ts";
import { AdvanceActionForm } from "../action-form.tsx";
export const dynamic="force-dynamic";export const revalidate=0;
export default async function ApplyAdvancePage({params}:{params:Promise<{organizationId:string;openItemId:string}>}){let organizationId,openItemId;try{const p=await params;organizationId=parseOrganizationId(p.organizationId);openItemId=parseUuid(p.openItemId);}catch{redirect("/companies?error=not_found");}const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");try{const actor=await resolveActorContext(organizationId,runtime.dependencies);const lifecycle=await runtime.client.rpc("read_advance_lifecycle",{p_organization_id:organizationId,p_open_item_id:openItemId});if(lifecycle.error){if(lifecycle.error.code==="P0002")throw CommandError.notFound();if(lifecycle.error.code==="42501")throw CommandError.forbidden();throw new Error("Advance is unavailable.");}const source=record(lifecycle.data,"advance");const customer=source.control_kind==="customer_advance";const capability=customer?"sales.write":"purchases.write";if(!actor.capabilities.includes(capability)||!actor.capabilities.includes("dues.allocate"))throw CommandError.forbidden();const today=new Date().toISOString().slice(0,10);const items=await runtime.client.rpc("read_advance_application_targets",{p_organization_id:organizationId,p_advance_open_item_id:openItemId,p_accounting_date:today});if(items.error||!Array.isArray(items.data))throw new Error("Eligible trade balances could not be loaded.");const targets=items.data.map((v:unknown)=>record(v,"open_item")).map(r=>({id:parseUuid(r.open_item_id),number:typeof r.document_number==="string"?r.document_number:null,date:String(r.issue_date),amount:String(r.available_amount)}));return <main className="content"><p><Link href={`/o/${organizationId}/advances/${openItemId}`}>← Advance</Link></p><p className="eyebrow">Advance application</p><h1>Apply {customer?"customer":"supplier"} advance</h1><p>This creates a controlled reclassification and settles both the advance and trade item. No cash is moved.</p>{targets.length?<AdvanceActionForm organizationId={organizationId} openItemId={openItemId} kind="apply" targetLabel={customer?"Invoice":"Supplier bill"} accountingDate={today} targets={targets}/>:<section className="panel"><p>No same-party open {customer?"invoice":"bill"} balance is available to apply.</p></section>}</main>;}catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="NOT_FOUND")redirect("/companies?error=not_found");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You do not have permission to apply this advance.</p></main>;throw error;}}
