"use client";
import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
export type ContactRecord={id:string;display_name:string;legal_name:string|null;is_customer:boolean;is_vendor:boolean;email:string|null;phone:string|null;billing_address:Record<string,unknown>;tax_identifiers:Record<string,unknown>;payment_terms_days:number;credit_limit:string|null;external_key:string|null;is_active:boolean;row_version:number};
export function ContactForm({organizationId,scope,initial}:{organizationId:string;scope:"customer"|"vendor";initial?:ContactRecord}){
 const router=useRouter();const key=useRef(crypto.randomUUID());const [name,setName]=useState(initial?.display_name??"");const [legal,setLegal]=useState(initial?.legal_name??"");const [customer,setCustomer]=useState(initial?.is_customer??scope==="customer");const [vendor,setVendor]=useState(initial?.is_vendor??scope==="vendor");const [email,setEmail]=useState(initial?.email??"");const [phone,setPhone]=useState(initial?.phone??"");const [terms,setTerms]=useState(String(initial?.payment_terms_days??0));const [credit,setCredit]=useState(initial?.credit_limit??"");const [external,setExternal]=useState(initial?.external_key??"");const [address,setAddress]=useState(JSON.stringify(initial?.billing_address??{},null,2));const [tax,setTax]=useState(JSON.stringify(initial?.tax_identifiers??{},null,2));const [active,setActive]=useState(initial?.is_active??true);const [warning,setWarning]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function checkDuplicate(value:string){setWarning("");if(value.trim().length<3)return;try{const r=await fetch(`/api/v1/organizations/${organizationId}/contacts?scope=${scope}&status=all&search=${encodeURIComponent(value.trim())}&limit=10`);const body=await r.json();const items=body?.data?.items as {id:string;display_name:string}[]|undefined;const duplicate=items?.find(c=>c.id!==initial?.id&&c.display_name.toLocaleLowerCase()===value.trim().toLocaleLowerCase());if(duplicate)setWarning(`A contact named “${duplicate.display_name}” already exists. Check that this is not a duplicate.`);}catch{/* directory remains usable if duplicate lookup fails */}}
 async function save(event:React.FormEvent){event.preventDefault();setError("");let billing_address:Record<string,unknown>,tax_identifiers:Record<string,unknown>;try{billing_address=JSON.parse(address);tax_identifiers=JSON.parse(tax);if(!billing_address||typeof billing_address!=="object"||Array.isArray(billing_address)||!tax_identifiers||typeof tax_identifiers!=="object"||Array.isArray(tax_identifiers))throw new Error();}catch{setError("Address and tax identifiers must be valid JSON objects.");return;}
  setBusy(true);try{const body={expected_version:initial?.row_version??null,contact:{display_name:name,legal_name:legal||null,is_customer:customer,is_vendor:vendor,email:email||null,phone:phone||null,billing_address,tax_identifiers,payment_terms_days:Number(terms),credit_limit:credit||null,external_key:external||null,is_active:active}};
   const path=initial?`/api/v1/organizations/${organizationId}/contacts/${initial.id}`:`/api/v1/organizations/${organizationId}/contacts`;const response=await fetch(path,{method:initial?"PATCH":"POST",headers:{"Content-Type":"application/json","X-Request-Id":`contact-save-${crypto.randomUUID()}`,"Idempotency-Key":key.current},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message??"Contact could not be saved.");key.current=crypto.randomUUID();const resultScope=customer?"customer":"vendor";const resultBase=resultScope==="customer"?"sales/customers":"purchases/vendors";router.push(`/o/${organizationId}/${resultBase}/${initial?result.data.id:""}`.replace(/\/$/,""));router.refresh();
  }catch(e){setError(e instanceof Error?e.message:"Contact could not be saved.");}finally{setBusy(false);}}
 return <form className="panel" onSubmit={save}><label>Display name<input required maxLength={200} value={name} onChange={e=>{setName(e.target.value);void checkDuplicate(e.target.value);}}/></label>{warning&&<p role="status">{warning}</p>}<label>Legal name<input maxLength={200} value={legal} onChange={e=>setLegal(e.target.value)}/></label>
  <fieldset><legend>Business roles</legend><label><input type="checkbox" checked={customer} onChange={e=>setCustomer(e.target.checked)}/> Customer</label><label><input type="checkbox" checked={vendor} onChange={e=>setVendor(e.target.checked)}/> Supplier</label><small>Customer receivables and supplier payables remain separate even when one contact has both roles.</small></fieldset>
  <label>Email<input type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone<input maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Payment terms (days)<input type="number" min={0} max={3650} value={terms} onChange={e=>setTerms(e.target.value)}/></label><label>Credit limit (BDT)<input inputMode="decimal" pattern="(?:0|[1-9][0-9]*)(?:\.[0-9]{1,2})?" value={credit} onChange={e=>setCredit(e.target.value)}/></label>
  <label>Billing address JSON<textarea value={address} onChange={e=>setAddress(e.target.value)}/></label><label>Tax identifiers JSON<textarea value={tax} onChange={e=>setTax(e.target.value)}/></label><label>External reference<input maxLength={160} value={external} onChange={e=>setExternal(e.target.value)}/></label>{initial&&<label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active contact</label>}
  {error&&<p role="alert">{error}</p>}<button disabled={busy||(!customer&&!vendor)}>{busy?"Saving…":initial?"Save contact":"Create contact"}</button></form>;
}
