"use client";
import Link from "next/link";
import {useState} from "react";
type Profile={contact:Record<string,unknown>;as_of:string;balances:Record<string,string>;documents:Record<string,unknown>[];statement:Record<string,unknown>[];activity:Record<string,unknown>[]};
export function ContactProfile({organizationId,scope,profile,canEdit,canWrite}:{organizationId:string;scope:"customer"|"vendor";profile:Profile;canEdit:boolean;canWrite:boolean}){
 const [tab,setTab]=useState("invoices");const c=profile.contact;const customer=scope==="customer";const root=`/o/${organizationId}/${customer?"sales/customers":"purchases/vendors"}`;
 const allowed=customer?{invoices:["invoice"],receipts:["receipt"],credits:["customer_credit","customer_refund"],advances:["customer_advance"]}:{invoices:["bill"],receipts:["vendor_payment"],credits:["vendor_credit","vendor_refund"],advances:["vendor_advance"]};
 const filtered=profile.documents.filter(d=>(allowed[tab as keyof typeof allowed]??[]).includes(String(d.type)));
 function exportStatement(){const lines=[["Date","Document","Control","Side","Original BDT","Balance BDT"],...profile.statement.map(i=>[i.date,i.document_number,i.control_kind,i.side,i.original_amount,i.balance])];const csv=lines.map(row=>row.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(",")).join("\r\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));link.download=`${String(c.display_name).replace(/[^a-z0-9_-]/gi,"_")}-statement.csv`;link.click();URL.revokeObjectURL(link.href);}
 return <><section className="panel"><div className="toolbar"><div><p className="eyebrow">{customer?"Customer":"Supplier"} profile</p><h1>{String(c.display_name)}</h1><p>{String(c.legal_name??"")} · {String(c.email??"")} · {String(c.phone??"")}</p><p>Terms: {String(c.payment_terms_days)} days · Credit limit: BDT {String(c.credit_limit??"Not set")} · External reference: {String(c.external_key??"—")}</p></div><div>{canEdit&&<Link className="secondary" href={`${root}/${String(c.id)}/edit`}>Edit profile</Link>}<p>{Boolean(c.is_active)?"Active":"Archived"}</p></div></div><div className="toolbar"><p>Open {customer?"receivable":"payable"}<br/><strong>BDT {profile.balances.receivable_or_payable}</strong></p><p>Available credits<br/><strong>BDT {profile.balances.available_credits}</strong></p><p>{customer?"Customer":"Supplier"} advances<br/><strong>BDT {profile.balances.advances}</strong></p></div><p>Balances are as of {profile.as_of} in this company’s timezone. Opening balances are maintained through the cutover workflow.</p>{canWrite&&<><p>These actions create drafts. Saving does not move cash; posting remains a separate authorized action.</p><div className="toolbar">{customer?<><Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=invoice&party_id=${String(c.id)}`}>New invoice</Link><Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=receipt&party_id=${String(c.id)}`}>New receipt</Link></>:<><Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=bill&party_id=${String(c.id)}`}>New bill</Link><Link className="secondary" href={`/o/${organizationId}/accounting/documents/new?type=vendor_payment&party_id=${String(c.id)}`}>Draft payment</Link></>}</div></>}</section>
  <section className="panel"><nav aria-label="Financial profile tabs" className="toolbar">{[["invoices",customer?"Invoices":"Bills"],["receipts",customer?"Receipts":"Payments"],["credits","Credits and refunds"],["advances","Advances"],["statement","Statement"],["activity","Activity"]].map(([id,label])=><button key={id} type="button" className={tab===id?"":"secondary"} aria-current={tab===id?"page":undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {tab==="statement"?<><div className="toolbar"><p>As of {profile.as_of} · BDT · customer/supplier control items only.</p><button type="button" className="secondary" onClick={exportStatement}>Export statement CSV</button></div>{profile.statement.length===0?<p>No dated control movements.</p>:<div className="table-scroll"><table><thead><tr><th>Date</th><th>Due</th><th>Document</th><th>Control</th><th>Side</th><th>Original</th><th>Open balance</th></tr></thead><tbody>{profile.statement.map((r,i)=><tr key={`${r.open_item_id}-${i}`}><td>{String(r.date)}</td><td>{String(r.due_date??"—")}</td><td>{String(r.document_number??r.reference)}</td><td>{String(r.control_kind)}</td><td>{String(r.side)}</td><td>{String(r.original_amount)}</td><td>{String(r.balance)}</td></tr>)}</tbody></table></div>}</>:
  tab==="activity"?<>{profile.activity.length===0?<p>No contact changes recorded.</p>:<div className="table-scroll"><table><thead><tr><th>When</th><th>Action</th><th>Reason</th></tr></thead><tbody>{profile.activity.map((a,i)=><tr key={i}><td>{String(a.created_at)}</td><td>{String(a.action)}</td><td>{String(a.reason??"")}</td></tr>)}</tbody></table></div>}<h3>Recent financial activity</h3>{profile.documents.length===0?<p>No source documents yet.</p>:<DocumentTable rows={profile.documents} organizationId={organizationId}/>}</>:
  filtered.length===0?<p>No {tab} recorded.</p>:<DocumentTable rows={filtered} organizationId={organizationId}/>}
  </section></>;
}
function DocumentTable({rows,organizationId}:{rows:Record<string,unknown>[];organizationId:string}){const hasSupplierReference=rows.some(r=>typeof r.supplier_invoice_reference==="string"&&r.supplier_invoice_reference.length>0);return <div className="table-scroll"><table><thead><tr><th>Date</th><th>Type</th><th>Number</th>{hasSupplierReference&&<th>Supplier invoice reference</th>}<th>State</th><th>Amount (BDT)</th><th>Description</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.id}-${i}`}><td>{String(r.date)}</td><td>{String(r.type).replaceAll("_"," ")}</td><td><Link href={`/o/${organizationId}/accounting/documents/${String(r.id)}`}>{String(r.number??"Draft")}</Link></td>{hasSupplierReference&&<td>{String(r.supplier_invoice_reference??"—")}</td>}<td>{String(r.state)}{r.duplicate_supplier_reference===true&&<p role="status">Possible duplicate supplier invoice reference; review before posting.</p>}</td><td>{String(r.amount)}</td><td>{String(r.description??"")}</td></tr>)}</tbody></table></div>;}
