"use client";
import Link from "next/link";
import {useState} from "react";
type Row={id:string;display_name:string;legal_name:string|null;email:string|null;phone:string|null;is_active:boolean;outstanding:string;available_credit:string;advances:string;overdue:string};
type Page={items:Row[];next_cursor:string|null};
export function DirectoryTable({organizationId,scope,initial}:{organizationId:string;scope:"customer"|"vendor";initial:Page}){
 const [page,setPage]=useState(initial);const [query,setQuery]=useState("");const [status,setStatus]=useState("active");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const base=scope==="customer"?`/o/${organizationId}/sales/customers`:`/o/${organizationId}/purchases/vendors`;
 async function load(after?:string,nextStatus=status){setBusy(true);setError("");try{const p=new URLSearchParams({scope,status:nextStatus,limit:"50"});if(query.trim())p.set("search",query.trim());if(after)p.set("after",after);const r=await fetch(`/api/v1/organizations/${organizationId}/contacts?${p}`);const body=await r.json();if(!r.ok)throw new Error(body?.error?.message??"Contacts could not be loaded.");const next=body.data as Page;setPage(old=>after?{items:[...old.items,...next.items],next_cursor:next.next_cursor}:next);}catch(e){setError(e instanceof Error?e.message:"Contacts could not be loaded.");}finally{setBusy(false);}}
 return <section className="panel"><div className="toolbar"><label>Search contacts<input type="search" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void load();}}}/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);void load(undefined,e.target.value);}}><option value="active">Active</option><option value="overdue">Overdue</option><option value="inactive">Archived</option><option value="all">All</option></select></label><button type="button" disabled={busy} onClick={()=>void load()}>{busy?"Loading…":"Search"}</button></div>
 {error&&<p role="alert">{error}</p>}{page.items.length===0?<p>No {scope} contacts match these filters.</p>:<div className="table-scroll"><table><thead><tr><th>Name</th><th>Open {scope==="customer"?"receivables":"payables"} (BDT)</th><th>Overdue (BDT)</th><th>Available credits (BDT)</th><th>Advances (BDT)</th><th>Status</th><th>Actions</th></tr></thead><tbody>{page.items.map(row=><tr key={row.id}><td><Link href={`${base}/${row.id}`}>{row.display_name}</Link><small>{row.email??row.phone??row.legal_name??""}</small></td><td>{row.outstanding}</td><td>{row.overdue}</td><td>{row.available_credit}</td><td>{row.advances}</td><td>{row.is_active?"Active":"Archived"}</td><td><Link href={`${base}/${row.id}`}>Open profile</Link></td></tr>)}</tbody></table></div>}
 {page.next_cursor&&<button type="button" className="secondary" disabled={busy} onClick={()=>void load(page.next_cursor??undefined)}>Load more</button>}</section>;
}
