import {parseOrganizationId} from "@ams/contracts";
import {resolveActorContext} from "../../../../../../server/auth/resolve-actor.ts";
import {commandErrorBody,normalizeCommandError,CommandError} from "../../../../../../server/commands/errors.ts";
import {generateRequestId} from "../../../../../../server/commands/request-context.ts";
import {createOrganizationRouteHandler} from "../../../../../../server/commands/route-adapter.ts";
import {readContactDirectory,saveContactCommand,type ContactScope} from "../../../../../../server/contacts/service.ts";
import {roleRuntime} from "../../../../../../server/roles/runtime.ts";
export async function GET(request:Request,context:{params:Promise<{organizationId:string}>}){const requestId=generateRequestId();try{const organizationId=parseOrganizationId((await context.params).organizationId);const runtime=await roleRuntime();const actor=await resolveActorContext(organizationId,runtime.dependencies);const q=new URL(request.url).searchParams;
 if([...q.keys()].some(k=>!(["scope","search","status","after","limit"] as string[]).includes(k)))throw CommandError.validation({query:"Unknown contact filter."});const scope=q.get("scope");if(scope!=="customer"&&scope!=="vendor")throw CommandError.validation({scope:"Choose customer or vendor."});const status=q.get("status")??"active";if(!["active","inactive","overdue","all"].includes(status))throw CommandError.validation({status:"Choose an active, inactive, overdue, or all filter."});const limit=q.get("limit")??"50";if(!/^(?:[1-9]|[1-9][0-9]|100)$/.test(limit))throw CommandError.validation({limit:"Use a page size of 1-100."});const data=await readContactDirectory(runtime.client,actor,{scope:scope as ContactScope,search:q.get("search"),status:status as "active"|"inactive"|"overdue"|"all",after:q.get("after"),limit:Number(limit)});return Response.json({data,meta:{request_id:requestId,replayed:false}},{headers:{"Cache-Control":"private, no-store"}});
 }catch(error){const e=normalizeCommandError(error);return Response.json(commandErrorBody(e,requestId),{status:e.status,headers:{"Cache-Control":"private, no-store"}});}}
export async function POST(request:Request,context:{params:Promise<{organizationId:string}>}){const runtime=await roleRuntime();return createOrganizationRouteHandler({definition:saveContactCommand(runtime.client,null),dependencies:runtime.dependencies})(request,context);}
