import { parseOrganizationId,parseUuid } from "@ams/contracts";
import Link from "next/link";
import { redirect } from "next/navigation";
import { resolveActorContext } from "../../../../../server/auth/resolve-actor.ts";
import { CommandError } from "../../../../../server/commands/errors.ts";
import { record } from "../../../../../server/documents/contracts.ts";
import { roleRuntime } from "../../../../../server/roles/runtime.ts";

export const dynamic="force-dynamic";export const revalidate=0;
export default async function TransferDetailPage({params}:{params:Promise<{organizationId:string;documentId:string}>}){
 let organizationId,documentId;try{const p=await params;organizationId=parseOrganizationId(p.organizationId);documentId=parseUuid(p.documentId);}catch{redirect("/companies?error=not_found");}
 const runtime=await roleRuntime();if(!runtime.current||runtime.current.organizationId!==organizationId)redirect("/companies?error=context_mismatch");
 try{await resolveActorContext(organizationId,runtime.dependencies);const result=await runtime.client.rpc("read_transfer_lifecycle",{p_organization_id:organizationId,p_document_id:documentId});if(result.error){if(result.error.code==="P0002")throw CommandError.notFound();if(result.error.code==="42501")throw CommandError.forbidden();throw new Error("Transfer details could not be loaded.");}
  const data=record(result.data,"transfer_lifecycle");if(typeof data.document_number!=="string"||typeof data.state!=="string"||typeof data.accounting_date!=="string"||typeof data.reference!=="string"||typeof data.from_account_name!=="string"||typeof data.to_account_name!=="string"||typeof data.principal_amount!=="string"||typeof data.fee_amount!=="string"||typeof data.total_amount!=="string")throw new Error("Invalid transfer detail response.");const approvals=Array.isArray(data.approvals)?data.approvals as Record<string,unknown>[]:[];
  return <main className="content"><p><Link href={`/o/${organizationId}/banking/transfers`}>← Transfers</Link></p><p className="eyebrow">Banking transfer</p><h1>{data.document_number}</h1><section className="panel"><p>Status: {data.state.replaceAll("_"," ")} · Accounting date: {data.accounting_date}</p><p>Reference: {data.reference}</p><p>From: {data.from_account_name} · To: {data.to_account_name}</p><p>Principal: BDT {data.principal_amount} · Fee: BDT {data.fee_amount}{typeof data.fee_account_name==="string"?` · ${data.fee_account_name}`:""} · Total source: BDT {data.total_amount}</p><p>{data.from_is_cash_equivalent===true&&data.to_is_cash_equivalent===true?"Both accounts are cash equivalents; transfer principal is classified as internal.":data.from_is_cash_equivalent!==data.to_is_cash_equivalent?"One account is not a cash equivalent; principal is classified as investing.":"Neither account is a cash equivalent; principal is excluded from cash-equivalent flow."}</p><p><Link href={`/o/${organizationId}/accounting/documents/${documentId}`}>Open source, approval and journal details</Link></p>{typeof data.journal_entry_id==="string"&&<p>Posted journal: {data.journal_entry_id}</p>}</section><section className="panel"><h2>Approval history</h2>{approvals.length===0?<p>No approval request yet.</p>:approvals.map((row,i)=><div key={String(row.id??i)}><p>{String(row.state)} · version {String(row.version)} · {String(row.created_at)}</p>{Array.isArray(row.decisions)&&(row.decisions as Record<string,unknown>[]).map((decision,j)=><p key={j}>{String(decision.decision)} · {String(decision.created_at)}{decision.reason?` · ${decision.reason}`:""}</p>)}</div>)}</section></main>;
 }catch(error){if(error instanceof CommandError&&error.code==="UNAUTHENTICATED")redirect("/auth/sign-in?next=/companies");if(error instanceof CommandError&&error.code==="NOT_FOUND")redirect("/companies?error=not_found");if(error instanceof CommandError&&error.code==="FORBIDDEN")return <main className="content"><h1>Access denied</h1><p>You do not have permission to open this transfer.</p></main>;throw error;}
}
